### ISSUE TITLE
how to download model

### ISSUE THREAD

**Issue by litongjava** [2noise/ChatTTS#1]
Hi
Where can I download the model for the project?

**Comment by ye7love7** [comment]
model目录下的两个model似乎是模型架构，同问模型参数哪里可以下载呀？

**Comment by luoyiroy** [comment]
> model目录下的两个model似乎是模型架构，同问模型参数哪里可以下载呀？

I found some checkpoint file here, who can help for verify it?
https://huggingface.co/2Noise/ChatTTS

**Comment by lich99** [comment]
When running load_models(), the models will be automatically downloaded from Hugging Face. 
The HF link is: [https://huggingface.co/2Noise/ChatTTS](url)

**Comment by OnceJune** [comment]
请问用的是什么 tokenizer 啊？
