### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by zgimszhd61** [2noise/ChatTTS#100]
我在colab运行，这个报错如何解决？

**Comment by Ethenlalala** [comment]
> 我在colab运行，这个报错如何解决？

我猜你跟我一样，起手就是`pip install chattts`，目前这个项目还不能直接pip install
参考下面这个[colab示例](https://colab.research.google.com/drive/1_Ma1BXvIrYw9kO4UYsSG4GaFkttbS1wY?usp=sharing)就可以正常运行。
示例来源[哔站视频](https://www.bilibili.com/video/BV1hi421S7Qd/?spm_id_from=333.1007.tianma.2-2-5.click&vd_source=ef3ab6128248f8e2a68b54b175c203fc)
