### ISSUE TITLE
core.py升级，插件不兼容

### ISSUE THREAD

**Issue by samqin123** [2noise/ChatTTS#101]
python=3.10
pip install -r 正常
pip install nemo_tools 正常

代码
‘’‘
import ChatTTS
import soundfile as sf

chat = ChatTTS.Chat()
chat.load_models()
texts = ["你好",]
wavs = chat.infer(texts, use_decoder=True)
sf.write(r"D:\Desktop\chattts.wav", wavs[0][0], 24000)
’‘’

报错内容
‘’‘
Traceback (most recent call last):
  File "/Users/user/Downloads/ChatTTS/import ChatTTS.py", line 7, in <module>
    wavs = chat.infer(texts, use_decoder=True)
  File "/Users/user/Downloads/ChatTTS/ChatTTS/core.py", line 144, in infer
    self.init_normalizer(_lang)
  File "/Users/user/Downloads/ChatTTS/ChatTTS/core.py", line 181, in init_normalizer
    from nemo_text_processing.text_normalization.normalize import Normalizer
ModuleNotFoundError: No module named 'nemo_text_processing'
’‘’

**Comment by samqin123** [comment]
omegaconf也有问题报错

**Comment by ZaymeShaw** [comment]
同。这个包装起来好多兼容问题。查了下好像是用来解决数字/标点符号转口语问题的

**Comment by aisaveflower** [comment]
注意：这应该适用于任何带有 x86_64 的 Linux 操作系统。由于依赖项[Pynini](https://www.openfst.org/twiki/bin/view/GRM/Pynini) ，不支持在 MacOS 和 Windows 上安装 Pip 。在 Linux x86_64 以外的平台上，从 Pip 安装会尝试从头开始编译 Pynini，并要求 OpenFst 标头和库位于预期的位置。所以如果它为你工作，那是因为你碰巧在正确的位置以正确的方式安装了 OpenFst。所以如果你想在 MacOS 上使用 Pip 安装 Pynini，你必须预编译和预安装 OpenFst。该版本的 Pynini README 应该会告诉您它需要哪个版本以及--enable-foo使用哪些标志。相反，我们建议您使用 conda-forge 在 MacOS 或 Windows 上安装 Pynini conda install -c conda-forge pynini=2.1.5：。
要在window上安装这个模块
先运行：conda install -c conda-forge pynini=2.1.5
再运行：pip install nemo_text_processing

**Comment by samqin123** [comment]
mac还是报错，无法安装成功pynini

**Comment by samqin123** [comment]
<img width="961" alt="iShot_2024-05-31_22 19 54" src="https://github.com/2noise/ChatTTS/assets/103937568/78de4ae9-1c3b-4374-b7ca-f88a2df0b782">
