### ISSUE TITLE
modelscope中缺少 spk_stat.pt

### ISSUE THREAD

**Issue by jianchang512** [2noise/ChatTTS#107]
改成从 modelscope下载模型后，下载成功运行时提示`AssertionError: Missing spk_stat.pt: **/pzc163/chatTTS/asset/spk_stat.pt`

从 https://huggingface.co/2Noise/ChatTTS/blob/main/asset/spk_stat.pt 下载 spk_stat.pt 复制到 asset 目录后问题解决

**Comment by Cassianvale** [comment]
我也遇到了这个问题，感谢！

**Comment by Amigosen** [comment]
这个网站打不开了，有好心人上传一下文件吗？

**Comment by Cassianvale** [comment]
> 这个网站打不开了，有好心人上传一下文件吗？

一直可以打开，可能是因为你没有科学上网，国内是不墙github的，但是huggingface你可能就上不去了

**Comment by Amigosen** [comment]
@Cassianvale  大哥能有时间的时候发我一下文件吗，我用的公司的网络，科学上不去，感谢感谢，给您磕一个

**Comment by jianchang512** [comment]
https://www.modelscope.cn/api/v1/models/mirror013/ChatTTS/repo?Revision=master&FilePath=asset%2Fspk_stat.pt

从这里下载，魔塔社区
