### ISSUE TITLE
如何正确读链接？

### ISSUE THREAD

**Issue by yanglbme** [2noise/ChatTTS#114]
我的文本中带有一些超链接，如何能让他准确读出来？

示例文本：

```python
texts = [
'''我们社区开源了一款 markdown 编辑器，项目开源地址是 https://github.com/doocs/md，欢迎使用
''']
```

**Comment by yanglbme** [comment]
利用 chatTTS，目前生成了以下音频：

[voice.webm](https://github.com/2noise/ChatTTS/assets/21008209/383f5a30-cf9b-45fe-9ef3-299b7f91c0c1)

**Comment by jinde98** [comment]
我也发现阿拉伯数字无法正确读出来。
