### ISSUE TITLE
合成数字时，效果不佳，如合成『我有145元钱 "』

### ISSUE THREAD

**Issue by bestlee666** [2noise/ChatTTS#117]
合成输出时，效果不佳，如合成『我有145元钱 "』

**Comment by lich99** [comment]
手动把数字改为文字或者用TN

**Comment by xeden3** [comment]
> 手动把数字改为文字或者用TN

TN是啥？

**Comment by NateYeh** [comment]
`from cn2an import an2cn
def convert_arabic_to_chinese_in_string(s):
    def replace_func(match):
        number = match.group(0)
        return an2cn(number)

    # 匹配所有的阿拉伯数字
    converted_str = re.sub(r'\d+', replace_func, s)
    return converted_str`

**Comment by NateYeh** [comment]
```
from cn2an import an2cn

def convert_arabic_to_chinese_in_string(s):
    def replace_func(match):
        number = match.group(0)
        return an2cn(number)

    # 匹配所有的阿拉伯数字
    converted_str = re.sub(r'\d+', replace_func, s)
    return converted_str
```

**Comment by jonahzheng** [comment]
刚才试了一下，现在的版本可以正确读出‘我有145元钱’
