### ISSUE TITLE
Would you upload the model to Modelscope

### ISSUE THREAD

**Issue by yaoper** [2noise/ChatTTS#12]
Would you upload the model to Modelscope

**Comment by anyvoiceai** [comment]
Maybe anyone else could help us to upload to modelscope?

**Comment by pzc163** [comment]
i have upload models to modelscope，pls refer https://www.modelscope.cn/models/pzc163/chatTTS

**Comment by yaoper** [comment]
> i have upload models to modelscope，pls refer https://www.modelscope.cn/models/pzc163/chatTTS

Thanks~
