### ISSUE TITLE
Load Model这一步报错UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by OrgTune** [2noise/ChatTTS#122]
Load Model这一步报错：UnpicklingError: invalid load key, 'v'
<img width="904" alt="截屏2024-05-31 11 38 19" src="https://github.com/2noise/ChatTTS/assets/151126262/dd42ac59-a01c-4913-b2ac-b4d25b9555e6">

**Comment by zhangjinming** [comment]
encountered the same problem,Is there a problem with the models version?
models
git clone https://huggingface.co/2Noise/ChatTTS.git models

error log:
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
Traceback (most recent call last):
  File "/Users/jmingzhang/Desktop/work/company/go/src/example/tts/ChatTTS-webui/api/base.py", line 33, in <module>
    chat.load_models(source='local', local_path=model_path)
  File "/Users/jmingzhang/Desktop/work/company/go/src/example/tts/ChatTTS-webui/api/ChatTTS/ChatTTS/core.py", line 61, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
  File "/Users/jmingzhang/Desktop/work/company/go/src/example/tts/ChatTTS-webui/api/ChatTTS/ChatTTS/core.py", line 84, in _load
    vocos.load_state_dict(torch.load(vocos_ckpt_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by zhangjinming** [comment]
这个问题是模型文件下载不对。 git 默认没有下载模型大文件。
手动去 https://huggingface.co/2Noise/ChatTTS/tree/main/asset 下载
<img width="777" alt="image" src="https://github.com/2noise/ChatTTS/assets/4297688/4c67a9f2-c20a-4c9d-be09-f013be34efe3">

**Comment by OrgTune** [comment]
> 这个问题是模型文件下载不对。 git 默认没有下载模型大文件。 手动去 https://huggingface.co/2Noise/ChatTTS/tree/main/asset 下载 <img alt="image" width="777" src="https://private-user-images.githubusercontent.com/4297688/335451091-4c67a9f2-c20a-4c9d-be09-f013be34efe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzUxNjAsIm5iZiI6MTcxNzEzNDg2MCwicGF0aCI6Ii80Mjk3Njg4LzMzNTQ1MTA5MS00YzY3YTlmMi1jMjBhLTRjOWQtYmUwOS1mMDEzYmUzNGVmZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDU1NDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBlNDFiZGJlYTIzOGUwNjk5YTE5Mjg4NWU4YjExMWE0MzBlODk5ZTRkNzAzNzQyNGI2ZWYxYjg5ZTBiZTI4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yEkP7ukmgKF81cKbLN1t0xjunnjbl1GiwouVXDK-Sf0">

感谢！！！
