### ISSUE TITLE
关于laugh break oral的参数设置还有语速设置

### ISSUE THREAD

**Issue by flyfox666** [2noise/ChatTTS#126]
试用了下感觉很棒，关于高阶用法下的laugh break 还有oral的参数设定有详细点的教程么？还有有没有官方参数可以设置语速啊?

**Comment by lich99** [comment]
example里有语速, eg: [speed_5]

**Comment by flyfox666** [comment]
> speed
好的，非常感谢，主要我就是在github里的example里没看到。。

inputs_en = """
chat T T S is a text to speech model designed for dialogue applications. 
[uv_break]it supports mixed language input [uv_break]and offers multi speaker 
capabilities with precise control over prosodic elements [laugh]like like 
[uv_break]laughter[laugh], [uv_break]pauses, [uv_break]and intonation. 
[uv_break]it delivers natural and expressive speech,[uv_break]so please
[uv_break] use the project responsibly at your own risk.[uv_break]
""".replace('\n', '') # English is still experimental.

params_refine_text = {
  'prompt': '[oral_2][laugh_0][break_4]'
} 
audio_array_cn = chat.infer(inputs_cn, params_refine_text=params_refine_text)
audio_array_en = chat.infer(inputs_en, params_refine_text=params_refine_text)

**Comment by flyfox666** [comment]
> example里有语速, eg: [speed_5]

刚才进example.ipynb里看到了。感谢

**Comment by station19** [comment]
如果想使用笑声，要怎么设置啊？一直没效果
