### ISSUE TITLE
未找到文件 [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by youzeliang** [2noise/ChatTTS#127]
运行的时候 一直报

FileNotFoundError: [Errno 2] No such file or directory: 

所以 mac 用户的这个 /Users/xxxx/.cache/huggingface/hub/model 路径下的配置是要如何去生成呢

**Comment by Ethenlalala** [comment]
> 运行的时候 一直报
> 
> FileNotFoundError: [Errno 2] No such file or directory:
> 
> 所以 mac 用户的这个 /Users/xxxx/.cache/huggingface/hub/model 路径下的配置是要如何去生成呢

参考下这个：https://github.com/2noise/ChatTTS/issues/82
