### ISSUE TITLE
You obviously bought github stars

### ISSUE THREAD

**Issue by dnlsndr** [2noise/ChatTTS#129]
It is quite obvious that you've bought your github stars and forks.
A project no more than 4 days old, having exactly 10k stars and almost exactly 1000 forks? Come on guys, it's a disgrace that you have to steep to such a low level just to push your research in the github alogorithm.

Obviously this issue will be deleted immediately, but it had to be said.
For anybody that's not part of this fraud, you can check out their star evolution here:
https://star-history.com/#2noise/ChatTTS&Timeline

**Comment by yihong0618** [comment]
you can search the project name on twitter on HN to check the trending
or you can visit the video link in README to check the play count。
Please stop your unfounded accusations.Click to apply its very rude and have no evidence.

**Comment by yihong0618** [comment]
@dnlsndr and seems the user bought a lot of thumbs down, for your bad manners 
you can also check it.

**Comment by wrench1997** [comment]
They have done traffic promotion on the Chinese website. It should not be difficult to increase the number of stars.

**Comment by wrench1997** [comment]
> It is quite obvious that you've bought your github stars and forks. A project no more than 4 days old, having exactly 10k stars and almost exactly 1000 forks? Come on guys, it's a disgrace that you have to steep to such a low level just to push your research in the github alogorithm.
> 
> Obviously this issue will be deleted immediately, but it had to be said. For anybody that's not part of this fraud, you can check out their star evolution here: https://star-history.com/#2noise/ChatTTS&Timeline

They have done traffic promotion on the Chinese website. It should not be difficult to increase the number of stars.

**Comment by Richard0403** [comment]
As a foreigner, you can't imagine how good this project is for Chinese pronunciation

**Comment by dnlsndr** [comment]
My, bad just seemed sketchy. I take back my accusations then.

**Comment by furqan4545** [comment]
@dnlsndr  Get a F life bro. Focus on their work, not stars.

**Comment by pcdd-group** [comment]
> 我的坏话似乎有点牵强。我撤销了我的指控。

China has a large population.
