### ISSUE TITLE
NameError: name 'chat' is not defined

### ISSUE THREAD

**Issue by tiandaoyuxi** [2noise/ChatTTS#131]
(venv) D:\ChatTTS>python test_a.py
Traceback (most recent call last):
  File "D:\ChatTTS\test_a.py", line 23, in <module>
    wav = chat.infer("<我是一段真人语音测试，认识大家很高兴！>", params_refine_text=params_refine_text, params_infer_code=params_infer_code)
          ^^^^
NameError: name 'chat' is not defined

**Comment by Ethenlalala** [comment]
> (venv) D:\ChatTTS>python test_a.py Traceback (most recent call last): File "D:\ChatTTS\test_a.py", line 23, in wav = chat.infer("<我是一段真人语音测试，认识大家很高兴！>", params_refine_text=params_refine_text, params_infer_code=params_infer_code) ^^^^ NameError: name 'chat' is not defined

报错意思chat没有被定义，你写脚本的时候漏了几行吧。。。
