### ISSUE TITLE
执行完无任何输出

### ISSUE THREAD

**Issue by youzeliang** [2noise/ChatTTS#132]
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
INFO:ChatTTS.core:All initialized.
  0%|          | 0/384 [00:00<?, ?it/s]DEBUG CHECK FAILED: /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/dynamo/cpython_defs.c:124

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)

执行完就是以上信息了。大家有遇到这种情况吗

**Comment by miniminibox** [comment]
我也这样,蹲一个后续  有时候运气好的话可以输出一个音频,但是大多数时间都是空白输出

**Comment by Ethenlalala** [comment]
> WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead INFO:ChatTTS.core:use cpu INFO:ChatTTS.core:vocos loaded. INFO:ChatTTS.core:dvae loaded. INFO:ChatTTS.core:gpt loaded. INFO:ChatTTS.core:decoder loaded. INFO:ChatTTS.core:tokenizer loaded. INFO:ChatTTS.core:All initialized. INFO:ChatTTS.core:All initialized. 0%| | 0/384 [00:00<?, ?it/s]DEBUG CHECK FAILED: /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/dynamo/cpython_defs.c:124
> 
> Process finished with exit code 134 (interrupted by signal 6:SIGABRT)
> 
> 执行完就是以上信息了。大家有遇到这种情况吗

要不百度或问问chatgpt把，最后一句显示执行中断了。。。

**Comment by youzeliang** [comment]
试过。让我换版本来着

**Comment by superuranus** [comment]
检查cuda和torch版本，torch要用+cu的版本
