### ISSUE TITLE
InvalidCxxCompiler: No working C++ compiler found in torch._inductor.config.cpp.cxx: (None, 'g++')

### ISSUE THREAD

**Issue by While941** [2noise/ChatTTS#133]
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
InvalidCxxCompiler: No working C++ compiler found in torch._inductor.config.cpp.cxx: (None, 'g++')

Python版本：3.10.4
操作系统：win10

按照环境安装的方式安装，torch~=2.1.0 安装了2.1.2的版本，到安装vocos的时候，会自动卸载torch2.1.2版本然后自动安装2.3.0，信息如下：
"Installing collected packages: torch, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 2.1.2
    Uninstalling torch-2.1.2:
      Successfully uninstalled torch-2.1.2
Successfully installed torch-2.3.0 torchaudio-2.3.0"

然后运行demo就会报无法找到c++编译器的问题。

猜测是torch版本的问题？

**Comment by While941** [comment]
修改了一下core.py下的compile: bool = False, 不让她编译了，就运行成功了，但是没有任何反应，跑完进度之后一点反应也没有

**Comment by While941** [comment]
就跑完了之后，没有音频是什么意思

**Comment by leiyu-boy** [comment]
torch._dynamo.config.suppress_errors = True，加上这个

**Comment by While941** [comment]
> 就跑完了之后，没有音频是什么意思

原来是没保存这个音频，但是咋保存呀0.0

**Comment by leiyu-boy** [comment]
> > 就跑完了之后，没有音频是什么意思
> 
> 原来是没保存这个音频，但是咋保存呀0.0

import ChatTTS
import soundfile as sf
import torch

torch._dynamo.config.suppress_errors = True

chat = ChatTTS.Chat()
chat.load_models(source='local', local_path='ChatTTS/hub')
texts = ["请注意，这个人叫小帅"]
wavs = chat.infer(texts, use_decoder=True)
sf.write("test.wav", wavs[0][0], 24000)

**Comment by While941** [comment]
> > > 就跑完了之后，没有音频是什么意思
> > 
> > 
> > 原来是没保存这个音频，但是咋保存呀0.0
> 
> import ChatTTS import soundfile as sf import torch
> 
> torch._dynamo.config.suppress_errors = True
> 
> chat = ChatTTS.Chat() chat.load_models(source='local', local_path='ChatTTS/hub') texts = ["请注意，这个人叫小帅"] wavs = chat.infer(texts, use_decoder=True) sf.write("test.wav", wavs[0][0], 24000)

感谢大佬！不会用python，啥库都不懂。。
