### ISSUE TITLE
还没把代码运行起来的可以用这个docker镜像体验一下

### ISSUE THREAD

**Issue by shengbox** [2noise/ChatTTS#136]
还没把代码运行起来的可以用这个docker镜像体验一下

docker run --rm -p 3000:3000 -it registry.cn-hangzhou.aliyuncs.com/shengbox/chattts_webui

来源于 @Gouryella  的开源项目 https://github.com/Gouryella/ChatTTS-webui

**Comment by nullcache** [comment]
启动时候说的是8000端口，实际上应该是3000端口，这个能优化下提示吗

**Comment by shengbox** [comment]
3000:前端界面端口
8000:API端口
