### ISSUE TITLE
速度问题，明明有GPU但是运行好慢

### ISSUE THREAD

**Issue by DragonWang-cell** [2noise/ChatTTS#138]
![image](https://github.com/2noise/ChatTTS/assets/56779824/e0fda9bd-04e7-405f-96a1-541f27874fe8)
平均1.34it/s，这正常吗，怎么回事啊，显卡如下图：
![image](https://github.com/2noise/ChatTTS/assets/56779824/3eaf4061-7239-4fee-9483-7cfeb376bb46)
推理的时候根本没占用gpu，这是什么问题啊？

**Comment by hungtooc** [comment]
+1

**Comment by h00cker** [comment]
我也一样，感觉就没使用GPU

**Comment by jianchang512** [comment]
更新下显卡驱动，安装 cuda11.8+

**Comment by jiedo** [comment]
预编译compile选项为True时, gpu就不工作了, 可以改为False @lich99
