### ISSUE TITLE
无法生成语音

### ISSUE THREAD

**Issue by swizardlv** [2noise/ChatTTS#139]
<img width="1685" alt="image" src="https://github.com/2noise/ChatTTS/assets/10117682/aa8fba07-868f-4172-9910-884710233fb8">
正常安装，在UI里输入文字，生成语音时无限等待。

**Comment by jianchang512** [comment]
文字很长吗
缩短点试试
或者重新运行下

modelscope下载模型会缺少一个pt文件，是否已下载了

**Comment by wulaoer011** [comment]
试一试

**Comment by swizardlv** [comment]
> 文字很长吗 缩短点试试 或者重新运行下
> 
> modelscope下载模型会缺少一个pt文件，是否已下载了 查看 #107
谢谢回复
文件已下载， 要转的文字很短，重新运行过了

**Comment by charSLee013** [comment]
> <img alt="image" width="1685" src="https://private-user-images.githubusercontent.com/10117682/335533792-aa8fba07-868f-4172-9910-884710233fb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjIyMjcsIm5iZiI6MTcxNzE2MTkyNywicGF0aCI6Ii8xMDExNzY4Mi8zMzU1MzM3OTItYWE4ZmJhMDctODY4Zi00MTcyLTk5MTAtODg0NzEwMjMzZmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDEzMjUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyN2Y1YjJmZGMzZDM5ZmJlNjhkM2E4MWI1YzhiZjhhM2E4NTZjMmE1YWVhMTEwOWJmYmFkZmQ4Mjc0NzIxNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oxod2VYq5W4cDQC9dS93N2SXMAfTzX6zFKPPQNp63Ns"> 正常安装，在UI里输入文字，生成语音时无限等待。

看起来像是`compile`的时候卡住了，将`compile=False`解决这个问题

```python
chat = ChatTTS.Chat()
chat.load_models(
    source="local",
    local_path=model_dir,
    compile=False,   <- 关闭compile
)
```

**Comment by jianchang512** [comment]
使用源码方式部署
按楼上所说方式试试

**Comment by SternBurge** [comment]
> ![QQ截图20240531184719](https://private-user-images.githubusercontent.com/171319163/335548984-9f75f504-aca7-48fe-9570-9e113f3847c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTI5MDIsIm5iZiI6MTcxNzIxMjYwMiwicGF0aCI6Ii8xNzEzMTkxNjMvMzM1NTQ4OTg0LTlmNzVmNTA0LWFjYTctNDhmZS05NTcwLTllMTEzZjM4NDdjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMzMwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTg1OTZmZGUwZDBjYjVkYmU2ZjY2ZGY5OTExMDUyZjkzZGZkM2Q5MjMzNGFiMzk5ZTdlYmQwYzc2YzI0NzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3bgoQP18a_kKVpmXj_j3cc0LgFBsXGiCTygj93qf8mM) This is my codes

when I run the program in the jupyter instead of pycharm ,it work!
