### ISSUE TITLE
WARNING:ChatTTS.core:vocos not initialized.

### ISSUE THREAD

**Issue by lyzhang1999** [2noise/ChatTTS#14]
When I try to run this code:

```
chat = ChatTTS.Chat()
chat.load_models()
```

output: 
```
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
```

How can I solve this problem?

**Comment by zou8944** [comment]
@lyzhang1999 how did you solve this problem finally ?

**Comment by kwin1412** [comment]
when you download models in local,using with
`chat = ChatTTS.Chat()
chat.load_models(
    source="local",
    local_path="./"
)`

**Comment by KiwiHana** [comment]
> source="local",
>     local_path="./"

    chat.load_models(source="local",local_path="./")
TypeError: Chat.load_models() got an unexpected keyword argument 'source'

./asset
./config
./run.py
