### ISSUE TITLE
错误：TypeError: Chat.load_models() got an unexpected keyword argument 'compile'

### ISSUE THREAD

**Issue by tocer** [2noise/ChatTTS#140]
$ python basic.py
Traceback (most recent call last):
  File "/home/dm/projects/chattts-demo/basic.py", line 5, in <module>
    chat.load_models(compile=False) # 设置为True以获得更快速度
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chat.load_models() got an unexpected keyword argument 'compile'

**Comment by sskeysskey** [comment]
same problem, same question, plz help and answer me....

**Comment by cphmvp** [comment]
same problem

**Comment by Losap** [comment]
same problem, how to solve it?

**Comment by Losap** [comment]
import torch
torch._dynamo.config.cache_size_limit = 64
torch._dynamo.config.suppress_errors = True
torch.set_float32_matmul_precision('high')



you need this

**Comment by Losap** [comment]
https://github.com/2noise/ChatTTS/blob/main/example.ipynb  
here is the example

**Comment by wnpllrzodiac** [comment]
same problem

**Comment by chinlee1523** [comment]
> import torch torch._dynamo.config.cache_size_limit = 64 torch._dynamo.config.suppress_errors = True torch.set_float32_matmul_precision('high')
> 
> you need this

加了这几行还是报错啊

**Comment by wnpllrzodiac** [comment]
code workable on a linux machine hosted in usa
need to download model files in runtime, which was not available in china mainland.

**Comment by ChangeY1n** [comment]
不需要直接pip install ChatTTS ,如果之前pip安装了需要uninstall

**Comment by cphmvp** [comment]
有解决的么
