### ISSUE TITLE
为什么不能固定音色

### ISSUE THREAD

**Issue by craii** [2noise/ChatTTS#141]
```
def generate_speaker_tensor(mean: float = 0.0, std: float = 15.247) -> torch.Tensor:
    return torch.normal(mean, std, size=(768,))


def generate_speaker_tensor_a() -> torch.Tensor:
    std, mean = torch.load(f'{Path(__file__).resolve().parent}/models/asset/spk_stat.pt').chunk(2)
    rand_spk = torch.randn(768) * std + mean
    return rand_spk
```

使用 generate_speaker_tensor 生成speaker1 和 generate_speaker_tensor_a 生成speaker2 ，然后分别保存到本地；
在推理时，本地加载speaker1 以及 speaker2 修改 params_infer_code 中的 rand_spk并生成多个语音
···
params_infer_code = {
  'spk_emb': rand_spk, # add sampled speaker 
  'temperature': .3, # using custom temperature
  'top_P': 0.7, # top P decode
  'top_K': 20, # top K decode
}
···

为什么 speaker2 可以相对固定音色，但 speaker1则不行且每次都不同？

**Comment by 6drf21e** [comment]
我固定后大部分音色基本一致 小部分不行  稳定性差的甚至会忽男忽女
感觉需要挑一挑

**Comment by prolenking** [comment]
我看音色也就是speaker是一个向量化的数据，目前虽然是不太固定的，搞不好之后能够开放对speaker的描述决定音色，比如：”一个声音很像周杰伦的人“，可能会放在付费版本里面。

但我觉得这可能有更高的一层道德风险，如果音色可控的话，就更加有可能被用于诈骗等犯罪领域。

**Comment by 6drf21e** [comment]
https://modelscope.cn/studios/ttwwwaa/ChatTTS_Speaker 可以去这里找找 rank 高的稳定性还可以。
