### ISSUE TITLE
运行时报错显示core未初始化

### ISSUE THREAD

**Issue by Franklin-Fred** [2noise/ChatTTS#143]
运行样例时报错，所用代码如下：
import ChatTTS  
from IPython.display import Audio  
  
chat = ChatTTS.Chat()  
chat.load_models()  
  
texts = ["PUT YOUR TEXT HERE",]  
  
wavs = chat.infer(texts, use_decoder=True)  
Audio(wavs[0], rate=24_000, autoplay=True)

运行结果如下：
runfile('C:/Users/user/untitled0.py', wdir='C:/Users/user')
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:decoder not initialized.
Traceback (most recent call last):

  File ~\mambaforge\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\user\untitled0.py:16
    wavs = chat.infer(texts, use_decoder=True)

  File ~\mambaforge\lib\site-packages\ChatTTS\core.py:95 in infer
    assert self.check_model(use_decoder=use_decoder)

AssertionError

**Comment by 1771801582** [comment]
同样error, 怎么解

**Comment by YoungWiller** [comment]
同，有解吗

**Comment by 1771801582** [comment]
在Miniconda 里重新搞了一遍才好,Windows下感觉是Pynini 不兼容然后导致WeTextProcessing & nemo_text_processing 一直报错, 在conda虚拟环境部署或者纯Linux比较容易

**Comment by KiwiHana** [comment]
> 在Miniconda 里重新搞了一遍才好,Windows下感觉是Pynini 不兼容然后导致WeTextProcessing & nemo_text_processing 一直报错, 在conda虚拟环境部署或者纯Linux比较容易

我在windows的Miniconda和conda都不成功，就是pynini安装报错。
```
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
Failed to build pynini
ERROR: Could not build wheels for pynini, which is required to install pyproject.toml-based projects
```
在Ubuntu22.04用miniconda可以安装成功pynini

```
INFO:ChatTTS.core:Load from local: ./model
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.

```

**Comment by KiwiHana** [comment]
windows 10 用anaconda prompt，然后使用这个安装指南https://github.com/libukai/Awesome-ChatTTS?tab=readme-ov-file，可以解决core未初始化的问题

**Comment by fumiama** [comment]
fixed in the latest version.

**Comment by AMAG-AB** [comment]
最新版还是报错。
download to local path /home/zbb/ChatTTS failed.
vocos not initialized.
gpt not initialized.
tokenizer not initialized.
decoder not initialized.
Traceback (most recent call last):
  File "/home/zbb/ChatTTS/test.py", line 10, in <module>
    wavs = chat.infer(texts)
  File "/home/zbb/ChatTTS/ChatTTS/core.py", line 236, in infer
    return next(res_gen)
  File "/home/zbb/ChatTTS/ChatTTS/core.py", line 348, in _infer
    assert self.has_loaded(use_decoder=use_decoder)
AssertionError
