### ISSUE TITLE
Unnecessary memory consumption with forward method in dvae.py

### ISSUE THREAD

**Issue by TaurusOmar** [2noise/ChatTTS#148]
In the forward method of the DVAE class, if self.vq_layer is None, a full copy of inp that does not share memory with the original is created. This can unnecessarily consume additional  memory.

```python
def forward(self, inp):
    if self.vq_layer is not None:
        vq_feats = self.vq_layer._embed(inp)
    else:
        vq_feats = inp.detach().clone()
    ...
```

Solution
```python
def forward(self, inp):
    if self.vq_layer is not None:
        vq_feats = self.vq_layer._embed(inp)
    else:
        vq_feats = inp
    ...
```

In the modified version, if self.vq_layer is None, we simply assign inp to vq_feats instead of creating a full copy. This should reduce memory consumption.

**Comment by lich99** [comment]
Thank you very much for pointing out the issue. I will correct it soon.
