### ISSUE TITLE
Windows环境能运行吗？requirements里没有nemo_text_processing为什么报错

### ISSUE THREAD

**Issue by 398074715** [2noise/ChatTTS#150]
INFO:ChatTTS.core:All initialized.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 4
      1 texts = ["So we found being competitive and collaborative was a huge way of staying motivated towards our goals, so one person to call when you fall off, one person who gets you back on then one person to actually do the activity with.",]*3 \
      2         + ["我觉得像我们这些写程序的人，他，我觉得多多少少可能会对开源有一种情怀在吧我觉得开源是一个很好的形式。现在其实最先进的技术掌握在一些公司的手里的话，就他们并不会轻易的开放给所有的人用。"]*3     
----> 4 wavs = chat.infer(texts)

File ~\IdeaProjects\ChatTTS\ChatTTS\core.py:145, in Chat.infer(self, text, skip_refine_text, refine_text_only, params_refine_text, params_infer_code, use_decoder, do_text_normalization, lang)
    143     for i, t in enumerate(text):
    144         _lang = detect_language(t) if lang is None else lang
--> 145         self.init_normalizer(_lang)
    146         text[i] = self.normalizer[_lang].normalize(t, verbose=False, punct_post_process=True)
    148 for i in text:

File ~\IdeaProjects\ChatTTS\ChatTTS\core.py:182, in Chat.init_normalizer(self, lang)
    179 def init_normalizer(self, lang):
    181     if lang not in self.normalizer:
--> 182         from nemo_text_processing.text_normalization.normalize import Normalizer
    183         self.normalizer[lang] = Normalizer(input_case='cased', lang=lang)

ModuleNotFoundError: No module named 'nemo_text_processing'

**Comment by XylitolJ** [comment]
then:
pip install nemo_text_processing
