### ISSUE TITLE
webui保存音色，使用固定音色推理

### ISSUE THREAD

**Issue by craii** [2noise/ChatTTS#152]
编写了一个webui,增加了以下功能：
1.  选择音色；
2.  保存音色到本地；
3.  选择固定音色推理；
4.  调整推理参数；
![](https://raw.githubusercontent.com/craii/ChatTTS_WebUI/main/screenshot.png)

[ChatTTS_WebUI](https://github.com/craii/ChatTTS_WebUI)

**Comment by theoldsong** [comment]
感谢大佬无私奉献。

**Comment by theoldsong** [comment]
感谢大佬无私奉献。

**Comment by theoldsong** [comment]
大佬，音色好像保存不了啊，重启服务也成功
