### ISSUE TITLE
RuntimeError: Windows not yet supported for torch.compile

### ISSUE THREAD

**Issue by RelievedCy** [2noise/ChatTTS#158]
![P_20240601094903](https://github.com/2noise/ChatTTS/assets/100887031/e294a800-0f02-4b4c-8220-0c810bf31777)

##环境：
python 3.11
Windows 11

**Comment by anitman** [comment]
#145 参考我的这个临时解决办法，要么在core.py里面将_load里面的compile bool = True改成False，要么换纯linux环境运行。

**Comment by RelievedCy** [comment]
解决了，在运行中根据报错加了一个share=True，可以运行了，谢谢

**Comment by anitman** [comment]
> 解决了，在运行中根据报错加了一个share=True，可以运行了，谢谢
不需要改compile？能具体说说还有哪个地方可以改吗？

**Comment by li775176364** [comment]
> 解决了，在运行中根据报错加了一个share=True，可以运行了，谢谢

在哪里加的？

**Comment by JeffRody** [comment]
+1 同问 在哪里加的？
