### ISSUE TITLE
这个项目已经能试用了吗？ 

### ISSUE THREAD

**Issue by bk111** [2noise/ChatTTS#16]
这个告警是咋回事呢？

dengz@nv2-pc:~/chattts1$ python chattts1.py
INFO:ChatTTS.core:use cuda:0
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:decoder not initialized.
Traceback (most recent call last):
  File "/home/dengz/chattts1/chattts1.py", line 10, in <module>
    wavs = chat.infer(texts, use_decoder=True)
  File "/home/dengz/.local/lib/python3.10/site-packages/ChatTTS/core.py", line 95, in infer
    assert self.check_model(use_decoder=use_decoder)
AssertionError

**Comment by zou8944** [comment]
same as https://github.com/2noise/ChatTTS/issues/32
