### ISSUE TITLE
UnboundLocalError: local variable 'Normalizer' referenced before assignment

### ISSUE THREAD

**Issue by RelievedCy** [2noise/ChatTTS#161]
##报错步骤
运行webui后点击生成默认案例，outtext显示错误：
![image](https://github.com/2noise/ChatTTS/assets/100887031/18e5bb92-0671-4fac-8a3f-01bb480c132f)

##环境：
Ubuntu 22.04.3 LTS
RTX 4090D
Python 3.10.8

**Comment by RelievedCy** [comment]
install WeTextProcessing

**Comment by zrmzack** [comment]
亲测可用
