### ISSUE TITLE
conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing

### ISSUE THREAD

**Issue by xinyunshenyun** [2noise/ChatTTS#162]
运行 conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
报以下错误
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting WeTextProcessing
  Using cached WeTextProcessing-0.1.12-py3-none-any.whl.metadata (5.2 kB)
Collecting pynini==2.1.5 (from WeTextProcessing)
  Using cached pynini-2.1.5.tar.gz (627 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by KFcoffie** [comment]
我咋看下来你这是安装环境的问题呢

**Comment by xinyunshenyun** [comment]
python3.10 -m venv venv
 source venv/bin/activate
 pip install -r requirements.txt

**Comment by anitman** [comment]
> 运行 conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing 报以下错误 Channels:
> 
> * conda-forge
> * defaults
>   Platform: osx-arm64
>   Collecting package metadata (repodata.json): done
>   Solving environment: done
> 
> # All requested packages already installed.
> Collecting WeTextProcessing Using cached WeTextProcessing-0.1.12-py3-none-any.whl.metadata (5.2 kB) Collecting pynini==2.1.5 (from WeTextProcessing) Using cached pynini-2.1.5.tar.gz (627 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [17 lines of output] Traceback (most recent call last): File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in main() File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires self.run_setup() File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup super().run_setup(setup_script=setup_script) File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals()) File "", line 22, in ModuleNotFoundError: No module named 'Cython' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

这个是因为缺少Cython，没有办法编译C导致的。pip install cython或conda install Cython.

**Comment by Oliver-Lief** [comment]
> > 运行 conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing 报以下错误 Channels:
> > 
> > * conda-forge
> > * defaults
> >   Platform: osx-arm64
> >   Collecting package metadata (repodata.json): done
> >   Solving environment: done
> > 
> > # All requested packages already installed.
> > Collecting WeTextProcessing Using cached WeTextProcessing-0.1.12-py3-none-any.whl.metadata (5.2 kB) Collecting pynini==2.1.5 (from WeTextProcessing) Using cached pynini-2.1.5.tar.gz (627 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> > × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [17 lines of output] Traceback (most recent call last): File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in main() File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) File "/Users/sy/learn/python/ChatTTS/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires self.run_setup() File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup super().run_setup(setup_script=setup_script) File "/private/var/folders/72/55z_yr217_722gy2v_kb2db80000gn/T/pip-build-env-likb1m7f/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals()) File "", line 22, in ModuleNotFoundError: No module named 'Cython' [end of output]
> > note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> > × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> 这个是因为缺少Cython，没有办法编译C导致的。pip install cython或conda install Cython.

安了Cython之后还是报缺这个模块

**Comment by Laplace-bit** [comment]
同问

**Comment by Laplace-bit** [comment]
创建环境
conda create -n chattts python=3.x.x
激活环境
conda activate chatts
安装Cython
conda install Cython
解下来再执行你的安装命令即可

**Comment by xinyunshenyun** [comment]
试了一下 这样是可以的

**Comment by pot-code** [comment]
> 创建环境 conda create -n chattts python=3.x.x 激活环境 conda activate chatts 安装Cython conda install Cython 解下来再执行你的安装命令即可

@Laplace-bit 试过了，也不行

**Comment by shaxiaozz** [comment]
I also encountered this problem, my OS is: Ubuntu 24.04.1 LTS
![image](https://github.com/user-attachments/assets/9a9a7eb7-df07-49ab-b136-19e1f813de11)

**Comment by Infinnerty** [comment]
> I also encountered this problem, my OS is: Ubuntu 24.04.1 LTS ![image](https://private-user-images.githubusercontent.com/43721571/381496586-9a9a7eb7-df07-49ab-b136-19e1f813de11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NTUzNzgsIm5iZiI6MTczMDY1NTA3OCwicGF0aCI6Ii80MzcyMTU3MS8zODE0OTY1ODYtOWE5YTdlYjctZGYwNy00OWFiLWIxMzYtMTllMWY4MTNkZTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE3MzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYTQ2YTVlZDhiODc2ODAxMGE2YjJkNDkzYTgzODMzZTllMzMwN2EyYjdkOTNjZjM5ZmNiYjIwMzgzYjBjMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9mGrqFMbpTjZr9goh9OQ4_p6jM_D2Wk3VolMpvKnbhU)

Use python 3.11 😄

**Comment by ztxdcyy** [comment]
问题出在，你是arm架构的机器，pynini只提供了基于x86平台预编译的轮子（https://pypi.org/project/pynini/2.1.5/#files），你可能需要下载源码之后自行编译。

**Comment by love530love** [comment]
我也遇到同样的问题，最后pip install WeTextProcessing --no-deps安装成了，但不知道不装依赖会产生哪些后果[
![微信截图_20241224231538](https://github.com/user-attachments/assets/a9f54350-ecb7-4dc9-b08c-20f4945277f6)
](url)

**Comment by linxichen** [comment]
I had this problem under 3.13. No issues under 3.11.
