### ISSUE TITLE
新版本windows上报错 Normalizer pynini WeTextProcessing  nemo_text_processing  解决方法

### ISSUE THREAD

**Issue by jianchang512** [2noise/ChatTTS#164]
新版使用了 nemo_text_processing  和  pynini 来处理中文，但遗憾的是，pynini压根无法在windows平台安装和使用，要使用，也只能安装在WSL子系统上。

不管给出的什么安装方式， 比如 

```
pip install pynini==2.1.5 Cython   WeTextProcessing

```

都是无法在Windows上正确安装的

![image](https://github.com/2noise/ChatTTS/assets/3378335/e32c50d1-492c-4b72-958b-78af0575e662)

----

解决方法:
打开 ChatTTS/core.py, 大约143行，注释掉接下来的7行，

![image](https://github.com/2noise/ChatTTS/assets/3378335/5bdd3dc8-0c7c-485f-b5dc-613f14917319)

问题解决

#160 #162 #150  #147 #101 #155

**Comment by ISuuuu** [comment]
666  真及时！！！

**Comment by cheniia** [comment]
这个报错我用作者告警信息的提示也解决了
`conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing`
`conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing`

**Comment by bicoll** [comment]
> 新版使用了 nemo_text_processing 和 pynini 来处理中文，但遗憾的是，pynini压根无法在windows平台安装和使用，要使用，也只能安装在WSL子系统上。
> 
> 不管给出的什么安装方式， 比如
> 
> ```
> pip install pynini==2.1.5 Cython   WeTextProcessing
> ```
> 
> 都是无法在Windows上正确安装的
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/335784402-e32c50d1-492c-4b72-958b-78af0575e662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzMwNjAsIm5iZiI6MTcxNzIzMjc2MCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQwMi1lMzJjNTBkMS00OTJjLTRiNzItOTU4Yi03OGFmMDU3NWU2NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDFUMDkwNjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjc1MTA3Mjk2NzRmMWMxZThlOTEwZDEwNThlOTRlZTdlOWYzNzhkNzMzYTQwMTE2NWU2YTAwMjMyZGNhM2ZkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R7TpeGmybOMFZIwg1dzR-5XO1kLAhPRJ4AKmi4k4ukA)
> 
> 解决方法: 打开 ChatTTS/core.py, 大约143行，注释掉接下来的7行，
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/335784496-5bdd3dc8-0c7c-485f-b5dc-613f14917319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzMwNjAsIm5iZiI6MTcxNzIzMjc2MCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQ5Ni01YmRkM2RjOC0wYzdjLTQ4NWYtYjVkYy02MTNmMTQ5MTczMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDFUMDkwNjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YzNmU3YzQ3NmIxMTZhYTNmOGE2NTgxNzlmOGI0MTZiYTVkNTkxOTY2OTA0YzQxMjY2OTMwYmM4MzhhMmU2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xi2YI9M7wAbhZPJtJNzHMF-nC7hCSk0nOKeuG_Wwnjo)
> 
> 问题解决
> 
> #160 #162 #150 #147 #101 #155
感谢感谢，灰常感谢

**Comment by zwb1988** [comment]
> 新版使用了 nemo_text_processing 和 pynini 来处理中文，但遗憾的是，pynini压根无法在windows平台安装和使用，要使用，也只能安装在WSL子系统上。
> 
> 不管给出的什么安装方式， 比如
> 
> ```
> pip install pynini==2.1.5 Cython   WeTextProcessing
> ```
> 
> 都是无法在Windows上正确安装的
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/335784402-e32c50d1-492c-4b72-958b-78af0575e662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzA1OTAsIm5iZiI6MTcxNzMzMDI5MCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQwMi1lMzJjNTBkMS00OTJjLTRiNzItOTU4Yi03OGFmMDU3NWU2NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMTIxMTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVjNDczMDc4NGFmOTlhYWMzNjBmMDhkNWM5YWQ1MWQzMTFjOTllZTcxMWVmZTNlODMyZWI5N2IzY2QyZGY2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LKGpSP6-YIXWREncOFWo2l8N1AmLaaKTnkY4HRlnIXQ)
> 
> 解决方法: 打开 ChatTTS/core.py, 大约143行，注释掉接下来的7行，
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/335784496-5bdd3dc8-0c7c-485f-b5dc-613f14917319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzA1OTAsIm5iZiI6MTcxNzMzMDI5MCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQ5Ni01YmRkM2RjOC0wYzdjLTQ4NWYtYjVkYy02MTNmMTQ5MTczMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMTIxMTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ5NjFmNzg0ZGRkY2FkYTRmMDZkYzQ1NTVkNGY4MDYwMjEwZmJlNDY0ODc4OWQxMmJkOWRiYTMwNWMwMmZjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qQpSDc7oOK3SZGUsSe8tAcVKXG1VwzzPk59nLfTwvU8)
> 
> 问题解决
> 
> #160 #162 #150 #147 #101 #155

注释掉这段代码果然可以~ 我是AI小白，问下 Text Normalization 是做什么的？

**Comment by pengzhendong** [comment]
> Text Normalization 是做什么的？

文本归一化：“今天下有30%概率下雨” => "今天有百分之三十概率下雨"

**Comment by pengzhendong** [comment]
> 新版使用了 nemo_text_processing 和 pynini 来处理中文，但遗憾的是，pynini压根无法在windows平台安装和使用，要使用，也只能安装在WSL子系统上。
> 
> 不管给出的什么安装方式， 比如
> 
> ```
> pip install pynini==2.1.5 Cython   WeTextProcessing
> ```
> 
> 都是无法在Windows上正确安装的
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/335784402-e32c50d1-492c-4b72-958b-78af0575e662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODU4OTgsIm5iZiI6MTcxNzM4NTU5OCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQwMi1lMzJjNTBkMS00OTJjLTRiNzItOTU4Yi03OGFmMDU3NWU2NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDMzMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzJjZTNlMjdjNWE0NjdhYTUzNWQwNjY1ODIyMDdhMzlkODNmM2FkNTgzNzE4ZmZjNTYxYjUyYjEyNDgwMGUzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zr5Zb0xFwB1d73VNm55M4L2YNkla4W5g0PUBC7IGiyg)
> 
> 解决方法: 打开 ChatTTS/core.py, 大约143行，注释掉接下来的7行，
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/335784496-5bdd3dc8-0c7c-485f-b5dc-613f14917319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODU4OTgsIm5iZiI6MTcxNzM4NTU5OCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQ5Ni01YmRkM2RjOC0wYzdjLTQ4NWYtYjVkYy02MTNmMTQ5MTczMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDMzMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzgxMDI2OGVlZGFlZDc2M2ZhNTlkNjM0MzJkM2VkNTQ4YTMwNDJjYzc1ZjIxNDM1ZDUwNTViMWQ0NjM1ZDFjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DKGvyIADGIoKsY45m1f6zWG_2T8rr3jH51HSt_4uXeI)
> 
> 问题解决
> 
> #160 #162 #150 #147 #101 #155

windows 平台的 pynini 可以通过 `conda install` 来安装

**Comment by xiehuiqi220** [comment]
直接设置 do_text_normalization=False

**Comment by zwb1988** [comment]
> 直接设置 do_text_normalization=False

的确，参数配置下false就不会走了

**Comment by zwb1988** [comment]
> > Text Normalization 是做什么的？
> 
> 文本归一化：“今天下有30%概率下雨” => "今天有百分之三十概率下雨"

谢谢~

**Comment by xiehuiqi220** [comment]
但是我觉得这个只是绕过去了，我使用mac m1 芯片和windows 11都遇到这个问题，希望官方能够彻底解决，为啥别人没遇到呢？

**Comment by jianchang512** [comment]
conda 配置环境的话可以安装，其他方式大多会失败。官方只提供了conda方式

**Comment by drome-ma** [comment]
> 但是我觉得这个只是绕过去了，我使用mac m1 芯片和windows 11都遇到这个问题，希望官方能够彻底解决，为啥别人没遇到呢？

macbook m1 max 依旧存在这个问题

**Comment by H2Ning** [comment]
> 新版使用了 nemo_text_processing 和 pynini 来处理中文，但遗憾的是，pynini压根无法在windows平台安装和使用，要使用，也只能安装在WSL子系统上。
> 
> 不管给出的什么安装方式， 比如
> 
> ```
> pip install pynini==2.1.5 Cython   WeTextProcessing
> ```
> 
> 都是无法在Windows上正确安装的
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/335784402-e32c50d1-492c-4b72-958b-78af0575e662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzQwNTQsIm5iZiI6MTcxNzc3Mzc1NCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQwMi1lMzJjNTBkMS00OTJjLTRiNzItOTU4Yi03OGFmMDU3NWU2NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTUyMjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk1MGQ2NGQzMjMwYzEwOTdkMmE5ZGRmNzI1Njk0ZGFhYTJjNGFmNTAzODdlYjIzNzBmYzM5MjYyOWQ2Mzc3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SuQG3Ircr0AqSiUStNynGe2ggNjojvyjB-yMBOsT5vs)
> 
> 解决方法: 打开 ChatTTS/core.py, 大约143行，注释掉接下来的7行，
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/335784496-5bdd3dc8-0c7c-485f-b5dc-613f14917319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzQwNTQsIm5iZiI6MTcxNzc3Mzc1NCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQ5Ni01YmRkM2RjOC0wYzdjLTQ4NWYtYjVkYy02MTNmMTQ5MTczMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTUyMjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNkZGQ3ZWY0YmU3MjIzNDU0ZTdiZDE0NGVjMTY3YWJjMmY3OTNiN2UyNmYzNDk1MDE0NGZmZjAxYWIwZjA5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HECzZClaqTOtBOa9oJQDT82_7CsMIRrQyu2_LmVQl9A)
> 
> 问题解决
> 
> #160 #162 #150 #147 #101 #155

确实只有用这种办法来绕过normalization，有用！但还是希望能够彻底解决。

**Comment by zwb1988** [comment]
> > 新版使用了 nemo_text_processing 和 pynini 来处理中文，但遗憾的是，pynini压根无法在windows平台安装和使用，要使用，也只能安装在WSL子系统上。
> > 不管给出的什么安装方式， 比如
> > ```
> > pip install pynini==2.1.5 Cython   WeTextProcessing
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 都是无法在Windows上正确安装的
> > ![image](https://private-user-images.githubusercontent.com/3378335/335784402-e32c50d1-492c-4b72-958b-78af0575e662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzQwNTQsIm5iZiI6MTcxNzc3Mzc1NCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQwMi1lMzJjNTBkMS00OTJjLTRiNzItOTU4Yi03OGFmMDU3NWU2NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTUyMjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk1MGQ2NGQzMjMwYzEwOTdkMmE5ZGRmNzI1Njk0ZGFhYTJjNGFmNTAzODdlYjIzNzBmYzM5MjYyOWQ2Mzc3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SuQG3Ircr0AqSiUStNynGe2ggNjojvyjB-yMBOsT5vs)
> > 解决方法: 打开 ChatTTS/core.py, 大约143行，注释掉接下来的7行，
> > ![image](https://private-user-images.githubusercontent.com/3378335/335784496-5bdd3dc8-0c7c-485f-b5dc-613f14917319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzQwNTQsIm5iZiI6MTcxNzc3Mzc1NCwicGF0aCI6Ii8zMzc4MzM1LzMzNTc4NDQ5Ni01YmRkM2RjOC0wYzdjLTQ4NWYtYjVkYy02MTNmMTQ5MTczMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTUyMjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNkZGQ3ZWY0YmU3MjIzNDU0ZTdiZDE0NGVjMTY3YWJjMmY3OTNiN2UyNmYzNDk1MDE0NGZmZjAxYWIwZjA5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HECzZClaqTOtBOa9oJQDT82_7CsMIRrQyu2_LmVQl9A)
> > 问题解决
> > #160 #162 #150 #147 #101 #155
> 
> 确实只有用这种办法来绕过normalization，有用！但还是希望能够彻底解决。

其实也不用注释掉代码，调用pynini这段逻辑有个判断。在调用infer方法的时候用命名参数配置false，那段逻辑就跳过了
do_text_normalization=False

**Comment by miryuan** [comment]
> conda 配置环境的话可以安装，其他方式大多会失败。官方只提供了conda方式

conda安装，问题依旧
![微信截图_20240611152204](https://github.com/2noise/ChatTTS/assets/8084785/f6c6dab0-58f3-4b2d-82be-86f9d92251a9)

**Comment by jianchang512** [comment]
> > conda 配置环境的话可以安装，其他方式大多会失败。官方只提供了conda方式
> 
> conda安装，问题依旧 ![微信截图_20240611152204](https://private-user-images.githubusercontent.com/8084785/338478364-f6c6dab0-58f3-4b2d-82be-86f9d92251a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTA5NjgsIm5iZiI6MTcxODA5MDY2OCwicGF0aCI6Ii84MDg0Nzg1LzMzODQ3ODM2NC1mNmM2ZGFiMC01OGYzLTRiMmQtODJiZS04NmY5ZDkyMjUxYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDcyNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRiNzNkNjk4NGEzNjU3ZmFlZTM1NzdhNzYxN2NhZDMyODljZTNhZGZjNjk2ZTIwOWM5ZDgyOGZlZDBiNGNiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XcdalzEiqLygbKojMNdrJReh3XS7wk3jKK7d8kgcvWY)

不能用pip安装，必须 conda install 安装

`conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing`

`conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing`

分别执行上面2条命令

**Comment by stephenwhy** [comment]
> 直接设置 do_text_normalization=False

感谢大佬，真的可以

**Comment by albertyann** [comment]
这个问题有点纠结，显卡不在linux下

**Comment by liunux4odoo** [comment]
> conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing

防止后来人搜到这里，命令需要改成：
`conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing==1.0.2`

**Comment by BlackMale8** [comment]
success! thx！

> > conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
> 
> 防止后来人搜到这里，命令需要改成： `conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing==1.0.2`

**Comment by gougang** [comment]
非常有用，就是WeTextProcessing的版本问题，十分感谢🙏


> > conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
> 
> 防止后来人搜到这里，命令需要改成： `conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing==1.0.2`

**Comment by gougang** [comment]
强烈建议作者在requirements里加上版本，有时候因为一个版本的问题浪费很久的时间，谢谢

**Comment by Meltryllisde** [comment]
> > conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
> 
> 防止后来人搜到这里，命令需要改成： `conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing==1.0.2`

噢，我操，还真好了

**Comment by jinyzhang5** [comment]
conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing==1.0.2
conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing==1.0.2

建议官方更新一下 将nemo_text_processing和WeTextProcessing的版本也固定下来 不然windows下还是会报错

**Comment by tyler-whz** [comment]
> 新版使用了 nemo_text_processing 和 pynini 来处理中文，但遗憾的是，pynini压根无法在windows平台安装和使用，要使用，也只能安装在WSL子系统上。
> 
> 不管给出的什么安装方式， 比如
> 
> ```
> pip install pynini==2.1.5 Cython   WeTextProcessing
> ```
> 
> 都是无法在Windows上正确安装的
> 
> ![image](https://github.com/2noise/ChatTTS/assets/3378335/e32c50d1-492c-4b72-958b-78af0575e662)
> 
> 解决方法: 打开 ChatTTS/core.py, 大约143行，注释掉接下来的7行，
> 
> ![image](https://github.com/2noise/ChatTTS/assets/3378335/5bdd3dc8-0c7c-485f-b5dc-613f14917319)
> 
> 问题解决
> 
> [#160](https://github.com/2noise/ChatTTS/issues/160) [#162](https://github.com/2noise/ChatTTS/issues/162) [#150](https://github.com/2noise/ChatTTS/issues/150) [#147](https://github.com/2noise/ChatTTS/issues/147) [#101](https://github.com/2noise/ChatTTS/issues/101) [#155](https://github.com/2noise/ChatTTS/issues/155)

现在主干代码没找到，🈶️报错怎么办？`    def load(
        self,
        source: Literal["huggingface", "local", "custom"] = "local",
        force_redownload=False,
        compile: bool = False,
        custom_path: Optional[torch.serialization.FILE_LIKE] = None,
        device: Optional[torch.device] = None,
        coef: Optional[torch.Tensor] = None,
        use_flash_attn=False,
        use_vllm=False,
        experimental: bool = False,
    ) -> bool:
        download_path = self.download_models(source, force_redownload, custom_path)
        if download_path is None:
            return False
        return self._load(
            device=device,
            compile=compile,
            coef=coef,
            use_flash_attn=use_flash_attn,
            use_vllm=use_vllm,
            experimental=experimental,`
