### ISSUE TITLE
请问官方中文示例里的音色是seed多少号呢？

### ISSUE THREAD

**Issue by whistle003** [2noise/ChatTTS#165]
https://private-user-images.githubusercontent.com/130631963/334550682-bbfa3b83-2b67-4bb6-9315-64c992b63788.webm?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjYzNjUsIm5iZiI6MTcxNzIyNjA2NSwicGF0aCI6Ii8xMzA2MzE5NjMvMzM0NTUwNjgyLWJiZmEzYjgzLTJiNjctNGJiNi05MzE1LTY0Yzk5MmI2Mzc4OC53ZWJtP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDFUMDcxNDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjViMjllMTY1YWJmYjI3YWI0ZDJlZjA3MmYxMGNlZmJlYzMxNWEwMjc2ZjRjZTYwYTgwMTdlYmZlMGMzYjEwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rFwOizLZ7dPKyMPhp1hv_fRxJ_81B0NpkV-KpfEKH9A

**Comment by SongOnWater** [comment]
像年轻时的郭德纲

**Comment by 6drf21e** [comment]
去抽卡吧 听到过类似的音频

https://github.com/6drf21e/ChatTTS_colab

![image](https://github.com/2noise/ChatTTS/assets/29720712/232e2969-513e-4595-93f3-4834acd693a1)

**Comment by zivenyang** [comment]
推一个 音频种子：123456789，文本种子：987654321

**Comment by orderer0001** [comment]
> 推一个 音频种子：123456789，文本种子：987654321

在代码中固定seed，好像每次输出还是音色不同 
params_infer_code = {'prompt': '[speed_123456789]', 'temperature': .5}  # .3

**Comment by BrightXiaoHan** [comment]
> > 推一个 音频种子：123456789，文本种子：987654321
> 
> 在代码中固定seed，好像每次输出还是音色不同 params_infer_code = {'prompt': '[speed_123456789]', 'temperature': .5} # .3

https://github.com/2noise/ChatTTS/issues/63  参考这个链接，或者参考这个代码：https://github.com/Jackiexiao/ChatTTS-api-ui-docker/blob/main/api.py
