### ISSUE TITLE
QQ群人满了，可以再开一个群吗

### ISSUE THREAD

**Issue by 1289902828** [2noise/ChatTTS#169]
如题

**Comment by lucasjinreal** [comment]
![11717242727_ pic](https://github.com/2noise/ChatTTS/assets/21303438/c47495e7-668d-4063-96c0-f14a5aeed799)

**Comment by hotdogarea** [comment]
满了 求拉一下

**Comment by learningpro** [comment]
再开一个吧，太火爆了

**Comment by mysxs** [comment]
再开一个吧
