### ISSUE TITLE
Win11成功运行最新代码

### ISSUE THREAD

**Issue by cheniia** [2noise/ChatTTS#170]
### 操作系统及运行环境版本
操作系：win11家庭版 23H2
conda：24.1.2
Python：3.11.9
`conda create -n chattts python=3.11`
torch 版本 2.1.2 
cuda版本 cuda_12.1.1  
`cuda各版本下载地址   https://developer.nvidia.com/cuda-toolkit-archive`
nvidia驱动版本 531.14
### 依赖包安装
`pip install -r requirements.txt`
`pip install jupyter`
`conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing`
`conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing`
作者默认使用的是cpu版本的torch，如果使用GPU版torch，安装如下依赖进行替换
`pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121`
### 运行jupyter notebook
`jupyter notebook --notebook-dir=[你的项目路径]`
### 成功运行
![Snipaste_2024-06-01_16-33-48](https://github.com/2noise/ChatTTS/assets/42088174/f3e907c3-e8e7-45dc-a8b1-53eae1ff2a4c)

**Comment by zpengcom** [comment]
我也成功了 分享一下
![image](https://github.com/2noise/ChatTTS/assets/8217132/a7e34c9b-41cf-410e-811e-5961ac5562c2)

**Comment by anitman** [comment]
Windows下还是建议WSL，compile在True的情况下性能至少是windows环境下的两倍以上，还是建议编译后运行。另外，一定要在环境中安装cuda-toolkit，目前在作者的依赖文件中是不包括的，需要自行安装。
conda install -c nvidia cuda-toolkit，否则，编译无法进行，会出现警告甚至报错。
每次运行的第一次编译时间较长，之后会正常。
