### ISSUE TITLE
欢迎体验啊

### ISSUE THREAD

**Issue by guomaoqiu** [2noise/ChatTTS#171]
欢迎体验： https://chattts.sctux.cc

![image](https://github.com/2noise/ChatTTS/assets/9714859/57078e31-c5a1-4b20-a458-a7b0d0ea08db)

**Comment by guomaoqiu** [comment]
文字过长，我这VPS压力大啊（哭.....................

**Comment by moodpo** [comment]
> https://chattts.sctux.cc

50个字，够干啥的

**Comment by guomaoqiu** [comment]
没法啊老哥，我的服务器资源不够😭

moodpo ***@***.***>于2024年6月1日 周六下午8:49写道：
