### ISSUE TITLE
UnboundLocalError: local variable 'Normalizer' referenced before assignment

### ISSUE THREAD

**Issue by wdyyyyyy** [2noise/ChatTTS#173]

**Comment by osahenr** [comment]
More light about this post please!

**Comment by wasimar** [comment]
fixed in https://github.com/2noise/ChatTTS/pull/153 (tested locally and Google Colab)

**Comment by lesonky** [comment]
Normalizer 有些问题，可以在调用 infer 的时候把  do_text_normalization=False 加进去，跳过 normalizer 这一步，等后续修复吧

**Comment by wdyyyyyy** [comment]
我现在可以跑了（系统是win10）

**Comment by wdyyyyyy** [comment]
我报错的原因是库没有装全，之后下载了pynini、WeTextProcessing等库就可以运行了。

**Comment by xiehuiqi220** [comment]
> fixed in #153 (tested locally and Google Colab)

no effect

**Comment by jianchang512** [comment]
windows上只可使用 conda 方式才能正确安装，其他报错，最简单方式就是 chat.infer里传入 do_text_normalization=False

**Comment by wdyyyyyy** [comment]
> windows上只可使用 conda 方式才能正确安装，其他报错，最简单方式就是 chat.infer里传入 do_text_normalization=False

是的，用pip显示安装失败，用conda就可以下载了

**Comment by cucdengjunli** [comment]
mark
