### ISSUE TITLE
ChatTTS的效果实在是太好了，有没有交流群可以交流一下模型架构以及一些trick？

### ISSUE THREAD

**Issue by lucasjinreal** [2noise/ChatTTS#175]
![11717242727_ pic](https://github.com/2noise/ChatTTS/assets/21303438/bef62dcb-7574-458c-b9af-ffc136f74dfb)

感兴趣的同学可以一起来交流～

**Comment by mysxs** [comment]
求拉

**Comment by mysxs** [comment]
> 这是官方群吗 README里不是🈶作者的qq群嘛

QQ群满了

**Comment by lphkxd** [comment]
![image](https://github.com/2noise/ChatTTS/assets/16346895/5f805db4-ec45-4c9d-a3e4-0ba7622da6cd)

**Comment by Chenwe111** [comment]
> ![11717242727_ pic](https://private-user-images.githubusercontent.com/21303438/335799046-bef62dcb-7574-458c-b9af-ffc136f74dfb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODE1NDEsIm5iZiI6MTcxNzM4MTI0MSwicGF0aCI6Ii8yMTMwMzQzOC8zMzU3OTkwNDYtYmVmNjJkY2ItNzU3NC00NThjLWI5YWYtZmZjMTM2Zjc0ZGZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAyMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGI0NjU1NjAyZDgxMDA2ZmYwM2ZjNjE0NGI4NmY5MWQ3ZTk1YTJhNDRmY2ZiYWJhYzY5MDk3MDAzNTI0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5cMcdpURhwEl6c7ZHrqDgcgQR-vS-CeTWJIgnrhFvSU)
> 
> 感兴趣的同学可以一起来交流～

满了，求拉

**Comment by kkxg** [comment]
> ![11717242727_ pic](https://private-user-images.githubusercontent.com/21303438/335799046-bef62dcb-7574-458c-b9af-ffc136f74dfb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODQ2MTMsIm5iZiI6MTcxNzM4NDMxMywicGF0aCI6Ii8yMTMwMzQzOC8zMzU3OTkwNDYtYmVmNjJkY2ItNzU3NC00NThjLWI5YWYtZmZjMTM2Zjc0ZGZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAzMTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4Y2U3ZGM5NGFmNDYxMjY2M2E1YjFmYjhkOGQxZDY1YmU5ZGNkNzlmOGI4YzhkOGUyMDRkNGI0NjZiZmRkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UNyXCR3sun2DrQExAKbhzFwT_n-oO85Go9bnl_af2wg)
> 
> 感兴趣的同学可以一起来交流～

人太多了。需要成员邀请才能进去。。

**Comment by kingmpw2015** [comment]
> ![image](https://private-user-images.githubusercontent.com/16346895/335857241-5f805db4-ec45-4c9d-a3e4-0ba7622da6cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODgzNDAsIm5iZiI6MTcxNzQ4ODA0MCwicGF0aCI6Ii8xNjM0Njg5NS8zMzU4NTcyNDEtNWY4MDVkYjQtZWM0NS00YzlkLWEzZTQtMGJhNzYyMmRhNmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4MDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OGFjZGJlMjJmZGNjMjA0ODFkMGU3Mjg0Y2NhYTI5YWMwMGRmOWEwMTBjODcwNmNjMTA3NDVjZjgzMDNkYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.40J4rnPM8R8ndfCNYHXMm2N29WsCnw-7wcwZGZzsPBs)

求拉：微信号： kingmpw

**Comment by FloatFrank** [comment]
fxrankz，求拉

**Comment by brainbpe** [comment]
kickunk， 谢谢
