### ISSUE TITLE
3090测试例子需要运行六个小时...

### ISSUE THREAD

**Issue by LixiangHello** [2noise/ChatTTS#177]
![t](https://github.com/2noise/ChatTTS/assets/32087152/c62c7937-fff7-4c97-a74c-f918d779111e)

这代码更新的不能运行了都...

**Comment by jiedo** [comment]
可能需要把compile参数设置False, 我测试预编译模型4090运行时间增加10倍.

**Comment by jiedo** [comment]
应该是新模型占用了更多的显存, 显存不足导致运行时间过长.

**Comment by warkcod** [comment]
哪个地方bug了吧，要不这种情况压根不可用啊

**Comment by lphkxd** [comment]
等一会自动就完成了
