### ISSUE TITLE
只能用GPU吗？CPU不能跑是吗？

### ISSUE THREAD

**Issue by guoqingcun** [2noise/ChatTTS#18]
只能用GPU吗？CPU不能跑是吗？

**Comment by iwanglei1** [comment]
模型下载中~

**Comment by wa008** [comment]
> > 模型下载中~
> 
> 未下载完，直接退出了

最终的进度条是在推理，是正常结束了。
可以用以下代码保存音频文件，再单独打开音频文件听内容。
```
import scipy
scipy.io.wavfile.write(filename = "./chattts_download_0.wav", rate = 24_000, data = wavs[0].T)
```

**Comment by guoqingcun** [comment]
@wa008 你说的没错，成功。怎么换语音模式，切换男女的声音之类的呢

**Comment by Bill-XU** [comment]
> ![image](https://private-user-images.githubusercontent.com/2375348/334378391-4123b125-fc1d-409a-9af7-a4fb2321416f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTUyNzAsIm5iZiI6MTcxNzY1NDk3MCwicGF0aCI6Ii8yMzc1MzQ4LzMzNDM3ODM5MS00MTIzYjEyNS1mYzFkLTQwOWEtOWFmNy1hNGZiMjMyMTQxNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDYyMjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI5MzQyMzFjOGViM2Y5ZjVmNGExMWU2YTMyYzFkZGMxMGUyNWUxOTJlNDczNzc0M2JkZTZiODg5ZTEyZjcxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eN4JFah-1Dz-ptffv6GjZdlMR7bYLDTbOXaWBcIRlH8)这是什么原因

我这边运行示例代码报下面的错。。。为啥没有下载模型的过程？
能不能分享一下你的代码？谢谢！
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
Traceback (most recent call last):
  File "C:\Workstations\python\chattts\chattts.py", line 22, in <module>
    wavs = chat.infer(texts)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\.conda\envs\chattts\Lib\site-packages\ChatTTS\core.py", line 95, in infer
    assert self.check_model(use_decoder=use_decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
