### ISSUE TITLE
RuntimeError: Couldn't find appropriate backend to handle uri output1.wav and format wav.

### ISSUE THREAD

**Issue by PSSUN** [2noise/ChatTTS#181]
OS: 
windows 11

Error message:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[17], line 1
----> 1 torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000, format='wav')

File F:\conda\Lib\site-packages\torchaudio\_backend\utils.py:311, in get_save_func.<locals>.save(uri, src, sample_rate, channels_first, format, encoding, bits_per_sample, buffer_size, backend, compression)
    223 def save(
    224     uri: Union[BinaryIO, str, os.PathLike],
    225     src: torch.Tensor,
   (...)
    233     compression: Optional[Union[CodecConfig, float, int]] = None,
    234 ):
    235     """Save audio data to file.
    236 
    237     Note:
   (...)
    309 
    310     """
--> 311     backend = dispatcher(uri, format, backend)
    312     return backend.save(
    313         uri, src, sample_rate, channels_first, format, encoding, bits_per_sample, buffer_size, compression
    314     )

File F:\conda\Lib\site-packages\torchaudio\_backend\utils.py:221, in get_save_func.<locals>.dispatcher(uri, format, backend_name)
    219     if backend.can_encode(uri, format):
    220         return backend
--> 221 raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")

RuntimeError: Couldn't find appropriate backend to handle uri output1.wav and format wav.
```

I have installed  **soundfile** and **pysoundfile**, but still error.

**Comment by jianchang512** [comment]
download ffmpeg and add Path

**Comment by Flame1117** [comment]
OS: windows 11

### **test.py**
import torch

import ChatTTS
from IPython.display import Audio

chat = ChatTTS.Chat()
chat.load_models(source='local', local_path='D:\zhanxy\ChatTTS\ChatTTS\model2\chatTTS')
# chat.load_models(compile=False)

texts = ["由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。",]

wavs = chat.infer(texts, use_decoder=True)

# Couldn't find appropriate backend to handle uri output1.wav and format None.
torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)


### **log**
INFO:ChatTTS.core:Load from local: D:\zhanxy\ChatTTS\ChatTTS\model2\chatTTS
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
INFO:ChatTTS.core:All initialized.
 10%|█         | 40/384 [00:02<00:23, 14.42it/s]
 15%|█▌        | 316/2048 [00:15<01:22, 20.88it/s]
Traceback (most recent call last):
  File "D:\zhanxy\ChatTTS\ChatTTS\test.py", line 15, in <module>
    torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)
NameError: name 'torchaudio' is not defined

Process finished with exit code 1

**Comment by jianchang512** [comment]
重新 git  pull

test.py 有点错误，改用 soundfile

**Comment by Flame1117** [comment]
name 'soundfile' is not defined  应该引入什么库
pycharm 提示我这样引入  from torchaudio._backend import soundfile
但是 我这样引入之后，报了一个这样的错
AttributeError: module 'torchaudio._backend.soundfile' has no attribute 'write'

**Comment by jianchang512** [comment]
2楼不是说了吗，不要使用 torchaudio ，删掉相关代码，使用 soundfile

pip install soundfile

**Comment by szhdanxiaoxi** [comment]
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
INFO:ChatTTS.core:All initialized.
  3%|▎         | 12/384 [00:00<00:21, 17.11it/s]
  4%|▍         | 83/2048 [00:03<01:15, 25.93it/s]
Traceback (most recent call last):
  File "E:\causal\ml\venv\ChatTTS-main\chattts.py", line 17, in <module>
    soundfile.write("E:/causal/ml/venv/ChatTTS-main/output/output1.wav", wavs[0], 24000)
  File "E:\causal\ml\venv\Lib\site-packages\soundfile.py", line 343, in write
    with SoundFile(file, 'w', samplerate, channels,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\causal\ml\venv\Lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\causal\ml\venv\Lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'E:/causal/ml/venv/ChatTTS-main/output/output1.wav': Format not recognised.

换成soundfile会报这个错

**Comment by libukai** [comment]
同样的报错

**Comment by libukai** [comment]
> soundfile.write("output1.wav", wavs[0], 24000)

代码需要修正

```python
soundfile.write("output1.wav", wavs[0][0], 24000)
```

**Comment by Yinshuofeng** [comment]
感谢楼上 可以了!

**Comment by chenmonster** [comment]
> 2楼不是说了吗，不要使用 torchaudio ，删掉相关代码，使用 soundfile
> 
> pip install soundfile

我用你说的第一种方法运行没问题，就是需要安装 `ffmpeg`  软件
```shell
apt update
apt install ffmpeg -y
ffmpeg -version
```

**Comment by njhouse365** [comment]
还是soundflie可靠
