### ISSUE TITLE
按#164处理完 pynini后，新的信息来了，windows 还是算了

### ISSUE THREAD

**Issue by itliuxing** [2noise/ChatTTS#184]
.......................
.......................
raise RuntimeError(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Cannot find a working triton installation. More information on installing Triton can be found at https://github.com/openai/triton

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

**Comment by dabiao2008** [comment]
chattts ui在windows 10下可以流畅运行
https://github.com/jianchang512/chatTTS-ui

**Comment by aisaveflower** [comment]
import torch之后加入这个尝试  torch.compile = lambda *args, **kwargs: args[0]

**Comment by ilexcn** [comment]
安装 windows 编译的Triton ，google 搜索 triton-2.0.0-cp310-cp310-win_amd64.whl

**Comment by ThankVinci** [comment]
> import torch之后加入这个尝试 torch.compile = lambda *args, **kwargs: args[0]

赞一个，这个可以

**Comment by delcompan** [comment]
> import torch之后加入这个尝试 torch.compile = lambda *args, **kwargs: args[0]

感谢，这个有用，但这一句到底什么作用，不懂
