### ISSUE TITLE
没有Mac版本的吗？

### ISSUE THREAD

**Issue by greensensen** [2noise/ChatTTS#186]

**Comment by qhgary** [comment]
人家用的python，mac下面也不困难啊，我就在mac下面用的

**Comment by jagguo** [comment]
看来楼主是需要一套Mac 的方案：
进入一个目录，cd 拖拽这个目录到终端 return。
1、git clone https://github.com/2noise/ChatTTS
2、pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
3、pip install -i https://pypi.tuna.tsinghua.edu.cn/simple gradio
4、注释掉143-149行，以及183-199行（影响中文+数字+英文的朗读顺畅度，自己在input时，都改成汉字）
5、根目录运行 python webui.py
