### ISSUE TITLE
RuntimeError: FFT_INVALID_DESCRIPTOR with Intel Arc GPU

### ISSUE THREAD

**Issue by 771991673** [2noise/ChatTTS#187]
Encounter this issue while infering with Intel Arc 770.

pip install torch==2.1.0.post2 torchvision==0.16.0.post2 torchaudio==2.1.0.post2 intel-extension-for-pytorch==2.1.30+xpu oneccl_bind_pt==2.1.300+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

File ~/ChatTTS/venv/lib/python3.10/site-packages/vocos/spectral_ops.py:46, in ISTFT.forward(self, spec)
     34 """
     35 Compute the Inverse Short Time Fourier Transform (ISTFT) of a complex spectrogram.
     36 
   (...)
     42     Tensor: Reconstructed time-domain signal of shape (B, L), where L is the length of the output signal.
     43 """
     44 if self.padding == "center":
     45     # Fallback to pytorch native implementation
---> 46     return torch.istft(spec, self.n_fft, self.hop_length, self.win_length, self.window, center=True)
     47 elif self.padding == "same":
     48     pad = (self.win_length - self.hop_length) // 2

RuntimeError: FFT_INVALID_DESCRIPTOR

**Comment by klmmlk** [comment]
intel没戏的，我也是intel的，只有看别人玩得开心，别怕，intel战未来
![0078E075](https://github.com/2noise/ChatTTS/assets/12571901/a54e8f09-1fe4-4b2c-95d6-59a925088050)

**Comment by 771991673** [comment]
> intel没戏的，我也是intel的，只有看别人玩得开心，别怕，intel战未来 ![0078E075](https://private-user-images.githubusercontent.com/12571901/336814613-a54e8f09-1fe4-4b2c-95d6-59a925088050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODc1MTMsIm5iZiI6MTcxNzU4NzIxMywicGF0aCI6Ii8xMjU3MTkwMS8zMzY4MTQ2MTMtYTU0ZThmMDktMWZlNC00YjJjLTk1ZDYtNTlhOTI1MDg4MDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDExMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDIxOTlmYTYyZjhmOTIwNzZmNDQwYWY1ZmVlYTQ4NzAzMzljYzVjYjUzYTAxMmY5NTg1NjQ2N2ZmNWMzODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJPtikyvooJr53HX6wNYsB-lW24zt8rXDfUpoB5qg_U)

我把bug提交給了ipex，希望能夠解決。最近ipex好用了好多。https://github.com/intel/intel-extension-for-pytorch/issues/644

**Comment by klmmlk** [comment]
> > intel没戏的，我也是intel的，只有看别人玩得开心，别怕，intel战未来 ![0078E075](https://private-user-images.githubusercontent.com/12571901/336814613-a54e8f09-1fe4-4b2c-95d6-59a925088050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODc1MTMsIm5iZiI6MTcxNzU4NzIxMywicGF0aCI6Ii8xMjU3MTkwMS8zMzY4MTQ2MTMtYTU0ZThmMDktMWZlNC00YjJjLTk1ZDYtNTlhOTI1MDg4MDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDExMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDIxOTlmYTYyZjhmOTIwNzZmNDQwYWY1ZmVlYTQ4NzAzMzljYzVjYjUzYTAxMmY5NTg1NjQ2N2ZmNWMzODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJPtikyvooJr53HX6wNYsB-lW24zt8rXDfUpoB5qg_U)
> 
> 我把bug提交給了ipex，希望能夠解決。最近ipex好用了好多。[intel/intel-extension-for-pytorch#644](https://github.com/intel/intel-extension-for-pytorch/issues/644)

可以自己先试下intel的pytouch扩展，[Welcome to Intel® Extension for PyTorch* Documentation](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.20%2bxpu&os=linux%2fwsl2&package=pip)看看能不能解决。
反正我的需求不是很高，用cpu也是一样的。况且挂甲骨文的，也没有显卡可用。
