### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by Wcowin** [2noise/ChatTTS#188]
<img width="1365" alt="image" src="https://github.com/2noise/ChatTTS/assets/99159173/1719edaf-dbb5-4709-8014-280b87596f8d">
<img width="1309" alt="image" src="https://github.com/2noise/ChatTTS/assets/99159173/9c1350c9-32ae-4ec7-95a5-d20a4c7c09b7">
成功跑在本地了，但是点击generate显示错误

**Comment by Wcowin** [comment]
ChatTTS-main /usr/local/bin/python3 /Users/wangkewen/Downloads/ChatTTS-main/ChatTTS/1.py
INFO:ChatTTS.core:Load from cache: /Users/wangkewen/.cache/huggingface/hub/models--2Noise--ChatTTS/snapshots/ce5913842aebd78e4a01a02d47244b8d62ac4ee3
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
INFO:ChatTTS.core:All initialized.
WARNING:ChatTTS.core:Package WeTextProcessing not found!                         Run: conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
Traceback (most recent call last):
  File "/Users/wangkewen/Downloads/ChatTTS-main/ChatTTS/1.py", line 13, in <module>
    wavs = chat.infer(texts, use_decoder=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangkewen/Downloads/ChatTTS-main/ChatTTS/ChatTTS/core.py", line 146, in infer
    self.init_normalizer(_lang)
  File "/Users/wangkewen/Downloads/ChatTTS-main/ChatTTS/ChatTTS/core.py", line 192, in init_normalizer
    self.normalizer[lang] = Normalizer().normalize
                            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'Normalizer' where it is not associated with a value

**Comment by jianchang512** [comment]
#164 #168  MacOS下也可以照此解决

**Comment by Wcowin** [comment]
> #164 #168 MacOS下也可以照此解决

谢谢，我在研究您的项目**CHATTTS-UI**

**Comment by Wcowin** [comment]
> #164 #168 MacOS下也可以照此解决

<img width="1309" alt="image" src="https://github.com/2noise/ChatTTS/assets/99159173/588a1530-0c19-477e-b423-6aa57d91cc3c">

大佬想请问下这是什么错误呢，我执行了`python3 app.py`后显示 
`2024-06-02 10:41:08,296 - modelscope - WARNING - Downloading: GPT.pt failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/pzc163/chatTTS/repo?Revision=master&FilePath=asset%2FGPT.pt (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) will retry`

**Comment by jianchang512** [comment]
modelscope.cn 只允许国内ip下载，关闭代理就行了

**Comment by Wcowin** [comment]
> modelscope.cn 只允许国内ip下载，关闭代理就行了

<img width="1355" alt="image" src="https://github.com/2noise/ChatTTS/assets/99159173/961d4269-478f-4542-acb7-0259de1dd7d7">  

谢谢老哥，you do such a wonderful job！😺
