### ISSUE TITLE
如何使用自己的声音呢？

### ISSUE THREAD

**Issue by alamise** [2noise/ChatTTS#190]
如何使用自己的音色来实现TTS呢？这个库是否提供根据录音采样来做训练的功能？

另外，非常感谢作者

**Comment by wulinshen** [comment]
同问，希望能训练自己的声音

**Comment by c4pt4in** [comment]
一个个想啥呢？这是项目UI，不是model本身，你需要自己训练自己的model或者自己微调model。别问那么傻的问题

**Comment by fumiama** [comment]
solved.

**Comment by zxmlong** [comment]
你好！邮件已收到！
