### ISSUE TITLE
ImportError: cannot import name 'CommitOperationAdd' from 'huggingface_hub' 

### ISSUE THREAD

**Issue by shadow123moon** [2noise/ChatTTS#191]
执行webui文件和后，一直报错，该如何解决

**Comment by stoneHah** [comment]
我也遇到了

---
Name: gradio
Version: 4.33.0
---
Name: gradio_client
Version: 0.17.0
---
Name: huggingface_hub
Version: 0.23.2

**Comment by SchrodingerFish** [comment]
ImportError: cannot import name 'CommitOperationAdd' from 'huggingface_hub'
