### ISSUE TITLE
为什么我的模型推理会把uv_break  等关键词读出来，Why does my model reasoning read out keywords such as uv_break? 

### ISSUE THREAD

**Issue by orderer0001** [2noise/ChatTTS#195]
为什么我的模型推理会把uv_break  等关键词读出来。用二阶段检查了生成的文本，格式也没有问题阿
Why does my model reasoning read out keywords such as uv_break? I checked the generated text in the second stage and there is no problem with the format.

**Comment by orderer0001** [comment]
I found that only English can control emotional tokens very well, but when I switch to Chinese, I often cannot express them correctly.

**Comment by 1771801582** [comment]
我这边也遇到了同样的问题，看起来都是今天发生的问题，昨天我清晰记得并没有这样的问题
same issue is observed on my side, seems it happens from today.

**Comment by ilexcn** [comment]
因为二阶段检查， 如果含有特殊符号 把 [ ]  去掉了，所以  [uv_break]  变成了 uv_break ，

**Comment by 1771801582** [comment]
> 因为二阶段检查， 如果含有特殊符号 把 [ ] 去掉了，所以 [uv_break] 变成了 uv_break ，

怎么破   有没有什么方法呢

**Comment by ilexcn** [comment]
![image](https://github.com/2noise/ChatTTS/assets/8230745/361b538b-4632-42bb-84d9-7d76f45f5071)
注释掉这两行试试。

**Comment by 6drf21e** [comment]
pull下最新的 后面修正了

**Comment by ZaymeShaw** [comment]
我发现输入包含特殊符号（比如问号？）的时候，整个句子生出的的refine text就会出问题，然后就会把uv_break这种特殊token直接读出来

**Comment by pinkiecircle** [comment]
把core.py的这个函数改掉，不让他替换[]_
def process_text(text):
    # process invaild number
    punctuation_pattern = r"[^\w\s,，\[\]]"
    replaced_text = re.sub(punctuation_pattern, ",", text)
    print(replaced_text)
    replaced_text = re.sub(r".!;:+", ",", replaced_text)
    replaced_text = re.sub(r"\s+", " ", replaced_text)
    replaced_text = re.sub(r",+", ",", replaced_text)
    replaced_text = replaced_text.strip()
    # process number to Chinese number
    replaced_text = process_num_text(replaced_text)
    return replaced_text
