### ISSUE TITLE
长文本请教

### ISSUE THREAD

**Issue by Oliver-Lief** [2noise/ChatTTS#197]
以前没接触过这种项目，想请教一下，刚开始放了网上随便找了点文本，发现文本处理后随机出现字符

猜想是文本太长了或者有特殊字符，然后做了一下字符处理和分段处理，想问一下这样分段处理速度如何评判，个人感觉很慢

用例为550字符长度，处理总时间为11min左右
<img width="1647" alt="Snipaste_2024-06-02_20-50-38" src="https://github.com/2noise/ChatTTS/assets/50728459/9bd7d046-27ca-452a-a0a7-5e4308167826">

**Comment by 6drf21e** [comment]
可能是CPU推理较慢的原因
同一段我这边50秒

调整口语化参数到0可以减少增加的口癖

[long-[seed_2][speed_3][oral_1][laugh_0][break_4][2024-06-02_225055].zip](https://github.com/user-attachments/files/15525711/long-.seed_2.speed_3.oral_1.laugh_0.break_4.2024-06-02_225055.zip)

**Comment by Oliver-Lief** [comment]
> 可能是CPU推理较慢的原因 同一段我这边50秒
> 
> 调整口语化参数到0可以减少增加的口癖
> 
> [long-[seed_2][speed_3][oral_1][laugh_0][break_4][2024-06-02_225055].zip](https://github.com/user-attachments/files/15525711/long-.seed_2.speed_3.oral_1.laugh_0.break_4.2024-06-02_225055.zip)

想请教怎样开启GPU推理，每次启动都是No GPU found
