### ISSUE TITLE
大佬啥时候推出个可执行程序啊

### ISSUE THREAD

**Issue by LonePheasantWarrior** [2noise/ChatTTS#2]
Android TTS,或者是Mac和Win的桌面软件之类的
美滋滋啊

**Comment by anymouschina** [comment]
要消耗 gpt token 的，不大可能免费出可执行程序，自建模型也有算力成本

**Comment by chenziwenhaoshuai** [comment]
@Newsteinwell pip install omegaconf==2.1.2

**Comment by hkgood** [comment]
> @Newsteinwell pip install omegaconf==2.1.2

<img width="852" alt="截屏2024-05-29 09 42 42" src="https://github.com/2noise/ChatTTS/assets/72559939/c5a95400-4df7-4d61-a479-6be306d5a586">

同样的问题，安装完成之后，还是继续提示

**Comment by yuhaolove** [comment]
对于还没有安装成功或使用成功的用户，这个WebUI可以大大帮助您。请大家尝试一下，并告诉我您的反馈。您的意见对改进这个工具、让它变得更加用户友好非常重要。

[ChatTTS-WebUI](https://github.com/yuhaolove/ChatTTS-WebUI)
