### ISSUE TITLE
where should i place pretrain models？

### ISSUE THREAD

**Issue by pzc163** [2noise/ChatTTS#20]
Hi，I have download all the models manually from Hugging face. I have placed models under ChatTTS/ChatTTS/model path.but it still show :WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
so where should i placed the pretrain models？
<img width="757" alt="image" src="https://github.com/2noise/ChatTTS/assets/105222039/788e73c2-6253-4cb1-a042-5a5b2d308cb6">

**Comment by ZsTs119** [comment]
![Snipaste_2024-05-30_11-10-07](https://github.com/2noise/ChatTTS/assets/75237264/16f310d2-ec9e-4be8-8a31-5742ddd2e839)
Find in HuggingFaceDownloadPath directory the models--2Noise--ChatTTS
