### ISSUE TITLE
嫌安装麻烦的可以试试这个 colab 直接运行  win10+也有离线安装包，支持音色抽卡、长音频生成和分角色朗读。

### ISSUE THREAD

**Issue by 6drf21e** [2noise/ChatTTS#200]
嫌安装麻烦的可以试试这个 colab 直接运行  win10+也有离线安装包，支持音色抽卡、长音频生成和分角色朗读。

https://github.com/6drf21e/ChatTTS_colab

![image](https://github.com/2noise/ChatTTS/assets/29720712/be35d676-8ce5-4771-80e3-bb90d4d813ca)

**Comment by 6drf21e** [comment]
更新到提交 [f4c8329](https://github.com/2noise/ChatTTS/commit/f4c8329f0d231b272b676e5e171fb9655b345f2e)

**Comment by midpoint** [comment]
这个真不错！
