### ISSUE TITLE
[laugh]和[uv_break]被识别为invalid，并且不能转成语音

### ISSUE THREAD

**Issue by hch001** [2noise/ChatTTS#201]
文本是这样的：
`python
inputs_cn = """
chat T T S 是一款强大的对话式文本转语音模型。它有中英混读和多说话人的能力。
chat T T S 不仅能够生成自然流畅的语音，还能控制[laugh]笑声啊[laugh]，
停顿啊[uv_break]语气词啊等副语言现象[uv_break]。这个韵律超越了许多开源模型[uv_break]。
请注意，chat T T S 的使用应遵守法律和伦理准则，避免滥用的安全风险。[uv_break]'
""".replace('\n', '')
`
<img width="647" alt="image" src="https://github.com/2noise/ChatTTS/assets/42072191/375b4bde-d842-4eee-9da1-36bc07f79584">

报错如下：
<img width="593" alt="image" src="https://github.com/2noise/ChatTTS/assets/42072191/da56f16b-1a7b-425e-945e-a9a1c25af5f6">

注释了 utils/infer_utils.py 中下面第93和94代码，仍然无效。
<img width="762" alt="image" src="https://github.com/2noise/ChatTTS/assets/42072191/06c45233-8934-427c-9f62-f156e40ed350">

**Comment by jianchang512** [comment]
注释的不正确，这里不需要注释，是 123行的 halfwidth_2_fullwidth_map 变量中的

**Comment by metaimagine** [comment]
我的[laugh]也无法识别，[uv_break]也是

**Comment by Lowpower** [comment]
我的[laugh] [uv_break] 都无法识别

**Comment by yanmingcao** [comment]
Same here. 我的环境是MacBook Pro MacOS 14.5, Apple M2 chip, 16GB memory.

```
input = """
chat T T S 是一款强大的对话式文本转语音模型。它有中英混读和多说话人的能力。
chat T T S 不仅能够生成自然流畅的语音，还能控制[laugh]笑声啊[laugh]，
停顿啊[uv_break]语气词啊等副语言现象[uv_break]。这个韵律超越了许多开源模型[uv_break]。
请注意，chat T T S 的使用应遵守法律和伦理准则，避免滥用的安全风险。[uv_break]'
""".replace('\n', '')

params_refine_text = {
  'prompt': '[oral_2][laugh_0][break_4]'
} 
wavs = chat.infer(input, use_decoder=True, params_refine_text=params_refine_text)
torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)

```

`WARNING:ChatTTS.core:Invalid characters found! : {'‘'}`
