### ISSUE TITLE
搞了一晚上，发现的问题和解决方法汇总一下

### ISSUE THREAD

**Issue by jokerfree** [2noise/ChatTTS#204]
README文件更新一下！！！
代码更新一下！！！
issues里面的问题有的说改了但是我pull最新的代码发现并没有同步，就比如torchaudio库换soundfile，infer_file中[]的问题，do_text_normalization=False说明一下
还有就是评论有的人让下载conda，之前你不用这个管理python环境的完全不需要！！！
中文没问题，正常读了！！！！
给我整乱了都，直接啪嚓，之前好好的python环境直接被这个替换了，果断卸载

**Comment by shinedlc** [comment]
能不能详细点呢。。我连运行文档都没找到

**Comment by tongxin3267** [comment]
感觉这个项目的人就是挖坑能手的。

> 能不能详细点呢。。我连运行文档都没找到

**Comment by jokerfree** [comment]
git clone https://github.com/2noise/ChatTTS
pip install torch ChatTTS
pip install -r requirements.txt
自己新建一个test.py参照remadME
修改部分代码，我的如下
`import ChatTTS
import soundfile
from IPython.display import Audio

chat = ChatTTS.Chat()
chat.load_models(compile=False) # 设置为True以获得更快速度

inputs_cn   = """chat T T S 是一款强大的对话式文本转语音模型。它有中英混读和多说话人的能力。
chat T T S 不仅能够生成自然流畅的语音，还能控制[laugh]笑声啊[laugh]，
停顿啊[uv_break]语气词啊等副语言现象[uv_break]。这个韵律超越了许多开源模型[uv_break]。
请注意，chat T T S 的使用应遵守法律和伦理准则，避免滥用的安全风险。[uv_break]'
""".replace('\n', '')

params_refine_text = {
  'prompt': '[oral_2][laugh_0][break_4]'
} 
audio_array_cn = chat.infer(inputs_cn, params_refine_text=params_refine_text, do_text_normalization=False)

soundfile.write("output1.wav", audio_array_cn[0][0], 24000)
`
需要修改的文件
![2024-06-03_135158](https://github.com/2noise/ChatTTS/assets/12743694/f10b6fad-72ed-4333-8d61-e58521a29520)
