### ISSUE TITLE
时长最长30秒是吗

### ISSUE THREAD

**Issue by jacbo0112** [2noise/ChatTTS#205]
时长最长30秒是吗

**Comment by 1771801582** [comment]
默认的webui.py 好像就是， 我输入长文本连读吞音都不高于30s

**Comment by jacbo0112** [comment]
好像很多tts的大模型都是30s限制，这个是为什么

**Comment by fastfading** [comment]
一句话30s够了

**Comment by tpjaord1983** [comment]
> 一句话30s够了

但是对于做个旁白 5000字的脚本 来说就有点短了

**Comment by woshilaowanga** [comment]
太短了

**Comment by libukai** [comment]
> > 一句话30s够了
> 
> 但是对于做个旁白 5000字的脚本 来说就有点短了

自己修改源代码，循环生成然后合成，或者试试我 Fork 的版本，增加了分段功能，可以处理长文本 [ChatTTS-Control](https://github.com/libukai/ChatTTS-Control)
