### ISSUE TITLE
please support cuda 12  or provide solution

### ISSUE THREAD

**Issue by fastfading** [2noise/ChatTTS#207]
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

But I have a newer version

local fd libcudart
cuda-12.4/targets/x86_64-linux/lib/libcudart.so
cuda-12.4/targets/x86_64-linux/lib/libcudart.so.12

**Comment by 1771801582** [comment]
not sure torch 2.1.2 whether supports cuda-12.4 or not, surely cuda-12.1 works fine.

**Comment by fastfading** [comment]
solved by  reinstall torch
pip uninstall torchaudio
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

 pip install -r requirements.txt
other dependencies
pip install gradio
pip install vocos
pip install omegaconf
pip install cpython
pip install WeTextProcessing

**Comment by anyvoiceai** [comment]
A problem caused by torch?
