### ISSUE TITLE
有些常用字比如“梓”怎么都会识别不了

### ISSUE THREAD

**Issue by qhgary** [2noise/ChatTTS#210]
这个又不是生僻字，怎么被系统识别的时候转成了几个随机的英文字母了呢？前后的汉字都没问题

**Comment by hhk0571** [comment]
不光是汉字, 有些标点符号比如 问号, 分号等都被识别为 uv_break, 而且是没有加中括号, 直接被读出来了 :-(
有大佬知道怎么解决吗?

**Comment by qhgary** [comment]
标点符号转译成停顿不是正常的嘛？ 说话不就是要在标点处停顿嘛

**Comment by hhk0571** [comment]
老大, 我上面写的问题是模型把标点符号翻译为 `uv_break`, 而不是 `[uv_break]`
停顿的token 是 `[uv_break]`, 如果没有加中括号, 它就不是特殊token了, 会被读出来.
