### ISSUE TITLE
推理太慢问题

### ISSUE THREAD

**Issue by DragonWang-cell** [2noise/ChatTTS#211]
如图情况是正常的么，第一步一直warning好久了才开始慢慢进行推理，出现这些warning是正常的么：
![image](https://github.com/2noise/ChatTTS/assets/56779824/a3924544-709b-4ee6-b10f-6735ac65b146)
然后我现在使用的cuda是11.8，发现第一步和第二步仍然没有gpu参与：
![image](https://github.com/2noise/ChatTTS/assets/56779824/a17e3434-c1ad-495b-a1c3-313bf23bd6eb)
![image](https://github.com/2noise/ChatTTS/assets/56779824/c1e2c8f0-06e0-4863-bfd0-a2379396fd3e)
我看给的实例是it/s，我的怎么s/it，也太慢了吧

**Comment by DragonWang-cell** [comment]
![1717385313467](https://github.com/2noise/ChatTTS/assets/56779824/5ee17eff-42cf-4f68-948b-b923fb0dfc8a)
明明CUDA版本和torch是对应的，compile设置的也是false了，还是找不到gpu，这是怎么回事

**Comment by hhk0571** [comment]
可能是cuda 库找的不对.
如果你用的是Ubuntu 系统, 可以参考: https://github.com/2noise/ChatTTS/issues/213

**Comment by DragonWang-cell** [comment]
> 可能是cuda 库找的不对. 如果你用的是Ubuntu 系统, 可以参考: #213

我用的不是webui啊，而且也不是这个错

**Comment by jokerfree** [comment]
搞个测试文件运行一下看是true还是false
import torch
print(torch.cuda.is_available())

**Comment by jokerfree** [comment]
我猜你可能torch库没装

**Comment by DragonWang-cell** [comment]
使用cuda12.1解决了，证明cuda11.8不行

**Comment by jokerfree** [comment]
我用的就是cuda11.8，没啥问题

**Comment by DragonWang-cell** [comment]
> 我用的就是cuda11.8，没啥问题

那就很玄学了，11.8装了官方相配的torch两个版本都不行，换成12.1可以了

**Comment by hhk0571** [comment]
Nvidia 驱动、cuda版本、pytorch 版本太玄学了，我昨晚更新了一下Ubuntu系统，别说快与慢了，系统登入后直接卡死，键盘鼠标都没法操作，最好只能通过iPad登入，卸载所有Nvidia驱动，折腾了好几个小时才恢复到能使用GPU的状态。学到教训了，以后轻易不乱升级系统😄

**Comment by Xavier-i** [comment]
![image](https://github.com/2noise/ChatTTS/assets/12480879/921d3c81-a008-48d1-bbd4-6e38bf7c90ed)
我是用了gpu了，但是还是奇慢无比
![image](https://github.com/2noise/ChatTTS/assets/12480879/a8c3515b-567c-4309-9437-ee9fdf88d80f)
