### ISSUE TITLE
支持 MacbookPro M1/2/4？

### ISSUE THREAD

**Issue by Huixxi** [2noise/ChatTTS#215]

**Comment by fuyuwei01** [comment]
试了下不支持mps加速，只能用cpu来算。

**Comment by Huixxi** [comment]
> 试了下不支持mps加速，只能用cpu来算。

好的谢谢！那是不是巨慢！

**Comment by fuyuwei01** [comment]
> > 试了下不支持mps加速，只能用cpu来算。
> 
> 好的谢谢！那是不是巨慢！

其实体验还好，
```'四川美食可多了，有麻辣火锅、宫保鸡丁、麻婆豆腐、担担面、回锅肉、夫妻肺片等，每样都让人垂涎三尺。'``` 这句话大概十几秒吧，自己玩玩还是可以的

**Comment by Huixxi** [comment]
> > > 试了下不支持mps加速，只能用cpu来算。
> > 
> > 
> > 好的谢谢！那是不是巨慢！
> 
> 其实体验还好， `'四川美食可多了，有麻辣火锅、宫保鸡丁、麻婆豆腐、担担面、回锅肉、夫妻肺片等，每样都让人垂涎三尺。'` 这句话大概十几秒吧，自己玩玩还是可以的

那你的挺快的啊，我的M2 16G要40s左右，兄弟你也是把do_text_normalization这个开关关了才运行起来的么？

**Comment by Chuhan1112** [comment]
希望支持 M 系列芯片

**Comment by fuyuwei01** [comment]
> > > > 试了下不支持mps加速，只能用cpu来算。
> > > 
> > > 
> > > 好的谢谢！那是不是巨慢！
> > 
> > 
> > 其实体验还好， `'四川美食可多了，有麻辣火锅、宫保鸡丁、麻婆豆腐、担担面、回锅肉、夫妻肺片等，每样都让人垂涎三尺。'` 这句话大概十几秒吧，自己玩玩还是可以的
> 
> 那你的挺快的啊，我的M2 16G要40s左右，兄弟你也是把do_text_normalization这个开关关了才运行起来的么？

更新代码后也报normalization的错误了，安装了相应的包后可以运行。
conda install -c conda-forge pynini=2.1.5
pip install WeTextProcessing
pip install nemo_text_processing

**Comment by beautychen123** [comment]
> 试了下不支持mps加速，只能用cpu来算。> 试了下不支持mps加速，只能用cpu来算。大哥 能不能帮我看看 我这边安装 pynini 这个地方一直报错

**Comment by beautychen123** [comment]
！[上传微信IMG356.jpg...]() 救命!
