### ISSUE TITLE
mac m1报错呀，尝试改成mps，好像也是报这个错

### ISSUE THREAD

**Issue by Rick-ustc** [2noise/ChatTTS#216]
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
Traceback (most recent call last):
  File "../test_tts.py", line 12, in <module>
    wavs = chat.infer(texts, use_decoder=False)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/torch_env/lib/python3.8/site-packages/ChatTTS/core.py", line 95, in infer
    assert self.check_model(use_decoder=use_decoder)
AssertionError

**Comment by wnpllrzodiac** [comment]
the same error

**Comment by ooking** [comment]
`import ChatTTS
import scipy

model_path = '/Users/king/.cache/modelscope/hub/pzc163/chatTTS'

chat = ChatTTS.Chat()
chat.load_models(
    vocos_config_path=f"{model_path}/config/vocos.yaml",
    vocos_ckpt_path=f"{model_path}/asset/Vocos.pt",
    dvae_config_path=f"{model_path}/config/dvae.yaml",
    dvae_ckpt_path=f"{model_path}/asset/DVAE.pt" ,
    gpt_config_path=f"{model_path}/config/gpt.yaml",
    gpt_ckpt_path=f"{model_path}/asset/GPT.pt",
    decoder_config_path=f"{model_path}/config/decoder.yaml",
    decoder_ckpt_path=f"{model_path}/asset/Decoder.pt",
    tokenizer_path=f"{model_path}/asset/tokenizer.pt",
    device='cpu'
)

texts = ["hello", ]

wavs = chat.infer(texts, use_decoder=True)

scipy.io.wavfile.write(filename="./tts3.wav", rate=24_000, data=wavs[0].T)
`
