### ISSUE TITLE
本地测试的时候，不能100% 是什么原因？

### ISSUE THREAD

**Issue by tpjaord1983** [2noise/ChatTTS#220]
![image](https://github.com/2noise/ChatTTS/assets/36291579/237c7155-4bbd-4515-a9df-e533ac5cc485)

**Comment by Huixxi** [comment]
这个是代表啥意思？能处理的Tokens数量上限么？

**Comment by fuyuwei01** [comment]
分母表示的是处理的Tokens数量上限，代码中写死的。text不够长的话不会走满。

**Comment by fuyuwei01** [comment]
> 那为啥会有两个进度条，一个是input text另一个是audio的？

看了下源码，第一段是refine_text，感觉是对text加一些token提升输出质量用的，可以用```skip_refine_text=True```跳过。
第二个进度条是text到audio的

**Comment by tpjaord1983** [comment]
谢谢大家的解答。
