### ISSUE TITLE
一些参数的含义问题

### ISSUE THREAD

**Issue by DragonWang-cell** [2noise/ChatTTS#221]
请问推理代码中'[speed_5]，[oral_2]，[laugh_0]，[break_6]这些参数都是用来干什么的啊，有什么意义么，源代码如下
params_infer_code = {'prompt':'[speed_5]', 'temperature':.3}
params_refine_text = {'prompt':'[oral_2][laugh_0][break_6]'}

**Comment by hhk0571** [comment]
从这些单词可以猜测, 是语速, 腔调, 笑声, 停顿的special token, 后面跟的数字可能是不同的风格

**Comment by DragonWang-cell** [comment]
> 从这些单词可以猜测, 是语速, 腔调, 笑声, 停顿的special token, 后面跟的数字可能是不同的风格

嗯嗯嗯对的看起来像是，也就是说可能是训练过程中也添加了这些信息，像oral_2这些都对应了一种风格么（训练数据集中划分的不同风格），可以这么理解么

**Comment by 1771801582** [comment]
调整seed算是不同风格 不同音色，[speed_5]，[oral_2]，[laugh_0]，[break_6] 这些后面的数字代表refine text的过程中要加入的程度，可以理解成数字越大text中出现的次数越多，但和次数不是对等的

**Comment by ssccutyy** [comment]
> > 从这些单词可以猜测, 是语速, 腔调, 笑声, 停顿的special token, 后面跟的数字可能是不同的风格
> 
> 嗯嗯嗯对的看起来像是，也就是说可能是训练过程中也添加了这些信息，像oral_2这些都对应了一种风格么（训练数据集中划分的不同风格），可以这么理解么



> > 从这些单词可以猜测, 是语速, 腔调, 笑声, 停顿的special token, 后面跟的数字可能是不同的风格
> 
> 嗯嗯嗯对的看起来像是，也就是说可能是训练过程中也添加了这些信息，像oral_2这些都对应了一种风格么（训练数据集中划分的不同风格），可以这么理解么

oral_2我猜是个人口语化的表达出现两次，比如“然后”这些词

**Comment by zcfrank1st** [comment]
希望官方出个详细的说明，学习一下，谢谢

**Comment by libukai** [comment]
![web-ui](https://github.com/2noise/ChatTTS/assets/5654585/25050c26-e772-4631-ab26-0e9a010a3ae4)

详细解读在 [ChatTTS-Control](https://github.com/libukai/ChatTTS-Control)

**Comment by libukai** [comment]
> > ChatTTS-Control
> 
> 请问如果我已经装了的话，如何再去对接使用这个webui？

官方版本已经跑起来了的话，直接 clone  这个执行里面的 web-ui 就行

**Comment by libukai** [comment]
官方的怎么跑的，这个就怎么跑，注意把依赖装全

**Comment by hhk0571** [comment]
> ![web-ui](https://private-user-images.githubusercontent.com/5654585/337063655-25050c26-e772-4631-ab26-0e9a010a3ae4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDUxMDMsIm5iZiI6MTcxNzY0NDgwMywicGF0aCI6Ii81NjU0NTg1LzMzNzA2MzY1NS0yNTA1MGMyNi1lNzcyLTQ2MzEtYWIyNi0wZTlhMDEwYTNhZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDMzMzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWExN2M2NThhNTg0NmYwYWI0ZGVhYTJiOTUwYzEwNjE4ZGM5YWUzMDFlZWM1YjUzN2MwNTM2OTc2ZjE2NDkzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Nkco87-rtxkZ0PbDp8n6CL9_7dcMf5_Owiq17g5Nuw)
> 
> 详细解读在 [ChatTTS-Control](https://github.com/libukai/ChatTTS-Control)

太牛叉了 👍👍👍
