### ISSUE TITLE
报错:WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead

### ISSUE THREAD

**Issue by gggggwen** [2noise/ChatTTS#229]
![屏幕截图 2024-06-03 205946](https://github.com/2noise/ChatTTS/assets/162149042/eaf19edb-e033-427e-8822-4a273dc460d1)

**Comment by gggggwen** [comment]
已解决

**Comment by shirubei** [comment]
装了gpu版的pytorch了吗

**Comment by dyfqpl1** [comment]
遇到了同样的问题，怎么解决啊

**Comment by KiwiHana** [comment]
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:decoder not initialized.
Traceback (most recent call last):
  File "C:\Users\solution\run_chattts.py", line 13, in <module>
    wavs = chat.infer(texts, use_decoder=True)
  File "C:\Users\hu\Miniconda3\envs\chattts\lib\site-packages\ChatTTS\core.py", line 95, in infer
    assert self.check_model(use_decoder=use_decoder)
AssertionError

**Comment by johne5s** [comment]
> Have you installed the gpu version of pytorch?

I had the same thing.  I needed to install the torch GPU version from the torch website.
https://pytorch.org/get-started/previous-versions/

i have a 3090, and used these commands.
pip uninstall torch
# CUDA 11.8
pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118

**Comment by shinedlc** [comment]
1、Check CUDA version first: nvcc --version
2、Ensure: 
invidia-smi ≥ nvcc --version ≥ Pytorch cudatoolkit version required
3、Test:
$ python
>>> import torch
>>> print(torch.cuda.is_available())
True

**Comment by KiwiHana** [comment]
I don't have NV DGPU on device. 

> 1、Check CUDA version first: nvcc --version 2、Ensure: invidia-smi ≥ nvcc --version ≥ Pytorch cudatoolkit version required 3、Test: $ python
> 
> > > > import torch
> > > > print(torch.cuda.is_available())
> > > > True

**Comment by grarahbsaerhra** [comment]
> 我的设备上没有 NV DGPU。
> 
> > 1、首先检查CUDA版本：nvcc--version 2、确保：invidia-smi ≥nvcc --version ≥ 需要Pytorch cudatoolkit版本 3、测试：$python
> > > > > 导入割炬打印（torch.cuda.is_available（）） True

me too

**Comment by fsea** [comment]
1、pip uninstall -y torch torchaudio
2、pip install torch torchaudio

**Comment by hexf00** [comment]
```shell
nvcc -V
python
```

```py
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.version.cuda)
```

版本一致后可以启用GPU，4060 比 7945hx 快 3 倍左右

**Comment by KiwiHana** [comment]
> 1、pip uninstall -y torch torchaudio 2、pip install torch torchaudio

torch                     2.3.1+cpu
torchaudio                2.3.1+cpu

(chattts) C:\digtal_human\ChatTTS>python run_chattts.py
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:decoder not initialized.
Traceback (most recent call last):
  File "C:\Users\sutai\Desktop\digtal_human\ChatTTS\run_chattts.py", line 20, in <module>
    wavs = chat.infer(texts, use_decoder=True)
  File "C:\Users\sutai\.conda\envs\chattts\lib\site-packages\ChatTTS\core.py", line 95, in infer
    assert self.check_model(use_decoder=use_decoder)
AssertionError
