### ISSUE TITLE
TypeError: Chat.load_models() got an unexpected keyword argument 'compile'

### ISSUE THREAD

**Issue by zhouyi-up** [2noise/ChatTTS#232]
import ChatTTS
import torch
import torchaudio
from IPython.display import Audio

chat = ChatTTS.Chat()
chat.load_models(compile=True)  # Set to True for better performance

texts = ["PUT YOUR TEXT HERE", ]

wavs = chat.infer(texts, )

torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)

Error message：
Traceback (most recent call last):
  File "F:\test-workspace\ai-study\chattts_demo\main.py", line 7, in <module>
    chat.load_models(compile=True)  # Set to True for better performance
TypeError: Chat.load_models() got an unexpected keyword argument 'compile'

这个问题怎么处理？

**Comment by shirubei** [comment]
但凡你先搜索一下就不会浪费时间再开一个贴了

**Comment by fumiama** [comment]
与 #140 重复。
