### ISSUE TITLE
是否有word level manual control的全部特殊token参考？

### ISSUE THREAD

**Issue by SchweitzerGAO** [2noise/ChatTTS#234]
目前在文档里只见到了`[uvbreak]` ,`[laugh]` `[lbreak]`这几个，请问开发者大佬能不能提供一个参考表之类的东西，感激不尽

**Comment by liyuanhe211** [comment]
```

##### Besides laughter, can we control anything else? Can we control other emotions?

In the current released model, the only token-level control units are [laugh], [uv_break], and [lbreak]. In future versions, we may open-source models with additional emotional control capabilities.

```

**Comment by liyuanhe211** [comment]
> 
> ##### Besides laughter, can we control anything else? Can we control other emotions?
> 
> In the current released model, the only token-level control units are [laugh], [uv_break], and [lbreak]. In future versions, we may open-source models with additional emotional control capabilities.
>

**Comment by SchweitzerGAO** [comment]
好的，感谢
