### ISSUE TITLE
[分享] ChatTTS Forge 项目

### ISSUE THREAD

**Issue by zhzLuke96** [2noise/ChatTTS#237]
分享下我的项目，实现了大部分 api 需求
https://github.com/lenML/ChatTTS-Forge

还实验性质的写了一个 ssml 语法用来支持长文本定制生成
另外还有 prompt 注入对生成进行风格干预

你可以在 huggingface 上在线体验（速度超快）：
https://huggingface.co/spaces/lenML/ChatTTS-Forge

欢迎提来pr issues

**Comment by handles98** [comment]
能实现多角色音色匹配，这个好！

**Comment by 3682483** [comment]
这项目有意思！

**Comment by hwang824** [comment]
非常棒！

**Comment by zhzLuke96** [comment]
补充一个 colab 一键启动脚本

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lenML/ChatTTS-Forge/blob/main/colab.ipynb)

**Comment by muei** [comment]
请问你这个怎么保存音色啊
