### ISSUE TITLE
【分享】几个还不错的音色分享给大家

### ISSUE THREAD

**Issue by QuantumDriver** [2noise/ChatTTS#238]
https://ixo96gpj4vq.feishu.cn/wiki/SjiZwNSuUin9fukZh23cIMBOnge?from=from_copylink

**Comment by 6drf21e** [comment]
好听！
能否用这几个音色作为默认音色加到 https://github.com/6drf21e/ChatTTS_colab   
下个版本准备支持保存文件音色 @QuantumDriver

**Comment by 6drf21e** [comment]
会注明出处

**Comment by QuantumDriver** [comment]
> 好听！ 能否用这几个音色作为默认音色加到 https://github.com/6drf21e/ChatTTS_colab 下个版本准备支持保存文件音色 @QuantumDriver

好的没问题！

**Comment by aqpmzngldh** [comment]
> > 好听！能否用这几个音色作为默认音色添加到https://github.com/6drf21e/ChatTTS_colab下一个版本准备支持保存文件音色@QuantumDriver
> 
> 好的没问题！

能不能自定义音色嘞

**Comment by QuantumDriver** [comment]
> > > 好听！能否用这几个音色作为默认音色添加到[https://github.com/6drf21e/ChatTTS_colab下一个版本准备支持保存文件音色@QuantumDriver](https://github.com/6drf21e/ChatTTS_colab%E4%B8%8B%E4%B8%80%E4%B8%AA%E7%89%88%E6%9C%AC%E5%87%86%E5%A4%87%E6%94%AF%E6%8C%81%E4%BF%9D%E5%AD%98%E6%96%87%E4%BB%B6%E9%9F%B3%E8%89%B2@QuantumDriver)
> > 
> > 
> > 好的没问题！
> 
> 能不能自定义音色嘞

目前不还能，只能靠随机生成，如果生成的音色觉得还不错就保存下来

**Comment by zhzLuke96** [comment]
感谢分享，你分享的音色已收录到 ChatTTS-Forge 项目中

可以到这里体验 https://huggingface.co/spaces/lenML/ChatTTS-Forge

**Comment by 6drf21e** [comment]
感谢 @QuantumDriver 提供音色
感谢 @v3ucn 的 pr https://github.com/6drf21e/ChatTTS_colab/releases/tag/v0.0.5
![image](https://github.com/2noise/ChatTTS/assets/29720712/102efad7-151a-4b30-8cbd-1c70339726e0)
