### ISSUE TITLE
程序在M1芯片上跑到8%-10%左右就终止，无错误提示

### ISSUE THREAD

**Issue by glovebx** [2noise/ChatTTS#24]
M1芯片上跑起来之后：
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
INFO:ChatTTS.core:All initialized.
  3%|████                                                                                                                   | 13/384 [00:00<00:16, 22.89it/s]
  8%|█████████▌                                                                                                           | 168/2048 [00:05<01:06, 28.45it/s]

就这样终止了，没有任何错误提示

**Comment by Felix-DHE** [comment]
这是内容生成完成了，需要执行Audio(wavs[0], rate=24_000, autoplay=True)这个生成音频文件，找到生成的音频文件就能正常播放了。

**Comment by ChenzhengUESTC** [comment]
哎，为什么我跑不起来？我也是m1

<img width="795" alt="iShot_2024-05-28_22 17 55" src="https://github.com/2noise/ChatTTS/assets/4604830/f88270f4-2ee0-441e-94f3-a28e84803aed">

**Comment by wa008** [comment]
> > 这是内容生成完成了，需要执行Audio(wavs[0], rate=24_000, autoplay=True)这个生成音频文件，找到生成的音频文件就能正常播放了。
> 
> 你是说这个情况已经成功了？，生成的文件在哪呢。同样的问题


原代码是在 jupyter 上运行的，终端运行可以用以下代码保存音频文件，跟原代码生成的音质差不多。
```
import scipy
scipy.io.wavfile.write(filename = "./chattts_download_0.wav", rate = 24_000, data = wavs[0].T)
```

**Comment by yuhaolove** [comment]
对于还没有安装成功或使用成功的用户，这个WebUI可以大大帮助您。请大家尝试一下，并告诉我您的反馈。您的意见对改进这个工具、让它变得更加用户友好非常重要。

[ChatTTS-WebUI](https://github.com/yuhaolove/ChatTTS-WebUI)

**Comment by ChinaStark** [comment]
> 哎，为什么我跑不起来？我也是m1
> 
> <img alt="iShot_2024-05-28_22 17 55" width="795" src="https://private-user-images.githubusercontent.com/4604830/334458303-f88270f4-2ee0-441e-94f3-a28e84803aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjkxOTksIm5iZiI6MTcxNzA2ODg5OSwicGF0aCI6Ii80NjA0ODMwLzMzNDQ1ODMwMy1mODgyNzBmNC0yZWUwLTQ0MWUtOTRmMy1hMjhlODQ4MDNhZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMTEzNDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmJiMDk0M2IxNzMyNjZiZDE2MjBjYjYxYTdiMWRiN2RlMDYyNzY3MTYzMGE4NGJjODYzMDhmNWQ2MDUxNWY5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G42myhOOPBS_ef9m1JarA_1Rja5PaWkJgWLOCKuDQWM">

你下载model参数了吗？？？     不写了not initialize吗？
