### ISSUE TITLE
为什么会自己加字？

### ISSUE THREAD

**Issue by zhouhao27** [2noise/ChatTTS#246]
比如：`白 日 依 山 尽 ， 黄 河 入 海 流。 欲 穷 千 里目 ， 更 上  一 层 楼 。`
生成文字为：`白 日 依 山 尽 [uv_break] ， 黄 河 入 海 流 [uv_break] 。 欲 穷 千 里 目 [uv_break] ， 那 更 上 一 层 楼 [uv_break] 。`

为什么要加一个**那**字，有办法保持原文吗？

**Comment by wxsthuee** [comment]
试试把oral改到0

**Comment by libukai** [comment]
取消 refine text 的勾选

![web-ui](https://github.com/2noise/ChatTTS/assets/5654585/fc188e9d-f0c6-440e-8980-9e343fbed1a0)

**Comment by TommyZihao** [comment]
试试把oral改到0
