### ISSUE TITLE
ChatTTS+MuseTalk?

### ISSUE THREAD

**Issue by shaoguowen** [2noise/ChatTTS#251]
1. 使用chatgpt改编了延边刺客的经典台词。
2. chatTTS生成语音。我用到了https://ixo96gpj4vq.feishu.cn/wiki/SjiZwNSuUin9fukZh23cIMBOnge 分享的电台主持人语音，并把转成csv在https://github.com/jianchang512/ChatTTS-ui使用。
3. 用MuseTalk生成口型：https://github.com/TMElyralab/MuseTalk

https://github.com/2noise/ChatTTS/assets/57278682/ea561feb-c606-4f21-8b40-9cb82643f644

Just for fun哈哈哈，更多AIGC的内容可以看我的视频号（温少的AIGC），欢迎交流讨论～

**Comment by shirubei** [comment]
厉害了。不过感觉口型还不是很好。不知道换wav2lip等其他一堆东西的话怎么样

**Comment by jianchang512** [comment]
csv 能否pr分享下，可以 加到 speaker 文件夹内，seed值命名

**Comment by ilexcn** [comment]
> 1. 使用chatgpt改编了延边刺客的经典台词。
> 2. chatTTS生成语音。我用到了https://ixo96gpj4vq.feishu.cn/wiki/SjiZwNSuUin9fukZh23cIMBOnge 分享的电台主持人语音，并把转成csv在[https://github.com/jianchang512/ChatTTS-ui使用。](https://github.com/jianchang512/ChatTTS-ui%E4%BD%BF%E7%94%A8%E3%80%82)
> 3. 用MuseTalk生成口型：https://github.com/TMElyralab/MuseTalk
> 
>  monalisa_0604-1.mp4 
> Just for fun哈哈哈，更多AIGC的内容可以看我的视频号（温少的AIGC），欢迎交流讨论～

用UVR5 去除下背景杂音

**Comment by shaoguowen** [comment]
> 厉害了。不过感觉口型还不是很好。不知道换wav2lip等其他一堆东西的话怎么样

确实，等EMO和vasa-1都等到emo了

**Comment by shaoguowen** [comment]
> > 1. 使用chatgpt改编了延边刺客的经典台词。
> > 2. chatTTS生成语音。我用到了https://ixo96gpj4vq.feishu.cn/wiki/SjiZwNSuUin9fukZh23cIMBOnge 分享的电台主持人语音，并把转成csv在[https://github.com/jianchang512/ChatTTS-ui使用。](https://github.com/jianchang512/ChatTTS-ui%E4%BD%BF%E7%94%A8%E3%80%82)
> > 3. 用MuseTalk生成口型：https://github.com/TMElyralab/MuseTalk
> > 
> > monalisa_0604-1.mp4
> > Just for fun哈哈哈，更多AIGC的内容可以看我的视频号（温少的AIGC），欢迎交流讨论～
> 
> 用UVR5 去除下背景杂音

人声很清楚呀

**Comment by shaoguowen** [comment]
这是那几个csv文件
[魅力大叔_male.csv](https://github.com/user-attachments/files/15572065/_male.csv)
[电视台女主持_female.csv](https://github.com/user-attachments/files/15572066/_female.csv)
[知心小姐姐_female.csv](https://github.com/user-attachments/files/15572067/_female.csv)
[阳光开朗大男孩_male.csv](https://github.com/user-attachments/files/15572068/_male.csv)
[纯情男大学生_male.csv](https://github.com/user-attachments/files/15572069/_male.csv)
[声音有点像陈一发_female.csv](https://github.com/user-attachments/files/15572070/_female.csv)

**Comment by shaoguowen** [comment]
new result
https://github.com/2noise/ChatTTS/assets/57278682/7159c17f-15da-4707-9505-310edefa7b3c

**Comment by shaoguowen** [comment]
https://github.com/2noise/ChatTTS/assets/57278682/ab8f8b4c-2332-4195-86cf-129064c9524c
