### ISSUE TITLE
Error installing and running on apple silicon - M1 chip 

### ISSUE THREAD

**Issue by FotieMConstant** [2noise/ChatTTS#263]
i get this error:

```bash
Traceback (most recent call last):
  File "/Users/🤓/demo-tts/main.py", line 1, in <module>
    import ChatTTS
  File "/Users/🤓/anaconda3/envs/ml-env/lib/python3.10/site-packages/ChatTTS/__init__.py", line 1, in <module>
    from .core import Chat
  File "/Users/🤓/anaconda3/envs/ml-env/lib/python3.10/site-packages/ChatTTS/core.py", line 6, in <module>
    from chattts.model.dvae import DVAE
ModuleNotFoundError: No module named 'chattts'
```

when i try to run this code:

```python
import ChatTTS
from IPython.display import Audio

chat = ChatTTS.Chat()
chat.load_models(compile=False) # Set to True for better performance

texts = """
chat T T S is a text to speech model designed for dialogue applications. 
[uv_break]it supports mixed language input [uv_break]and offers multi speaker 
capabilities with precise control over prosodic elements [laugh]like like 
[uv_break]laughter[laugh], [uv_break]pauses, [uv_break]and intonation. 
[uv_break]it delivers natural and expressive speech,[uv_break]so please
[uv_break] use the project responsibly at your own risk.[uv_break]
""".replace('\n', '') # English is still experimental.

wavs = chat.infer(texts, )

torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)
```

OS: macOS, M1 chip

**Comment by samsontands** [comment]
try this method: worked for me.

MacOS安装步骤
1、安装brew工具：打开[https://brew.sh/](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbGdEZ3MwQVFYWXNmMzkyajBYYmlNalpUa21xd3xBQ3Jtc0tsOThISzZNSEg0WE9DSU1WZ1FwdXJVaXVCVGdnZWFjWWM0ak5ES0pkRG9zRmtPVHlHcWtvbFRFY3NGRFhDaGMxeVkzLWNVekRDbjlxM3VnbHFaNXBZNkhKOUhOV0pZX29HX0NWb28telVaLThqMmROcw&q=https%3A%2F%2Fbrew.sh%2F&v=9mMMoZuLWM0) 手动复制安装指令
2、用brew安装git：brew install git
3、用brew安装miniconda：brew install miniconda    安装好以后关闭终端重新打开
4、conda初始化：conda init --all
5、conda创建虚拟环境：conda create --name chattts  python=3.10
6、激活虚拟环境chattts：conda activate chattts
7、克隆程序库：git clone  [https://github.com/2noise/ChatTTS.git](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbWVCdlJ0Y2xLNEJoaVQyTU4zZUZVTmswV2hyZ3xBQ3Jtc0tuYk5zQVBVRUdTa2pobEVRYzg3QW9XanF4NXgta2RDbmNHcVJOeTMtUzYtSGNDOHlnWEg1TGlXRC1aQjJiUnNCQzgwOVlrbWlMZnB6WEttTkU2X0pRdlU4UWtJbjJnYzQ5ekhfZjc2ajZIczZTMUFFUQ&q=https%3A%2F%2Fgithub.com%2F2noise%2FChatTTS.git&v=9mMMoZuLWM0)
8、切换目录：cd chatTTS
9、安装依赖包：pip3  install  -r  requirements.txt
10、检查依赖包：pip list
11、没gradio要安装：pip3 install gradio   安装完以后关闭终端重新打开
12、切换目录激活虚拟环境然后运行：cd chatTTS    conda activate    python   webui.py
13、根据提示执行两条指令安装缺少的WeTextProcessing依赖包
conda install -c conda-forge pynini=2.1.5
pip  install WeTextProcessing （或者pip3  install WeTextProcessing）
14、以上两条指令执行完成后，关闭终端重新运行即可使用。

**Comment by masonchen2014** [comment]
> > httpx.RemoteProtocolError: Server disconnected without sending a response.
> 
> Hello, have you solved it yet please, I'm getting the same error.

I also met this same error , and I solved it by turning off my vpn
