### ISSUE TITLE
got an unexpected keyword

### ISSUE THREAD

**Issue by mechigonft** [2noise/ChatTTS#264]
加了：
import torch
torch._dynamo.config.cache_size_limit = 64
torch._dynamo.config.suppress_errors = True
torch.set_float32_matmul_precision('high')
还是没办法启动推理，报错load_models() got an unexpected keyword argument 'source'

**Comment by libukai** [comment]
模型没有下载下来，见常见问题解答一，下载之后修改对应的路径

**Comment by kandada** [comment]
我的也是一样，模型确定是已经下载下来了的。系统是ubuntu22.04。
求解决方法
