### ISSUE TITLE
AttributeError module 'ChatTTS' has no attribute 'Chart'

### ISSUE THREAD

**Issue by Jazzy411** [2noise/ChatTTS#266]
chat = ChatTTS.Chart()
AttributeError: partially initialized module 'ChatTTS' has no attribute 'Chart' (most likely due to a circular 
import)

Scripts:
```
import ChatTTS
from IPython.display import Audio
chat = ChatTTS.Chart()
```

**Comment by libukai** [comment]
It's `Chat`, not `Chart`

```python
 chat = ChatTTS.Chat()
```

**Comment by Jazzy411** [comment]
> It's `Chat`, not `Chart`
> 
> ```python
>  chat = ChatTTS.Chat()
> ```

![image](https://github.com/2noise/ChatTTS/assets/59430852/98dfea4e-a22c-4685-bd67-b8a2f471c305)
Sorry for the mistake. But the same for Chat.

**Comment by mohammednuruddin** [comment]
same here

**Comment by Eugenio-Schiavoni** [comment]
same here!
