### ISSUE TITLE
what is the set up/install to be used to test and install this in google colab?

### ISSUE THREAD

**Issue by silvacarl2** [2noise/ChatTTS#268]
what is the set up/install to be used to test and install this in google colab?

this stuff looks awesome!

carl

**Comment by libukai** [comment]
![142f0be2277d3d8cfdae727a0fca81aa](https://github.com/2noise/ChatTTS/assets/5654585/3dcde565-bf29-425a-84e1-28f7090dab37)

Try ChatTTS_colab to install this in google colab

**Comment by utshomax** [comment]
#293 added a complete colab demo, just make sure your runtime is T4.
