### ISSUE TITLE
[FEATURE] Upload to PyPi

### ISSUE THREAD

**Issue by zanderlewis** [2noise/ChatTTS#269]
It would be nice to make this a PyPi package so anyone can download and use this model easily.

**Comment by libukai** [comment]
![142f0be2277d3d8cfdae727a0fca81aa](https://github.com/2noise/ChatTTS/assets/5654585/8e178679-0a56-459c-8e92-532bc2e2b256)

Try ChatTTS-fork to test with Pypi

**Comment by fumiama** [comment]
> It would be nice to make this a PyPi package so anyone can download and use this model easily.

WIP. This package now need to download assets outside, which is not suitable for a pypi package. If we decoupled this behavior, glad to upload it to pypi.

**Comment by jtoy** [comment]
how do all the other big models do it?
