### ISSUE TITLE
Please teach me how to use these parameters

### ISSUE THREAD

**Issue by linchen1987** [2noise/ChatTTS#274]
I hope to briefly explain the meaning of the parameters 'refine text', 'autio temperature', 'top_P', 'top_K', 'Audio Seed', 'Text Seed' from the perspective of usage? How to use them?

<img width="1253" alt="image" src="https://github.com/2noise/ChatTTS/assets/11010275/80f44556-a0d4-4fcb-ba76-eaefdf24fbd5">

**Comment by libukai** [comment]
![web-ui](https://github.com/2noise/ChatTTS/assets/5654585/ebb59e85-c021-4a76-b34c-fb18f3960b8e)
