### ISSUE TITLE
为什么输出音频采样率是24K的

### ISSUE THREAD

**Issue by wuhongsheng** [2noise/ChatTTS#275]

**Comment by teressawang** [comment]
torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)

你用的这个吗？  最后一个 24000 就是采样率 可以改 48k

**Comment by wuhongsheng** [comment]
> torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)
> 
> 你用的这个吗？ 最后一个 24000 就是采样率 可以改 48k
我想降到16K，但是音频音频质量就下降

**Comment by sherryxie1** [comment]
24k是因为他们训练用的24k语音。想要16k的话可以先生成24k的然后resample
