### ISSUE TITLE
创建了一个汇总安装指南、参数说明、音色列表、常见问题、资源推荐的入门指南，新人建议先完整看一遍

### ISSUE THREAD

**Issue by libukai** [2noise/ChatTTS#277]
把 Issues 中的常见问题都过了一遍，整理了一个入门指南，新人建议先完整看一遍 

项目地址：[Awesome-ChatTTS](https://github.com/libukai/Awesome-ChatTTS)，觉得有用还请打赏个 ⭐️ 支持一下

* [快速体验](https://github.com/libukai/Awesome-ChatTTS#%E5%BF%AB%E9%80%9F%E4%BD%93%E9%AA%8C)
* [热门分支](https://github.com/libukai/Awesome-ChatTTS#%E7%83%AD%E9%97%A8%E5%88%86%E6%94%AF)
* [参数说明](https://github.com/libukai/Awesome-ChatTTS#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)
* [固定音色](https://github.com/libukai/Awesome-ChatTTS#%E5%9B%BA%E5%AE%9A%E9%9F%B3%E8%89%B2)
* [安装指南](https://github.com/libukai/Awesome-ChatTTS#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97)
* [常见问题](https://github.com/libukai/Awesome-ChatTTS#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
* [报错速查](https://github.com/libukai/Awesome-ChatTTS#%E6%8A%A5%E9%94%99%E9%80%9F%E6%9F%A5)

![web-ui](https://github.com/2noise/ChatTTS/assets/5654585/3cd29ab2-aa47-42ea-b153-57c9c1cacae2)

**Comment by jvssoft** [comment]
不错,点赞,可否考虑研究一下流式合成?

**Comment by 906051999** [comment]
非常感谢你的项目！

**Comment by viewlei** [comment]
提一个问题：固定seed后，在当前环境下多次运行同一个text的确可以保证合成出来的音频完全一样，但是不代表同样的seed在其他机器上也能合成出来和你一样的结果。

建议考虑下在抽卡遇到合适的音色时，除了保存seed以外，同时保存     rand_spk = chat.sample_random_speaker()  这样的一个结果到本地，维护好 <seed, rand_spk>的列表。在共享音色的时候，其实共享的应该是 rand_spk。

**Comment by snoopyhuang** [comment]
函文已收：大函细读，尊意俱悉！黄少南15208159495，承蒙关注，特此感谢！

**Comment by libukai** [comment]
> 提一个问题：固定seed后，在当前环境下多次运行同一个text的确可以保证合成出来的音频完全一样，但是不代表同样的seed在其他机器上也能合成出来和你一样的结果。
> 
> 建议考虑下在抽卡遇到合适的音色时，除了保存seed以外，同时保存 rand_spk = chat.sample_random_speaker() 这样的一个结果到本地，维护好 <seed, rand_spk>的列表。在共享音色的时候，其实共享的应该是 rand_spk。

谢谢提醒，明天测试一下，继续优化

**Comment by waltcow** [comment]
文档这里 写错了 
> conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing

应该是

conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing

**Comment by foxsinyo** [comment]
您好，我这边部署好了之后一直报错，可以帮忙看下日志什么原因导致的吗

![报错1](https://github.com/2noise/ChatTTS/assets/117609529/3e1c5496-3764-4cea-9f5e-2e5c91040426)
![报错日志](https://github.com/2noise/ChatTTS/assets/117609529/bb83762d-0efa-45f2-a9e1-c47ffc74170e)

**Comment by libukai** [comment]
模型下载不成功，参见 常见问题-模型无法下载 问题

**Comment by foxsinyo** [comment]
> 模型下载不成功，参见 常见问题-模型无法下载 问题

你好，第10行添加导入依赖：from modelscope import snapshot_download ，那原有的import ChatTTS 删除吗，还是在import ChatTTS 后面写

**Comment by foxsinyo** [comment]
您好，常见问题-模型无法下载解决方法中说第10行 102,104行要加代码。是我截图中的位置吗。
然后比如#第 10 行添加导入依赖：from modelscope import snapshot_download。  那我是在我第10行import ChatTTS 后面添加这个代码，还是回车把import ChatTTS 落到第11行，然后在第十行写from modelscope import snapshot_download吗

![10行](https://github.com/2noise/ChatTTS/assets/117609529/3f8440f8-27ad-4eb2-bcfd-0db53f868730)
![102 104](https://github.com/2noise/ChatTTS/assets/117609529/94413f02-55b7-4808-bb21-5aa2e0d1a460)
您好，

**Comment by foxsinyo** [comment]
您好，遇到了报错，您说模型下载不成功，参见 常见问题-模型无法下载 问题，按照里面的做了，但是还是报错
![错误新](https://github.com/2noise/ChatTTS/assets/117609529/78048226-4e60-4697-ac11-6e47190af9ca)
![改1](https://github.com/2noise/ChatTTS/assets/117609529/72e9e5c1-6232-41f0-ae03-c87f42777165)
![改2](https://github.com/2noise/ChatTTS/assets/117609529/905e28c9-169c-4188-ae33-942bdf675f02)

**Comment by libukai** [comment]
不是改这里，重新 pull 一下最新版吧，webui.py 中更新成国内模型下载方式了
