### ISSUE TITLE
语速怎么调节，有靓仔知道吗

### ISSUE THREAD

**Issue by Leslie-XH** [2noise/ChatTTS#278]
语速怎么调节，有靓仔知道吗

**Comment by libukai** [comment]
![web-ui](https://github.com/2noise/ChatTTS/assets/5654585/90aadeff-12fe-45a6-9841-af531e48bb9a)

**Comment by jumao1hao** [comment]
不知道唉

**Comment by Leslie-XH** [comment]
谢谢，下载了项目运行了确实可以调慢语速，我再研究下代码是怎么实现的

**Comment by gongming1963** [comment]
@Leslie-XH 求问下载的是哪个版本？
我现在运行的版本，没有 Speed 选项

![image](https://github.com/2noise/ChatTTS/assets/4929753/bee6142b-aad6-4320-bf95-f3e41aac5c79)

**Comment by libukai** [comment]
https://github.com/libukai/Awesome-ChatTTS，应该说的是我的库
