### ISSUE TITLE
有没有其他推荐的开源TTS，可以做到流式或者低延迟响应的，chattts的速度实在是慢

### ISSUE THREAD

**Issue by chwyxy** [2noise/ChatTTS#279]
我在A100上运行的chattts，生成长文本需要很长时间，后面尝试去做文本分割，一段段的生成，速度也还是不行，之前实现了基于paddlespeech的语音合成，流式的效果很好，但是音色比较拉跨，有没有合成效果不那么拉跨，而且速度还可以的tts推荐

**Comment by teressawang** [comment]
bert bits 2  试过没？

**Comment by QuantumDriver** [comment]
![tts](https://github.com/2noise/ChatTTS/assets/48795900/d79eb5a1-149c-4479-b2cd-9b97bfaedd7f)
实测4090显卡下15秒生成2分钟的音频（批处理后再合并，显存占用12G）

**Comment by lphkxd** [comment]
目前我用的vits2

**Comment by chwyxy** [comment]
> ![tts](https://private-user-images.githubusercontent.com/48795900/337307390-d79eb5a1-149c-4479-b2cd-9b97bfaedd7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzA3OTMsIm5iZiI6MTcxNzczMDQ5MywicGF0aCI6Ii80ODc5NTkwMC8zMzczMDczOTAtZDc5ZWI1YTEtMTQ5Yy00NDc5LWIyY2QtOWI5N2JmYWVkZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDAzMjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOTk2YmM2OTI5MjNhNzcyN2NjYzRjYjI4NzZmNjFjMzhkNTE5MGNiMmM5NmVhOGU5YWQ3NjRmODczNDA3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l4v_O440HcNBkFfRMmJzsfOqVqoqCmUDdotAN7hfaf4) 实测4090显卡下15秒生成2分钟的音频（批处理后再合并，显存占用12G）

可以提供一下代码吗，我这边测试没有这么快的速度，还是很慢

**Comment by hoveychen** [comment]
ChatTTS的延时比较严重，单纯批处理速度还行。如果要低延时，估计得改代码做流式输出，对于自回归模型，大概是可能可以做到的

**Comment by haidog-yaqub** [comment]
用vits2

**Comment by jlia0** [comment]
Using A100-40GB from modal for generating a 10-second clip takes ~ 6 seconds, making this model unusable for real-time applications.
