### ISSUE TITLE
【1000个 chatTTS音色】熬夜龟速生产并上传了1000个 chatTTS音色，在线播放，不为音色抽卡烦恼了哈 。  1001~10000生产中...

### ISSUE THREAD

**Issue by kangyiwen** [2noise/ChatTTS#281]
## 1000个 chatTTS音色

熬夜龟速上传了1000个 chatTTS音色，在线播放，不为音色抽卡烦恼了哈    ：）

https://github.com/kangyiwen/TTSlist

用GPT做了个单页面： www.TTSlist.com     备用：http://ttslist.aiqbh.com/

我是菜鸟，5月才开始学PY的，chatTTS真好玩，音色抽卡太费时间了，干脆生产一大批，和大家分享下，
这会在往github上传呢，传完睡觉。

我还做了个自动生产对话的程序，也是GPT写的，成熟点也放上来。

**Comment by kangyiwen** [comment]
https://kangyiwen.github.io/TTSlist-En/

**Comment by QuantumDriver** [comment]
bro，你有音色的性别和大致描述吗？

**Comment by kangyiwen** [comment]
还没有做描述，一开始以为可以用数字大概区分男女，实际发现还不是这样。




XinOu ***@***.***> 于2024年6月7日周五 10:26写道：

**Comment by libukai** [comment]
推荐了一下，很多朋友反馈打开速度慢，不能播放

**Comment by kangyiwen** [comment]
应该是页面打开后，直接默认去自动下载这些音色了。  我来问问GPT能否优化一下。

另外，可以直接百度网盘下载，本地播放，一共800多M，本地播放很舒服，页面也有。


libukai ***@***.***> 于2024年6月7日周五 12:32写道：

**Comment by libukai** [comment]
额，这个……改成点击播放了再下载吧……

**Comment by kangyiwen** [comment]
嗯，我也这么想的，在让GPT修改试试。

另外，大家感觉1000个音色够玩吗？ 还是要更多，感觉生产1万个都能行的样子。


libukai ***@***.***> 于2024年6月7日周五 12:39写道：

**Comment by libukai** [comment]
在精不在多，精选一下，更有价值

**Comment by kangyiwen** [comment]
精选标准，每个人不太一样，这个很难说。 有时候，就需要点“土味”或者不一样的感觉。

最好还是量大，也有精选。


libukai ***@***.***> 于2024年6月7日周五 12:43写道：

**Comment by kangyiwen** [comment]
www.TTSlist.com  页面更新了，加载方式改了，帮忙试试看。

**Comment by trigsoft** [comment]
国外还打不开

**Comment by youshanxiansheng** [comment]
俩个都打不开了，上午还能打

**Comment by rijin89** [comment]
英文的也打不开，我自己测试英文都是有的怪怪的 哈哈

**Comment by rijin89** [comment]
各位如果有好的**英语音色**求分享

**Comment by kangyiwen** [comment]
> 各位如果有好的**英语音色**求分享

https://github.com/kangyiwen/TTSlist-En    有1000个英语音色，可以看看。

**Comment by libukai** [comment]
在我的 Fork 中，为这个项目增加了一个推荐，请问可以在网页上放一个我项目的链接吗？ [Awesome-ChatTTS](https://github.com/libukai/Awesome-ChatTTS)

![CleanShot 2024-06-09 at 12 23 41@2x](https://github.com/2noise/ChatTTS/assets/5654585/cd0778d5-d16f-45ef-9b3e-161f8d62d922)

**Comment by kangyiwen** [comment]
ok  互换下吧   我把 https://github.com/libukai/Awesome-ChatTTS  放到我项目介绍里去

**Comment by anwen-anyi** [comment]
你好 是如何使用chattts训练自己声音呢？ 换句话说就是 如何训练自己的chatTTS音色 :heart:

**Comment by Yeeler** [comment]
> 你好 是如何使用chattts训练自己声音呢？ 换句话说就是 如何训练自己的chatTTS音色 ❤️

I want to know as well. @kangyiwen Thanks for sharing your work.

**Comment by rijin89** [comment]
> > 各位如果有好的**英语音色**求分享
> 
> https://github.com/kangyiwen/TTSlist-En 有1000个英语音色，可以看看。

谢谢您，我进行了测试，英语它不会读字母或型号如GGG，RX7FC3S，AE86
GGG它读成GAG，然后其它的读错或省略了一些字母，看来英语还需要等更新的版本，哈哈

**Comment by kangyiwen** [comment]
嗯 英语感觉差点意思，等下个版本了。  现在TTS感觉已经很成熟了。

**Comment by kangyiwen** [comment]
今天开始生成 1~10000 音色的...
