### ISSUE TITLE
运行wavs = chat.infer(texts, use_decoder=True)出现以下错误

### ISSUE THREAD

**Issue by chappyhome** [2noise/ChatTTS#29]
ARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:decoder not initialized.

AssertionError                            Traceback (most recent call last)
[<ipython-input-10-8db0cbd920d8>](https://localhost:8080/#) in <cell line: 1>()
----> 1 wavs = chat.infer(texts, use_decoder=True)

[/usr/local/lib/python3.10/dist-packages/ChatTTS/core.py](https://localhost:8080/#) in infer(self, text, skip_refine_text, params_refine_text, params_infer_code, use_decoder)
     93 
     94     def infer(self, text, skip_refine_text=False, params_refine_text={}, params_infer_code={}, use_decoder=False):
---> 95         assert self.check_model(use_decoder=use_decoder)
     96         if not skip_refine_text:
     97             text_tokens = refine_text(self.pretrain_models, text, **params_refine_text)['ids']

**Comment by zou8944** [comment]
may be same as https://github.com/2noise/ChatTTS/issues/32

**Comment by yuehong136** [comment]
更新一下transformers库就解决了

**Comment by vivisol** [comment]
更新transformers库至4.41.2，并不能解决问题，依然报错：
```shell
(chatTTS) D:\AI\chatTTS>python untitled.py
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:dvae not initialized.
========texts========: ['今天天气不错，适合去钓鱼']
========chat.pretrain_models========: {}
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:decoder not initialized.
Traceback (most recent call last):
  File "D:\Learn\chatTTS\untitled.py", line 16, in <module>
    wavs = chat.infer(texts, use_decoder=True, )
  File "D:\ProgramData\miniconda3\envs\chatTTS\lib\site-packages\ChatTTS\core.py", line 95, in infer
    assert self.check_model(use_decoder=use_decoder)
AssertionError
```
通过debug发现，chat.pretrain_models是空的，没有被初始化

**Comment by Mrjackzxc** [comment]
where is tools.logger model?
