### ISSUE TITLE
README需要增加安装步骤

### ISSUE THREAD

**Issue by Bill-XU** [2noise/ChatTTS#290]
现在是从pip install ChatTTS的话，会安装比较老的版本，方法参数接口都和测试代码不一致。
必须先从git clone到本地，在本地引用使用。

还有sample代码里应该提示需要pip install pyaudiofile，否则 torchaudio 会报no backend错误。

**Comment by libukai** [comment]
可以看看这个库里的安装指南，[Awesome-ChatTTS](https://github.com/libukai/Awesome-ChatTTS)

![CleanShot 2024-06-08 at 11 28 34@2x](https://github.com/2noise/ChatTTS/assets/5654585/4f86649c-c8cc-43dc-9ec3-6690b2e6dfad)
