### ISSUE TITLE
请问大家是如何处理数字的

### ISSUE THREAD

**Issue by guiji101** [2noise/ChatTTS#292]
阿拉伯数字做inference的时候会出现乱码，例如下面一段话里的年份

> 从孔子（公元前`551`—前`479`年）起，周代的最后三个世纪出现了成体系的思辨思想，它主要体现在六七个思想学派中，但别的不容易归于任何学派的个别思想家也表现出这种思想

想请教一下这种问题通常是如何解决的。是否需要做预处理，把阿拉伯数字转换为对应汉字 （如 551 -> 五百五十一）？

**Comment by wangfeng35** [comment]
可以参考https://github.com/jianchang512/ChatTTS-ui或者https://github.com/CyberWon/ChatTTS-API/blob/api/api.md 做预处理
