### ISSUE TITLE
助词读音不对，"有效地"

### ISSUE THREAD

**Issue by zhuliwen** [2noise/ChatTTS#298]
中文助词，这里应该读成 "有效 de"
但是 ChatTTS 的结果会读成 "有效 di(第四声)"
希望可以修复这个问题。

**Comment by sekkit** [comment]
前端的问题，跟模型没关系吧

**Comment by zemelLeong** [comment]
多音字当然是替换成其他错别字来保证发音正确啦

**Comment by zhuliwen** [comment]
> 多音字当然是替换成其他错别字来保证发音正确啦

批量不太好操作

**Comment by panpan123456** [comment]
> 多音字当然是替换成其他错别字来保证发音正确啦

在文本大量生成的时候，这个是怎么操作的？
