### ISSUE TITLE
运行到一半就自动停止了

### ISSUE THREAD

**Issue by luosaidage** [2noise/ChatTTS#3]
![image](https://github.com/2noise/ChatTTS/assets/23243630/95f9abdc-e97c-4a01-a768-053581a12336)
如图，运行到一半就停止了。。
系统：linux
python版本：3.12
另外建议写个requirements吧

**Comment by moonnee** [comment]
> 已经找到问题了，这个其实是运行完了，只是在命令行下播不出来，用jupyter运行打开就好了

请问运行遇到 
File  ChatTTS/model/dvae.py
from vector_quantize_pytorch import GroupedResidualFSQ  
ModuleNotFoundError: No module named 'vector_quantize_pytorch'  
这个怎么解决呢？ 看起来似乎是模型文件缺失？
