### ISSUE TITLE
怎么去定制自己的音色？

### ISSUE THREAD

**Issue by Evelyn9192** [2noise/ChatTTS#307]

**Comment by Evelyn9192** [comment]
有没有其他小语种的

**Comment by tenadolanter** [comment]
录制自己的声音，根据这个声音生成音色，项目地址 [https://github.com/tenadolanter/chatTTS-timbre](https://github.com/tenadolanter/chatTTS-timbre)

**Comment by fumiama** [comment]
zero shot 已上线。
