### ISSUE TITLE
有没有考虑过采用类似encodec的结构呢

### ISSUE THREAD

**Issue by zhiqiuiyiye** [2noise/ChatTTS#309]
我理解的模型通过LLM获得离散的信息，然后通过DVAE decoder获得mel谱，再通过vocos还原音频，有没有考虑过直接将离散的信息换成类似encodec这样的结构呢，这样做会有什么弊端吗？

**Comment by haidog-yaqub** [comment]
那玩意token数量太多了

**Comment by pengzhendong** [comment]
https://mp.weixin.qq.com/s/RKSrystS53HN4C0POr6PYQ

> LLM 中语音 token 的解码应该是要走层次化或者多步的方法，先解码语义特征，再解码声学特征，或者是先解码 MEL，再加一个 HIFIGAN 这样的声码器。

**Comment by haidog-yaqub** [comment]
> https://mp.weixin.qq.com/s/RKSrystS53HN4C0POr6PYQ
> 
> > LLM 中语音 token 的解码应该是要走层次化或者多步的方法，先解码语义特征，再解码声学特征，或者是先解码 MEL，再加一个 HIFIGAN 这样的声码器。

不需要这种建模方式，只需要将waveform离散化（encodec）喂给transformer（valle）再接encodec重建waveform，或者将mel当成图片离散化喂给transformer（dalle，chatts）再接vocoder重建waveform。

**Comment by paulpaul91** [comment]
M

**Comment by wwfcnu** [comment]
> https://mp.weixin.qq.com/s/RKSrystS53HN4C0POr6PYQ
> 
> > LLM 中语音 token 的解码应该是要走层次化或者多步的方法，先解码语义特征，再解码声学特征，或者是先解码 MEL，再加一个 HIFIGAN 这样的声码器。

对应vall-e里，就是AR先解码语义特征，NAR后解码声学特征，层次化是这个意思吗

**Comment by UestcJay** [comment]
> encodec方案的token显著多于mel+vq+vocoder方案，而且需要修改transformer的训练方式，可以参考voicecraft、valle这些项目，mel+vq直接用image的方法即可。 只做speech的话，两种方案音质上其实差距不明显，encodec音质上限高一点。

请问chattts中 llm inference中这个inputs_ids是speech token吗？通过生成的speech token再去生成mel
` return {
                'ids': inputs_ids, 
                'attentions': attentions,
                'hiddens':hiddens,
            }`
