### ISSUE TITLE
写了一个chattts管理系统,有需求的可以看下

### ISSUE THREAD

**Issue by MaterialShadow** [2noise/ChatTTS#316]
[ChatTTS-manager](https://github.com/MaterialShadow/ChatTTS-manager)
- 支持音色保存
- 音色上传/下载
- 自定义音色
- 长文本音频合成

**Comment by libukai** [comment]
已经收录到 [libukai/Awesome-ChatTTS](https://github.com/libukai/Awesome-ChatTTS) 中
