### ISSUE TITLE
请问支持音色克隆吗

### ISSUE THREAD

**Issue by zheyuye** [2noise/ChatTTS#319]

**Comment by MichaelYang1995** [comment]
同上

**Comment by chrjxj** [comment]
+1

**Comment by tenadolanter** [comment]
录制自己的声音，根据这个声音生成音色，项目地址 [https://github.com/tenadolanter/chatTTS-timbre](https://github.com/tenadolanter/chatTTS-timbre)

**Comment by hello2mao** [comment]
+1

**Comment by smallkeyonce** [comment]
> 录制自己的声音，根据这个声音生成音色，项目地址 https://github.com/tenadolanter/chatTTS-timbre

用你这个项目生成的pt文件  推理报错啊

**Comment by v-yunbin** [comment]
> > 录制自己的声音，根据这个声音生成音色，项目地址 https://github.com/tenadolanter/chatTTS-timbre
> 
> 用你这个项目生成的pt文件 推理报错啊

确实用不了
