### ISSUE TITLE
同济子豪兄ChatTTS保姆级视频教程，草履虫都能学会

### ISSUE THREAD

**Issue by TommyZihao** [2noise/ChatTTS#324]
视频：https://www.bilibili.com/video/BV1Ui421v7JU
代码：https://github.com/TommyZihao/ChatTTS_Tutorials
同济子豪兄手把手带你部署开源语音合成神器ChatTTS
基础用法：在线网页Demo使用、安装配置环境、部署WebUI网页、Python代码控制一句话和多句话语音合成
进阶用法：导出和导入自定义音色、控制口语笑声停顿程度、自动生成语气词
大模型用法：接入零一万物、文心一言API做多轮对话

**Comment by libukai** [comment]
感谢推荐，已经放到 [libukai/Awesome-ChatTTS](https://github.com/libukai/Awesome-ChatTTS) 中置顶推荐
