### ISSUE TITLE
 unexpected keyword argument 'compile'

### ISSUE THREAD

**Issue by praveenarjun** [2noise/ChatTTS#326]
while using the code
 import ChatTTS
import torchaudio
import torch
from IPython.display import Audio

chat = ChatTTS.Chat()
chat.load_models(compile=False) # Set to True for better performance

texts = ["PUT YOUR TEXT HERE",]

wavs = chat.infer(texts, )

torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)
giving unexpected keyword argument compile what it mean

**Comment by l7492** [comment]
same problem here.
