### ISSUE TITLE
2000条说话人音色稳定性评估+男女年龄划分(实验)+在线试听+音色pt文件下载

### ISSUE THREAD

**Issue by 6drf21e** [2noise/ChatTTS#328]
2000条说话人音色稳定性评估+男女年龄划分(实验)+在线试听+音色pt文件下载

项目代码已开源

https://github.com/6drf21e/ChatTTS_Speaker

直接体验：

- 国内：https://modelscope.cn/studios/ttwwwaa/ChatTTS_Speaker
- 抱脸：https://huggingface.co/spaces/taa/ChatTTS_Speaker

![image](https://github.com/2noise/ChatTTS/assets/29720712/19dae45d-cc75-45e6-903a-a054db1494ed)

![image](https://github.com/2noise/ChatTTS/assets/29720712/93f85b4b-72ac-4e0b-b0f5-60347488bdd1)

**Comment by kangyiwen** [comment]
我生产了1万个音色  http://ttslist.aiqbh.com/10000cn/   

你V多少？ 请教下你怎么为音色打标签和分类。

**Comment by 6drf21e** [comment]
> 你V多少？ 请教下你怎么为音色打标签和分类。

标签是自己找了一些样本音色， 然后根据 https://modelscope.cn/models/iic/speech_eres2netv2_sv_zh-cn_16k-common/ 判断和目标音色的相似度。 男女准确度还行 其他差点

**Comment by libukai** [comment]
这个项目挺不错，已推荐

**Comment by fastfading** [comment]
多没有有， 能不能只挑出来几个有用比较有特色的音色。  
比如
萌妹
萝莉
御姐
老师
etc

**Comment by jin1258804025** [comment]
> 我生产了1万个音色 http://ttslist.aiqbh.com/10000cn/
> 
> 你V多少？ 请教下你怎么为音色打标签和分类。

请教下，怎么将wav文件转换为pt文件的？

**Comment by orderer0001** [comment]
请教大佬
音色很稳定，但是有一个问题，合成的语音，最开始总会出现一个sbdi的发音，这是为什么？试了几个seed pt都是这样。有解决办法吗？
