### ISSUE TITLE
音色库升级 10000个音色在线听！ 上次1000个后很多人加我希望更多，这次生产了1万个

### ISSUE THREAD

**Issue by kangyiwen** [2noise/ChatTTS#329]
上次1000个后很多人加我希望更多(https://github.com/2noise/ChatTTS/issues/281)，这次生产了1万个。

网址：http://ttslist.aiqbh.com/10000cn/

给个小Star鼓励下吧：https://github.com/kangyiwen/TTSlist/

**Comment by jianchang512** [comment]
提个建议，可以 提供个 音色 pt 或csv格式下载

**Comment by kangyiwen** [comment]
你打开网址，可以看到baidu网盘下载wav的。    PT csv里是想要参数吗？

**Comment by jianchang512** [comment]
一般人需要使用时不会想要wav的，需要的是音色值或csv或pt

**Comment by kangyiwen** [comment]
我还不熟悉，我理解下哦。  pt   csv 是在哪里用的？  你们是用哪个UI包的？   pt csv 可以自己放到UI里，直接选，是吗？

**Comment by jianchang512** [comment]
刷新下，看上面提供了csv生成代码。pt更简单 torch.save(spk,'xx.pt') 即可生成

是的，我的webui项目支持csv和pt直接使用

https://github.com/jianchang512/ChatTTS-ui

**Comment by kangyiwen** [comment]
哦！  大神，我就是用你这个批了生产的。   我学下

**Comment by robinspt** [comment]
> 一般人需要使用时不会想要wav的，需要的是音色值或csv或pt
> 
> 类似这个项目 https://github.com/6drf21e/ChatTTS_Speaker/tree/main 提供pt下载

大佬，下载的pt文件，在你的项目是直接导入/chatTTS-ui/speaker文件夹吗？

**Comment by jianchang512** [comment]
> > 一般人需要使用时不会想要wav的，需要的是音色值或csv或pt
> > 类似这个项目 https://github.com/6drf21e/ChatTTS_Speaker/tree/main 提供pt下载
> 
> 大佬，下载的pt文件，在你的项目是直接导入/chatTTS-ui/speaker文件夹吗？

放在这个文件夹里就行，升级到 0.92 版本

**Comment by tiny-andr** [comment]
> 一般人需要使用时不会想要wav的，需要的是音色值或csv或pt
> 
> 类似这个项目 https://github.com/6drf21e/ChatTTS_Speaker/tree/main 提供pt下载

https://github.com/6drf21e/ChatTTS_Speaker/tree/main
这里面的文件[evaluation_results.csv](https://github.com/6drf21e/ChatTTS_Speaker)文件是没法在[ChatTTS_colab](https://github.com/6drf21e/ChatTTS_colab)项目中用么  不知道该放在哪个文件夹。。
