### ISSUE TITLE
不能正常朗读吗，非口语化的语言，它也会有很多语气和断句

### ISSUE THREAD

**Issue by zx-lhb** [2noise/ChatTTS#331]
朗读古文还是不行，我用关关雎鸠，在河之洲，窈窕淑女，君子好逑在原版代码上测试了一下，读的很奇怪

**Comment by zx-lhb** [comment]
[output01.zip](https://github.com/user-attachments/files/15864245/output01.zip)

**Comment by lixikun** [comment]
这个去掉 跳过 refine text 的步骤，听起来还可以。

**Comment by zengxushen** [comment]
> [output01.zip](https://github.com/user-attachments/files/15864245/output01.zip)

你这个简直不能听啊 。。。调一下temp参数吧，别那么大。试试

**Comment by panpan123456** [comment]
所以上面的506507要如何实现他不加入额外的话

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Comment by zx-lhb** [comment]
> 所以上面的506507要如何实现他不加入额外的话

应该是还没实现这个功能，目前朗读就是会有很多其他语气词
