### ISSUE TITLE
在海量音频中寻找相似音色的可能

### ISSUE THREAD

**Issue by cronrpc** [2noise/ChatTTS#332]
理论上如果生成的音色范围足够广，大多数音频有办法找到相似的音色。

https://github.com/cronrpc/Audio-Speaker-Needle-In-Haystack

这里用的3ds-speaker的音频embs，可能扩充到一万人到五万人会产生质变，并且文本需要选择一个尽可能相似的。

Huggingface Sapce: https://huggingface.co/spaces/omniway/Audio-Needle-In-Haystack

![image](https://github.com/2noise/ChatTTS/assets/147160173/b987e0ac-5603-4956-95db-30eca20bb98b)

**Comment by skysbird** [comment]
你是想做zeroshot么？

**Comment by chrjxj** [comment]
1. 随机生成足够多的音频，保持音色的配置文件和emb
2. 录制自己的声音，用自己的音频搜索出相近的音频以及对应的音色配置
3. 用对应的音色配置，去"clone"(近似)自己的音色

**Comment by tenadolanter** [comment]
录制自己的声音，根据这个声音生成音色，项目地址 [https://github.com/tenadolanter/chatTTS-timbre](https://github.com/tenadolanter/chatTTS-timbre)

**Comment by limujun** [comment]
> 录制自己的声音，根据这个声音生成音色，项目地址 https://github.com/tenadolanter/chatTTS-timbre

你这个生成的是torch.Size([1, 36])和chattts 的维度不一样

**Comment by tenadolanter** [comment]
> > 录制自己的声音，根据这个声音生成音色，项目地址 https://github.com/tenadolanter/chatTTS-timbre
> 
> 你这个生成的是torch.Size([1, 36])和chattts 的维度不一样

欢迎pr
