### ISSUE TITLE
关于固定音色，ChatTTS_Speaker这个项目真不错 

### ISSUE THREAD

**Issue by wangtao911** [2noise/ChatTTS#339]
关于固定音色，我也是一直听头疼的，但今天发现了这个项目，真不错 👍

https://huggingface.co/spaces/taa/ChatTTS_Speaker

https://modelscope.cn/studios/ttwwwaa/ChatTTS_Speaker/summary

**Comment by 6drf21e** [comment]
🙋‍感谢推荐！
请问稳定rank高的音色实际使用的时候稳定性如何？
评估的样本还是有局限性。

**Comment by orderer0001** [comment]
> 关于固定音色，我也是一直听头疼的，但今天发现了这个项目，真不错 👍
> 
> https://huggingface.co/spaces/taa/ChatTTS_Speaker
> 
> https://modelscope.cn/studios/ttwwwaa/ChatTTS_Speaker/summary

音色很稳定，但是有一个问题，合成的语音，最开始总会出现一个sbdi的发音，这是为什么？试了几个seed pt都是这样。有解决办法吗？
