### ISSUE TITLE
根据参考音频克隆音色的模型，欢迎试用 Voice Clone

### ISSUE THREAD

**Issue by hoveychen** [2noise/ChatTTS#369]
训练了几个克隆声音的模型，可以根据参考音频生成ChatTTS使用的音色嵌入。

模型Demo页面：
http://region-9.autodl.pro:41137

欢迎大家反馈一下测试效果，加入QQ群474529811给建议或者讨论。

-----
用法：下载声音模型（.pt结尾），记住temperature要设置得非常低，否则声音会不准确。
`
rand_spk = torch.load(f'my_speaker.pt')

params_infer_code = {
  'spk_emb': rand_spk, # add sampled speaker 
  'temperature': .000001, # using custom temperature
}

texts = ['hello world', '你好呀，旅行者！']

wavs = chat.infer(texts, params_infer_code=params_infer_code)
`

**Comment by 6drf21e** [comment]
效果不错👍

**Comment by redstoneleo** [comment]
QQ群搜不到啊

**Comment by ZaymeShaw** [comment]
用自己的声音简短录了两句话测试，用噪声比较少的声音做克隆时能拷贝一个接近的音色出来，多句话之间的音色一致性也比较高，不过生成声音似乎有比较多噪声，音色也不是完全一样

**Comment by wangqun888** [comment]
请问一下克隆模型可以在哪里下载？

**Comment by hello2mao** [comment]
+1
求一个本地部署和使用的方式。

**Comment by yiwei0730** [comment]
想請問使用方式還有程式的部分
想了解提取.pt是如何執行的，謝謝!

**Comment by atfa** [comment]
> 训练了几个克隆声音的模型，可以根据参考音频生成ChatTTS使用的音色嵌入。
> 
> 模型Demo页面： http://region-9.autodl.pro:41137
> 
> 欢迎大家反馈一下测试效果，加入QQ群474529811给建议或者讨论。
> 
> 用法：下载声音模型（.pt结尾），记住temperature要设置得非常低，否则声音会不准确。 ` rand_spk = torch.load(f'my_speaker.pt')
> 
> params_infer_code = { 'spk_emb': rand_spk, # add sampled speaker 'temperature': .000001, # using custom temperature }
> 
> texts = ['hello world', '你好呀，旅行者！']
> 
> wavs = chat.infer(texts, params_infer_code=params_infer_code) `

感谢，用自己的声音测试了，没想到用纯中文训练的spk用在中英混杂场景异常好用，比用中英混杂的录音训练出来的spk还好用。还希望未来能开源，感激不尽。

**Comment by 954028118** [comment]
会开源吗，期待开源

**Comment by Yitianw** [comment]
474529811 群满了 请问有新群吗

**Comment by ChenadSH** [comment]
> 训练了几个克隆声音的模型，可以根据参考音频生成ChatTTS使用的音色嵌入。
> 
> 模型Demo页面： http://region-9.autodl.pro:41137
> 
> 欢迎大家反馈一下测试效果，加入QQ群474529811给建议或者讨论。
> 
> 用法：下载声音模型（.pt结尾），记住temperature要设置得非常低，否则声音会不准确。 ` rand_spk = torch.load(f'my_speaker.pt')
> 
> params_infer_code = { 'spk_emb': rand_spk, # add sampled speaker 'temperature': .000001, # using custom temperature }
> 
> texts = ['hello world', '你好呀，旅行者！']
> 
> wavs = chat.infer(texts, params_infer_code=params_infer_code) `

网站为什么打不开了？
