### ISSUE TITLE
May I ask how to fix the voice color？

### ISSUE THREAD

**Issue by wangwenjie1314** [2noise/ChatTTS#375]
rt：May I ask how to fix the voice color？
请问：如何固定音色，或者有没有ChatTTS增强版的autodl镜像

**Comment by wangwenjie1314** [comment]
我找到一个增强版的解决了我的需求：https://github.com/6drf21e/ChatTTS_colab
可以云部署，我喜欢

**Comment by neverbiasu** [comment]
#272 is what u need
