### ISSUE TITLE
Load models KeyError

### ISSUE THREAD

**Issue by Ding-jinyu** [2noise/ChatTTS#378]
<img width="977" alt="image" src="https://github.com/2noise/ChatTTS/assets/73097207/1a1bcb4d-d905-408d-bd28-bd3c7cc350db">
如图，一直有KeyError的报错，怎么解决呀？
这个问题昨天还没有 :(

**Comment by jianchang512** [comment]
目录下的sha256.env重名为 .env 试试

**Comment by mkyuangithub** [comment]
from dotenv import load_dotenv
chat.load_models(source='custom',custom_path='D:/cursor_space/python/ChatTTS') 

can solve ur probs

**Comment by Ding-jinyu** [comment]
> from dotenv import load_dotenv chat.load_models(source='custom',custom_path='D:/cursor_space/python/ChatTTS')
> 
> can solve ur probs

Thanks! I fixed it

**Comment by Ding-jinyu** [comment]
> 目录下的sha256.env重名为 .env 试试
> 
> 如果还是报错 再将下面代码加到你文件代码中再执行
> 
> ```
> from dotenv import load_dotenv
> load_dotenv()
> ```
> 
> 若是新出现 module dotenv not found 错误 就安装下模块 pip install python-dotenv

谢谢，有用！
