### ISSUE TITLE
有关笑声生成的问题

### ISSUE THREAD

**Issue by ZYJGO** [2noise/ChatTTS#395]
请问一下如何能保证笑声的出现呢，在生成英语的时候几乎总是读出来laugh这个单词，或者直接无视掉。是不是将[laugh]放在某些特定的单词前会增加概率呢

**Comment by Eric-Zhong** [comment]
> 请问一下如何能保证笑声的出现呢，在生成英语的时候几乎总是读出来laugh这个单词，或者直接无视掉。是不是将[laugh]放在某些特定的单词前会增加概率呢

Instead of using the default WebUI, you should try using code programming with prompt parametrrs, it is in the example code.
