### ISSUE TITLE
git pull之后，提示安装依赖pynini WeTextProcessing nemo_text_processing失败，求助

### ISSUE THREAD

**Issue by zengxushen** [2noise/ChatTTS#396]
![image](https://github.com/2noise/ChatTTS/assets/137095237/a7999608-c792-46c5-90f7-f1023838e5ec)

**Comment by fumiama** [comment]
可使用conda安装，也可前往`requirements.txt`删除最后三行：
```
pynini==2.1.5
WeTextProcessing
nemo_text_processing
```
