### ISSUE TITLE
一旦使用固定音色spk_emb，生成的内容前后就会有短暂的胡言乱语Once the fixed tone spk_emb is used, the generated content will have brief nonsense before and after

### ISSUE THREAD

**Issue by orderer0001** [2noise/ChatTTS#404]
Once the fixed tone spk_emb is used, the generated content will have brief nonsense before and after，Can this problem be solved?
After loading the spk_emb fixed timbre, there are always some redundant sounds in front of the synthesized sound.
一旦使用固定音spk_emb，生成的内容前后会有简短的废话，这个问题能解决吗？
就是加载spk_emb固定音色后，合成声音前面总是有一些多余的声音。

**Comment by zhangkanghao** [comment]
同问，还有可能有打断省略没生成出来

**Comment by Coefu** [comment]
我也遇到了，有解决方案了吗？
