### ISSUE TITLE
【Bug】文本中如果有数字和中文混合的内容数字不能正确的合成

### ISSUE THREAD

**Issue by guozanhua218** [2noise/ChatTTS#412]
如标题所述

**Comment by fumiama** [comment]
请尝试正确安装`WeTextProcessing`包，该包就是为了解决此问题。当然更好的办法还是让模型支持数字。

**Comment by jianchang512** [comment]
中文的数字处理可以考虑使用百度的PaddlePaddle text normlization代码

目前集成的wetext只可conda下才能安装，兼容性不好

**Comment by fumiama** [comment]
考虑将normlization做成接口，库中不再包含任一实现。
