### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by anthonyyuan** [2noise/ChatTTS#42]
import torch
std, mean = torch.load('ChatTTS/asset/spk_stat.pt').chunk(2)
rand_spk = torch.randn(768) * std + mean

params_infer_code = {
  'spk_emb': rand_spk, # add sampled speaker 
  'temperature': .3, # using custom temperature
  'top_P': 0.7, # top P decode
  'top_K': 20, # top K decode
}

**Comment by iqiancheng** [comment]
Here is the solution:  
```python
import torch
from huggingface_hub import hf_hub_download

# Download and load the model
repo_id = "2Noise/ChatTTS"
filename = "asset/spk_stat.pt"
local_path = hf_hub_download(repo_id=repo_id, filename=filename)
std, mean = torch.load(local_path).chunk(2)

# Generate a random speaker embedding
rand_spk = torch.randn(768) * std + mean

# Set inference parameters
params_infer_code = {
    'spk_emb': rand_spk,  # Add sampled speaker embedding
    'temperature': .3,    # Use custom temperature
    'top_P': 0.7,         # Top P decoding
    'top_K': 20,          # Top K decoding
}

```

**Comment by BrightGu** [comment]
麻烦看一下huggingface_hub的版本，谢谢~我的一直报错ImportError: cannot import name 'hf_hub_download' from 'huggingface_hub'？

**Comment by firLucky** [comment]
同问，cpu不会报错，安装cuda就会出现该问题
