### ISSUE TITLE
出现未定义字符后 语气推导的text的 tag 会丢失[]

### ISSUE THREAD

**Issue by asamaayako** [2noise/ChatTTS#424]
当出现如 我传入了一个问号  WARNING:ChatTTS.core:Invalid characters found! : {'？'}
wabui 输入用例
```
四川美食确实以辣闻名，但也有不辣的选择。比如甜水面、赖汤圆、蛋烘糕、叶儿粑等，这些小吃口味温和，甜而不腻，也很受欢迎？
```
输出结果
```
四 川 美 食 确 实 以 辣 闻 名 ， 但 也 有 不 辣 的 选 择 ,uv_break, 。 比 如 甜 水 面 、 赖 汤 圆 、 蛋 烘 糕 、 叶 粑 等 ， 这 些 小 吃 口 味 温 和 ， 甜 而 不 腻 ,uv_break, ， 也 很 受 欢 迎 吗 ,uv_break, ？
```
同时语音也会将uv_break以英文的方式读出来

**Comment by AIyumeng** [comment]
看这个仓库[https://github.com/libukai/Awesome-ChatTTS](https://github.com/libukai/Awesome-ChatTTS)

修改 ChatTTS/utils/infer_utils.py 中的代码，在 103 行的 character_map 的字典中添加缺失的标点符号。

**Comment by zhangkanghao** [comment]
> 看这个仓库https://github.com/libukai/Awesome-ChatTTS
> 
> 修改 ChatTTS/utils/infer_utils.py 中的代码，在 103 行的 character_map 的字典中添加缺失的标点符号。

没有 ChatTTS/utils/infer_utils.py 啊

**Comment by jasonchanhku** [comment]
现在是不是在 `utils/ChatTTS/norm.py` 改一改?

<img width="368" alt="image" src="https://github.com/2noise/ChatTTS/assets/20807220/fbc1bdef-15b1-410e-bd34-dfe89f8652e2">
