### ISSUE TITLE
How to make the voice sounding the same?

### ISSUE THREAD

**Issue by Vishalmshekhar** [2noise/ChatTTS#435]
How to make the voice sound the same? 
Is there at least a way to manually invoke male and female voices or is it always random?

**Comment by humpydonkey** [comment]
+1, I have the same question.
i think this is a foundational feature to many ChatTTS users for production usage. It'd be helpful to document the answer in a doc.

**Comment by humpydonkey** [comment]
read here: https://github.com/2noise/ChatTTS?tab=readme-ov-file#advanced
