### ISSUE TITLE
generate_audio函数返回和API文档中的不一致

### ISSUE THREAD

**Issue by DExpress-dev** [2noise/ChatTTS#448]
从API文档中看到generate_audio函数返回的数据为：
Returns tuple of 2 elements
[0] filepath
The output value that appears in the "Output Audio" Audio component.
[1] str
The output value that appears in the "Output Text" Textbox component.
但是实际上返回的却是类似：
{"event_id":"ebe68074e43b44fea4abc3a226004f12"}

那么依哪个为准呢？

**Comment by DExpress-dev** [comment]
那现在是无法使用API接口来使用ChatTTS功能的是么？

**Comment by fumiama** [comment]
🈚️
