### ISSUE TITLE
ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations

### ISSUE THREAD

**Issue by neverbiasu** [2noise/ChatTTS#46]
# ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations'

## Problem Description

While trying to import the `ChatTTS` package, I encountered the following error:

ImportError                               Traceback (most recent call last)
Cell In[4], line 2
      1 import torch
----> 2 import ChatTTS
      3 from IPython.display import Audio

File ~/ChatTTS/ChatTTS/__init__.py:1
----> 1 from .core import Chat

File ~/ChatTTS/ChatTTS/core.py:9
      7 from vocos import Vocos
      8 from .model.dvae import DVAE
----> 9 from .model.gpt import GPT_warpper
     10 from .utils.gpu_utils import select_device
     11 from .utils.io_utils import get_latest_modified_file

File ~/ChatTTS/ChatTTS/model/gpt.py:13
     11 import torch.nn.functional as F
     12 import torch.nn.utils.parametrize as P
---> 13 from torch.nn.utils.parametrizations import weight_norm
     14 from transformers import LlamaModel, LlamaConfig
     17 class LlamaMLP(nn.Module):

ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations' (/root/miniconda3/lib/python3.8/site-packages/torch/nn/utils/parametrizations.py)

## Cause Analysis

This error is caused by changes in the PyTorch version. In newer versions of PyTorch, the `weight_norm` function has been removed from the `torch.nn.utils.parametrizations` module.

## Possible Solutions

1. **Use an older version of PyTorch**
   If your code depends on an older version of PyTorch, you can try installing an older version, such as 1.11 or earlier, as the `weight_norm` function still exists in those versions.

2. **Use `torch.nn.utils.weight_norm`**
   In newer versions of PyTorch, the `weight_norm` function has been moved to the `torch.nn.utils.weight_norm` module. Therefore, you can replace:

   ```python
   from torch.nn.utils.parametrizations import weight_norm
   ```

   with:

   ```python
   from torch.nn.utils import weight_norm
   ```

3. **Use `torch.nn.utils.parametrize.weight_norm`**
   Alternatively, you can also use `torch.nn.utils.parametrize.weight_norm` instead:

   ```python
   from torch.nn.utils.parametrize import weight_norm
   ```

## Environment Information

- Python version: 3.8.10
- PyTorch version: 2.0.1
- ChatTTS version: latest

**Comment by GarrickLin** [comment]
I tried `torch.nn.utils.parametrize.weight_norm` but not working:
```
Traceback (most recent call last):
  File "/Users/garrick/workspace/python/ChatTTS/test1.py", line 1, in <module>
    import ChatTTS
  File "/Users/garrick/workspace/python/ChatTTS/ChatTTS/__init__.py", line 1, in <module>
    from .core import Chat
  File "/Users/garrick/workspace/python/ChatTTS/ChatTTS/core.py", line 9, in <module>
    from .model.gpt import GPT_warpper
  File "/Users/garrick/workspace/python/ChatTTS/ChatTTS/model/gpt.py", line 17, in <module>
    from torch.nn.utils.parametrize import weight_norm
ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrize' (/Users/garrick/anaconda3/lib/python3.9/site-packages/torch/nn/utils/parametrize.py)
```

**Comment by xiaomingnio** [comment]
pytorch 2.1.0 is ok.
