### ISSUE TITLE
方言化了？

### ISSUE THREAD

**Issue by ucasiggcas** [2noise/ChatTTS#468]
输入：家人们，举报了，庄国栋就是个渣男，渣男！！！
输出：家 人 们 ， 然 后 就 [uv_break] 举 报 了 ， 然 后 就 是 庄 国 栋 就 是 个 渣 男 ， 就 是 渣 男 [uv_break] 。 就 。 [uv_break] 。
<img width="1259" alt="image" src="https://github.com/2noise/ChatTTS/assets/35590066/42eefe56-31d9-4994-99b4-a00f4260bb1e">

**Comment by fumiama** [comment]
可以取消勾选refine text，把output直接复制到input，删去多余的部分重新推理。

**Comment by ucasiggcas** [comment]
老铁，uv_break都读出来了，

你 没 事 吧 ， 早 上 没 吃 药 还 是 患 病 了 吗 [uv_break] ？ 用 得 着 你 [uv_break] 说 三 道 四 ， 指 指 点 点 [uv_break] ， 有 病 [laugh] 赶 紧 治 吧 ， 别 [uv_break] 拖 着 呢 [uv_break] 。
原输入：你没事吧，早上没吃药还是患病了？用得着你说三道四，指指点点，有病赶紧治，别拖着！
[audio (1).mp3.zip](https://github.com/user-attachments/files/16006586/audio.1.mp3.zip)

**Comment by Vishalmshekhar** [comment]
我也有同样的问题
