### ISSUE TITLE
推理的时候A100比cpu慢十倍不止，求助怎么解

### ISSUE THREAD

**Issue by panpan123456** [2noise/ChatTTS#476]
python3 example/cmd/run.py "hjkshfksd"
机器A100，速度超慢

**Comment by fumiama** [comment]
因为默认是开启编译的，虽然第一次推理慢，但是多次推理的时候比不编译要快大概一倍。

**Comment by peakDay** [comment]
> 因为默认是开启编译的，虽然第一次推理慢，但是多次推理的时候比不编译要快大约一倍。

只求第一次推理速度要快。怎么解决了？

**Comment by zhuyetuo** [comment]
好像每次运行都要重新编译
