### ISSUE TITLE
"Compile” doesn't work on GPU

### ISSUE THREAD

**Issue by encorechow** [2noise/ChatTTS#479]
pytorch version: 2.3.1+cu121

I've tried to use `compile=True` in `load` function, it is super slow to generate results, and I didn't see any GPU utilizition with `nvidia-smi` like below (a liitle memory ocuupied like 1GB):
![企业微信截图_17194899582803](https://github.com/2noise/ChatTTS/assets/9158462/0a10755f-b254-4b28-9c95-5c58f69db372)

after I commented out the code block below, GPU utilization turns normal, and result is generated much much faster:
![企业微信截图_17194900322602](https://github.com/2noise/ChatTTS/assets/9158462/d023b00f-bf35-4427-8b8e-d51e1d288f6e)
![企业微信截图_17194900872413](https://github.com/2noise/ChatTTS/assets/9158462/6284a604-821a-4f83-96f5-37a383ce6b3e)

I cant understand why the torch.compile function didn't work well. Does anyone know why?

**Comment by fumiama** [comment]
The compile only shows its effect when you run a generating process continuously with the same input shape. If you only run it once, it will slow down the generation.
