### ISSUE TITLE
AttributeError: 'Chat' object has no attribute 'load'

### ISSUE THREAD

**Issue by xgocn** [2noise/ChatTTS#490]
Traceback (most recent call last):
  File "D:\AI\ChatTTS\examples\test\simple.py", line 6, in <module>
    chat.load(compile=False) # Set to True for better performance
    ^^^^^^^^^
AttributeError: 'Chat' object has no attribute 'load'

**Comment by xgocn** [comment]
the code is ：
`import ChatTTS
import torch
import torchaudio

chat = ChatTTS.Chat()
chat.load(compile=False) # Set to True for better performance

texts = ["PUT YOUR 1st TEXT HERE", "PUT YOUR 2nd TEXT HERE"]

wavs = chat.infer(texts)

torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)`

**Comment by fumiama** [comment]
Please use latest version of ChatTTS.

**Comment by xgocn** [comment]
(base) D:\AI>git clone https://github.com/2noise/ChatTTS.git
Cloning into 'ChatTTS'...
remote: Enumerating objects: 1113, done.
remote: Counting objects: 100% (643/643), done.
remote: Compressing objects: 100% (322/322), done.
remote: Total 1113 (delta 431), reused 443 (delta 300), pack-reused 470
Receiving objects: 100% (1113/1113), 7.09 MiB | 699.00 KiB/s, done.
Resolving deltas: 100% (593/593), done.

(base) D:\AI>cd chattts

(base) D:\AI\ChatTTS>python examples/web/webui.py
Traceback (most recent call last):
  File "D:\AI\ChatTTS\examples\web\webui.py", line 13, in <module>
    from examples.web.funcs import *
  File "D:\AI\ChatTTS\examples\web\funcs.py", line 19, in <module>
    chat = ChatTTS.Chat(get_logger("ChatTTS"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chat.__init__() takes 1 positional argument but 2 were given

**Comment by fumiama** [comment]
Have you ever installed ChatTTS? If true, use `pip uninstall ChatTTS` to uninstall it first.

**Comment by xgocn** [comment]
(base) D:\AI\ChatTTS>pip uninstall ChatTTS
WARNING: Skipping ChatTTS as it is not installed.

(base) D:\AI\ChatTTS>pip install ChatTTS
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting ChatTTS
  Using cached ChatTTS-0.0.5-py3-none-any.whl
Requirement already satisfied: torch>=2.0.0 in d:\conda3\lib\site-packages (from ChatTTS) (2.3.1)
Requirement already satisfied: filelock in d:\conda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\conda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (4.12.2)
Requirement already satisfied: sympy in d:\conda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (1.12)
Requirement already satisfied: networkx in d:\conda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (3.1)
Requirement already satisfied: jinja2 in d:\conda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (3.1.3)
Requirement already satisfied: fsspec in f:\roaming\python\python311\site-packages (from torch>=2.0.0->ChatTTS) (2023.10.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in d:\conda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (2021.4.0)
Requirement already satisfied: intel-openmp==2021.* in d:\conda3\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=2.0.0->ChatTTS) (2021.4.0)
Requirement already satisfied: tbb==2021.* in d:\conda3\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=2.0.0->ChatTTS) (2021.12.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\conda3\lib\site-packages (from jinja2->torch>=2.0.0->ChatTTS) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\conda3\lib\site-packages (from sympy->torch>=2.0.0->ChatTTS) (1.3.0)
Installing collected packages: ChatTTS
Successfully installed ChatTTS-0.0.5

(base) D:\AI\ChatTTS>python examples/web/webui.py
Traceback (most recent call last):
  File "D:\AI\ChatTTS\examples\web\webui.py", line 13, in <module>
    from examples.web.funcs import *
  File "D:\AI\ChatTTS\examples\web\funcs.py", line 19, in <module>
    chat = ChatTTS.Chat(get_logger("ChatTTS"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chat.__init__() takes 1 positional argument but 2 were given

**Comment by xgocn** [comment]
I repeated this workflow in a new host，the error message is the same

**Comment by xgocn** [comment]
(base) E:\>pip uninstall ChatTTS
WARNING: Skipping ChatTTS as it is not installed.

(base) E:\>pip install ChatTTS
Collecting ChatTTS
  Downloading ChatTTS-0.0.5.tar.gz (9.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=2.0.0 in d:\anaconda3\lib\site-packages (from ChatTTS) (2.3.1+cu121)
Requirement already satisfied: filelock in d:\anaconda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\anaconda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (4.9.0)
Requirement already satisfied: sympy in d:\anaconda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (1.12)
Requirement already satisfied: networkx in d:\anaconda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (3.1)
Requirement already satisfied: jinja2 in d:\anaconda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (3.1.3)
Requirement already satisfied: fsspec in d:\anaconda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (2023.10.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in d:\anaconda3\lib\site-packages (from torch>=2.0.0->ChatTTS) (2021.4.0)
Requirement already satisfied: intel-openmp==2021.* in d:\anaconda3\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=2.0.0->ChatTTS) (2021.4.0)
Requirement already satisfied: tbb==2021.* in d:\anaconda3\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=2.0.0->ChatTTS) (2021.12.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda3\lib\site-packages (from jinja2->torch>=2.0.0->ChatTTS) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\anaconda3\lib\site-packages (from sympy->torch>=2.0.0->ChatTTS) (1.3.0)
Building wheels for collected packages: ChatTTS
  Building wheel for ChatTTS (setup.py) ... done
  Created wheel for ChatTTS: filename=ChatTTS-0.0.5-py3-none-any.whl size=11797 sha256=8d8208d9a9b631dc05efb1a8caf49aeb7d85cab9b151a65c3323bf5b90962c75
  Stored in directory: c:\users\xgocn\appdata\local\pip\cache\wheels\cc\d6\4e\c785faabf80f3958cabb4ac93648d4b3025b0b7271f023421f
Successfully built ChatTTS
Installing collected packages: ChatTTS
Successfully installed ChatTTS-0.0.5

(base) E:\tts>python examples/web/webui.py
Traceback (most recent call last):
  File "E:\tts\examples\web\webui.py", line 13, in <module>
    from examples.web.funcs import *
  File "E:\tts\examples\web\funcs.py", line 19, in <module>
    chat = ChatTTS.Chat(get_logger("ChatTTS"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chat.__init__() takes 1 positional argument but 2 were given

**Comment by fumiama** [comment]
No pip install ChatTTS. PyPI is currently WIP. Please read the REDAME.

**Comment by xgocn** [comment]
thx，resolved

**Comment by AliArfa852** [comment]
just try
print(dir(chat))
and check what you can use
it can be load or load_model depending on version
