### ISSUE TITLE
文本里面的阿拉伯数字好像识别不了

### ISSUE THREAD

**Issue by soone** [2noise/ChatTTS#50]
我使用的ipyn里面的例子进行生成的，只是生成使用的文本换成了“这个可以啊，，但是你价格5.2美金打不下来吧”这个，然后发现里面的5.2无法正常的发音

**Comment by 1044690543** [comment]
> 我使用的ipyn里面的例子进行生成的，只是生成使用的文本换成了“这个可以啊，，但是你价格5.2美金打不下来吧”这个，然后发现里面的5.2无法正常的发音

需要自己把阿拉伯数字转正汉字
