### ISSUE TITLE
Get error in WSL2 with CUDA

### ISSUE THREAD

**Issue by cnjack** [2noise/ChatTTS#51]
```python
import torch
import ChatTTS
from IPython.display import Audio

chat = ChatTTS.Chat()
chat.load_models()

texts = ["你好啊,我是你的智能助手",]

wavs = chat.infer(texts, use_decoder=True)

Audio(wavs[0], rate=24_000, autoplay=True)
```
get the error:
```
python app.py
INFO:ChatTTS.core:Load from cache: /root/.cache/huggingface/hub/models--2Noise--ChatTTS/snapshots/c0aa9139945a4d7bb1c84f07785db576f2bb1bfa
INFO:ChatTTS.core:use cuda:0
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
INFO:ChatTTS.core:All initialized.
  5%|███████▋                                                                                                                                                    | 19/384 [00:00<00:11, 31.67it/s]
  8%|███████████▉                                                                                                                                              | 158/2048 [00:02<00:24, 75.72it/s]
/root/anaconda3/envs/chatts/lib/python3.11/site-packages/torch/nn/modules/conv.py:306: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv1d(input, weight, bias, self.stride,
```

**Comment by iorzt** [comment]
seems related? could you try?
https://github.com/pytorch/pytorch/issues/121834

**Comment by gaohaozhang** [comment]
> ```python
> import torch
> import ChatTTS
> from IPython.display import Audio
> 
> chat = ChatTTS.Chat()
> chat.load_models()
> 
> texts = ["你好啊,我是你的智能助手",]
> 
> wavs = chat.infer(texts, use_decoder=True)
> 
> Audio(wavs[0], rate=24_000, autoplay=True)
> ```
> 
> get the error:
> 
> ```
> python app.py
> INFO:ChatTTS.core:Load from cache: /root/.cache/huggingface/hub/models--2Noise--ChatTTS/snapshots/c0aa9139945a4d7bb1c84f07785db576f2bb1bfa
> INFO:ChatTTS.core:use cuda:0
> INFO:ChatTTS.core:vocos loaded.
> INFO:ChatTTS.core:dvae loaded.
> INFO:ChatTTS.core:gpt loaded.
> INFO:ChatTTS.core:decoder loaded.
> INFO:ChatTTS.core:tokenizer loaded.
> INFO:ChatTTS.core:All initialized.
> INFO:ChatTTS.core:All initialized.
>   5%|███████▋                                                                                                                                                    | 19/384 [00:00<00:11, 31.67it/s]
>   8%|███████████▉                                                                                                                                              | 158/2048 [00:02<00:24, 75.72it/s]
> /root/anaconda3/envs/chatts/lib/python3.11/site-packages/torch/nn/modules/conv.py:306: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
>   return F.conv1d(input, weight, bias, self.stride,
> ```

你好，请问您这个问题解决了吗
