### ISSUE TITLE
 'tools.logger' model not found

### ISSUE THREAD

**Issue by Mrjackzxc** [2noise/ChatTTS#515]
i get error "ModuleNotFoundError: No module named 'tools.logger'" when i run example.ipynb ,how can i get 'tools.logger'  model ?

**Comment by fumiama** [comment]
Check your root dir. If you can, please put your notebook output to let us know the detail.

**Comment by ahmedoubadi** [comment]
same problem:
File "D:\projects\ai-agents\ChatTTS\examples\cmd\run.py", line 10, in <module>
    from tools.logger import get_logger
ModuleNotFoundError: No module named 'tools.logger'

**Comment by fumiama** [comment]
> same problem: File "D:\projects\ai-agents\ChatTTS\examples\cmd\run.py", line 10, in from tools.logger import get_logger ModuleNotFoundError: No module named 'tools.logger'

replace
```py
from tools.logger import get_logger
```
with
```py
from ChatTTS.tools.logger import get_logger
```
and use the latest `dev` branch according to #603
