### ISSUE TITLE
pip install "ChatTTS>=0.1.0" failed

### ISSUE THREAD

**Issue by codingl2k1** [2noise/ChatTTS#517]
Collecting ChatTTS>=0.1.0
  Using cached chattts-0.1.0.tar.gz (114 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Requested ChatTTS>=0.1.0 from https://files.pythonhosted.org/packages/73/39/5e39c12213ffa2468586b00224e2279436bd7e2d3836d51b3b70862b19ca/chattts-0.1.0.tar.gz, but installing version 0.0.0
Discarding https://files.pythonhosted.org/packages/73/39/5e39c12213ffa2468586b00224e2279436bd7e2d3836d51b3b70862b19ca/chattts-0.1.0.tar.gz (from https://pypi.org/simple/chattts/): Requested ChatTTS>=0.1.0 from https://files.pythonhosted.org/packages/73/39/5e39c12213ffa2468586b00224e2279436bd7e2d3836d51b3b70862b19ca/chattts-0.1.0.tar.gz has inconsistent version: expected '0.1.0', but metadata has '0.0.0'

**Comment by fumiama** [comment]
Will fix soon.

**Comment by fumiama** [comment]
`v0.1.1` released. Please have a try.
