### ISSUE TITLE
求助大佬们，ChatTTS库已经安装，但是运行后找不到sample_random_speaker()此方法

### ISSUE THREAD

**Issue by kustcl** [2noise/ChatTTS#518]
rand_spk = chat.sample_random_speaker()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Chat' object has no attribute 'sample_random_speaker'

**Comment by gyy028lucky** [comment]
File "/usr/local/lib/python3.8/dist-packages/ChatTTS/core.py", line 182, in _sample_random_speaker
    dim: int = self.gpt.gpt.layers[0].mlp.gate_proj.in_features
AttributeError: 'Chat' object has no attribute 'gpt'
