### ISSUE TITLE
如何流式生成编码的音频字节流？

### ISSUE THREAD

**Issue by codingl2k1** [2noise/ChatTTS#529]
目前的 demo 使用 pyaudio 播放的，可以直接流式 infer 结果转成编码音频字节流吗？

**Comment by panpan123456** [comment]
同求

**Comment by fumiama** [comment]
更改代码即可。

**Comment by panpan123456** [comment]
> 目前的 demo 使用 pyaudio 播放的，可以直接流式 infer 结果转成编码音频字节流吗？

你好问下，这个是怎么改的？
