### ISSUE TITLE
There is a messy code problem in ChatTTS WebUI

### ISSUE THREAD

**Issue by lunyu-half** [2noise/ChatTTS#541]
After launching ChatTTS WebUI `python examples/web/webui.py` , I found there was a messy code problem on the page, as you can see in the following image.
I don't know what exactly they are in the **Speaker Embedding** textbox and  **DVAE Coefficient** textbox. Are they now unavailable for using?  Maybe you should fix it.
<img width="1115" alt="2024-07-07_105504" src="https://github.com/2noise/ChatTTS/assets/33707237/85a65831-0127-43d4-a596-4b9d870c87dc">

**Comment by fumiama** [comment]
That's the encoding of data. If you copy it and save them in somewhere, you will be able to restore the timbre by pasting it in the textbox.
