### ISSUE TITLE
没有找到transformer_engine_extensions 模块，No module named 'transformer_engine_extensions'

### ISSUE THREAD

**Issue by xyqbest** [2noise/ChatTTS#542]
第一次使用时，提示没找到transformer_engine。
尤于没法科学上网，pip install TE的的方式没搞成，用了官方指导的源码编译。安装成功了TE，但在import chatTTS的时候提示
```
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
No module named 'transformer_engine_extensions'
```
请教一下如何解决？
1. 如何解决上面的bug？
2. 能不能不用transformer_engine？但我在import 阶段就报错了

**Comment by fumiama** [comment]
> 如何解决上面的bug

TE 现在不可用，还在试验阶段。

> 能不能不用transformer_engine

当然可以，无需理会没找到transformer_engine的提示，那只是个warning。

**Comment by xyqbest** [comment]
> > 如何解决上面的bug
> 
> TE 现在不可用，还在试验阶段。
> 
> > 能不能不用transformer_engine
> 
> 当然可以，无需理会没找到transformer_engine的提示，那只是个warning。

1. 我在import 阶段就报错了。注意是报错，Error，不是Warning。后面的代码就直接提示没有ChatTTS模块。
2. 你们的guidance，简直叫做灾难。我在同步进行两件事，没细看你们的安装命令，直接copy并run了。
```
conda create -n chattts
conda activate chattts
pip install -r requirements.txt
```
这套命令下来，直接把我base环境的东西给改了。
`conda create -n chattts` 的时候不需要安装个python和pip么？不指定的话，就是一个空环境，空环境里是没有pip的。在此环境下跑pip，pip用的就是base环境的pip，安装的也就是base环境的包。。。
3. 那么高⭐的项目，我好像没找到开发文档、API文档。。。有的代码写chat.load_model()，刚发布一个新版本写法又是chat.load()。里面的参数是什么含义，也只能跳转进框架里去检查。

**Comment by fumiama** [comment]
1. 没有人跟您卖关子，没有人无聊到在这骗您，没有人有义务回答您的问题，对愿意看这个 issue 并回答问题的人，请端正自己的态度，否则我可以选择不再回答。

2. 具体问题具体分析，出什么问题提什么 issue，不要预设一个“我是绝对正确”的立场。有没有一种可能，即我运行是正常的，而您不是。请您记住：issue 的编辑功能有历史记录，您发送的任何东西我会收到邮件，不要妄图抹消已经发生的冒犯而不做任何解释。

> 我在import 阶段就报错了。注意是报错，Error，不是Warning

我的注意力还没有到能在千里之外黑进您的电脑查看您的屏幕的程度。如果有具体的问题，请带上具体的报错信息，具体解决。如果您在这里发泄情绪，我也只好选择向您发泄情绪了。您不贴任何报错信息发一段文字描述，我选择推测您可能遇到的情形并给予回答，请珍惜这种态度。换一个人的话，他可能就会直接给您算一卦了。而现在，我不想再回答您的这个问题。如果您意识到自己哪里有问题，请带上自己的详细报错新开 issue。如果您继续发泄情绪，我会直接删除您的 issue，乃至将您 block。

> 那么高⭐的项目，我好像没找到开发文档、API文档。。。

典型的阴阳怪气。请参看提交历史记录吧，在六月一日也就是一个月前，如果您试图使用本项目，我都不知道您会发出怎样的锐评。至于文档不同步，这对于任何一个不断变化发展的项目来说都是存在的，如果发现，您应该针对具体文件提出issue或更正pr，而非在此阴阳。

> 里面的参数是什么含义，也只能跳转进框架里去检查。

在一个月前，您甚至无法做到这样的检查，因为函数接受的参数是kwargs。

> 那么高⭐的项目，

没有GPT-SoVITS高。如果您觉得本项目不堪用，我向您隆重推荐该项目，请务必试试。
