### ISSUE TITLE
unexpected end at index

### ISSUE THREAD

**Issue by yuguosen** [2noise/ChatTTS#543]
Text input: ["post like top youtubers and accelerate your growth with top,quality hooks. don't let capcut hold you back, a great hook is  ninety-nine percent of what makes your video go viral", ' 比如甜水面、赖汤圆、蛋烘糕、叶儿粑等，这些小吃口味温和，甜而不腻，也很受欢迎']

使用api的示例代码，单独跑每一个都没问题，但是放在一起就一直报
code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [1]
code:   0%|          | 0/2048(max) [00:00, ?it/s]
regenerate in order to ensure non-empty
code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [1]
code:   0%|          | 0/2048(max) [00:00, ?it/s]
regenerate in order to ensure non-empty
code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [1]
code:   0%|          | 0/2048(max) [00:00, ?it/s]

**Comment by fumiama** [comment]
这是为了跑出来的结果不为空而设的检查，详见 #511。如果最终可以得到正常的结果，可以忽略此警告。

**Comment by cailuyu** [comment]
> 这是为了跑出来的结果不为空而设的检查，详见 #511。如果最终可以得到正常的结果，可以忽略此警告。

这个场景下经常会爆显存！

**Comment by fumiama** [comment]
> 这个场景下经常会爆显存！

爆显存问题有待解决。目前可先调低batch数，以显著减少尝试频次。

**Comment by cailuyu** [comment]
> > 这个场景下经常会爆显存！
> 
> 爆显存问题有待解决。目前可先调低batch数，以显著减少尝试频次。

就2条都会爆的，感觉代码递归调用了。
这个问题不如暂时让用户自己重新预测，我暂时把ensure_non_empty改false了

**Comment by zxs-learn** [comment]
> 这是为了跑出来的结果不为空而设的检查，详见 #511。如果最终可以得到正常的结果，可以忽略此警告。

关键是一直卡在 0% 不能生成了

**Comment by AdamMayor2018** [comment]
我按照fix642改了代码还是出现unexpected end at index [0]和显存爆炸问题。
在我的场景中，设置speed0就不会有问题，设置speed1就会有问题。

**Comment by fumiama** [comment]
> 我按照fix642改了代码还是出现unexpected end at index [0]和显存爆炸问题。

如果你固定了生成种子，那么无论生成多少次，都会是 unexpected end at index [0] 的结果。我已经在dev发了一个修复，就是在检测到自定义种子时自动无效化`ensure_non_empty`: c140a0b

**Comment by fumiama** [comment]
此时不要自己调用`torch.manual_seed`, 给`RefineTextParams`/`InferCodeParams`传入`manual_seed`参数即可。
