### ISSUE TITLE
对时间播报的任务效果不好，是因为缺样本么？

### ISSUE THREAD

**Issue by bkseastone** [2noise/ChatTTS#544]
比如待推理的text为：
现在是19点17

推理后的音频为：
[https://www.weisong.space/release/tmp/现在是19点17.wav](https://www.weisong.space/release/tmp/现在是19点17.wav)

**Comment by fumiama** [comment]
应该是没有normalizer导致的，建议全部写成汉字推理。阿拉伯数字是无法被识别的。

**Comment by MissingTwins** [comment]
1. 下载这个
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/paddlespeech/t2s/frontend/zh_normalization

2. 你可能需要安装 pypinyin
```
#pip install pypinyin
from zh_normalization import text_normlization
mn = text_normlization.TextNormalizer()
test_txt = """
直至今日我都不知道当时30亿和50亿这两个数字是从哪里冒出来的，很显然那时我并不理解数字是怎么回事儿。
"""
tmp_n =  mn.normalize_sentence(test_txt)
print(tmp_n)
```

`直至今日我都不知道当时三十亿和五十亿这两个数字是从哪里冒出来的，很显然那时我并不理解数字是怎么回事儿。`

![image](https://github.com/2noise/ChatTTS/assets/146804746/f7fc9b30-ced3-47c1-acd9-83010673fe04)

**Comment by cailuyu** [comment]
> 1. 下载这个
>        https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/paddlespeech/t2s/frontend/zh_normalization
> 
>     2. 你可能需要安装 pypinyin
> 
> 
> ```
> #pip install pypinyin
> from zh_normalization import text_normlization
> mn = text_normlization.TextNormalizer()
> test_txt = """
> 直至今日我都不知道当时30亿和50亿这两个数字是从哪里冒出来的，很显然那时我并不理解数字是怎么回事儿。
> """
> tmp_n =  mn.normalize_sentence(test_txt)
> print(tmp_n)
> ```
> 
> `直至今日我都不知道当时三十亿和五十亿这两个数字是从哪里冒出来的，很显然那时我并不理解数字是怎么回事儿。`
> 
> ![image](https://private-user-images.githubusercontent.com/146804746/346772481-f7fc9b30-ced3-47c1-acd9-83010673fe04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTU5MzAsIm5iZiI6MTcyMDQ5NTYzMCwicGF0aCI6Ii8xNDY4MDQ3NDYvMzQ2NzcyNDgxLWY3ZmM5YjMwLWNlZDMtNDdjMS1hY2Q5LTgzMDEwNjczZmUwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMzI3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmQwMzAyYjRiYTYzZDdhODI5MGFkNGE2ODA4ZDA5NTVhOWJlMjVhYzVlM2NlN2QzMThjMWFjY2M5NDNkZDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gkr09BnKmJ_i3pniWdxXegtHn2SSyf1crVRtKVnopWg)

新版本是要自己作zh_normalization了是吗，那do_text_normalization没用了？

**Comment by fumiama** [comment]
> 新版本是要自己作zh_normalization了是吗

用
```py
chat.normailzer.register('zh', function_name)
```
方法注册一个新的中文normalizer。

**Comment by cailuyu** [comment]
> > 新版本是要自己作zh_normalization了是吗
> 
> 用
> 
> ```python
> chat.normailzer.register('zh', function_name)
> ```
> 
> 方法注册一个新的中文normalizer。
亲侧可行，之前好像默认就是用tn.chinese.normalizer，新在需要手动注册

**Comment by hudaoling** [comment]
注册from zh_normalization import text_normlization  这个中文norm模块后，解决了数字问题，
又面临中英文混合句子中，英文单词发音错误，如何处理好呢?

**Comment by fumiama** [comment]
可以举一个例句

**Comment by Jarvanen** [comment]
流式输出的情况下  数字该如何处理呢
