### ISSUE TITLE
Generate default input test failed

### ISSUE THREAD

**Issue by JUSTLIKEHU** [2noise/ChatTTS#545]
error as follow:

python examples/web/webui.py
[+0800 20240707 22:49:10] [WARN]  WebUI  | funcs | no ffmpeg installed, use wav file output
[+0800 20240707 22:49:10] [INFO]  WebUI  | webui | loading ChatTTS model...
[+0800 20240707 22:49:10] [INFO] ChatTTS | dl | checking assets...
[+0800 20240707 22:49:11] [INFO] ChatTTS | dl | checking configs...
[+0800 20240707 22:49:11] [INFO] ChatTTS | dl | all assets are already latest.
[+0800 20240707 22:49:12] [INFO] ChatTTS | core | use device cuda:0
[+0800 20240707 22:49:12] [INFO] ChatTTS | core | vocos loaded.
[+0800 20240707 22:49:12] [INFO] ChatTTS | core | dvae loaded.
[+0800 20240707 22:49:12] [WARN] ChatTTS | gpt | use default LlamaModel for importing TELlamaModel error: No module named 'transformer_engine'
[+0800 20240707 22:49:14] [WARN] ChatTTS | gpt | compile failed: Dynamo is not supported on Python 3.12+. fallback to normal mode.
[+0800 20240707 22:49:14] [INFO] ChatTTS | core | gpt loaded.
[+0800 20240707 22:49:14] [INFO] ChatTTS | core | decoder loaded.
[+0800 20240707 22:49:14] [INFO] ChatTTS | core | tokenizer loaded.
[+0800 20240707 22:49:14] [INFO] ChatTTS | core | all models has been initialized.
[+0800 20240707 22:49:14] [WARN]  WebUI  | funcs | Package nemo_text_processing not found!
[+0800 20240707 22:49:14] [WARN]  WebUI  | funcs | Run: conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing
[+0800 20240707 22:49:14] [WARN]  WebUI  | funcs | Package WeTextProcessing not found!
[+0800 20240707 22:49:14] [WARN]  WebUI  | funcs | Run: conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
[+0800 20240707 22:49:14] [INFO]  WebUI  | webui | Models loaded successfully.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
gio: http://localhost:8080/: Operation not supported
[+0800 20240707 22:49:35] [INFO] ChatTTS | core | all models has been initialized.
text:   0%|                                                                                                                                                                           | 0/384(max) [00:00, ?it/s]We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)
text:  17%|████████████████████████████▉                                                                                                                                         | 67/384(max) [00:02, 31.96it/s]
[+0800 20240707 22:49:38] [INFO] ChatTTS | core | all models has been initialized.
code:  24%|███████████████████████████████████████▎                                                                                                                            | 491/2048(max) [00:06, 71.26it/s]
Traceback (most recent call last):
  File "/home/aaa/miniconda3/lib/python3.12/site-packages/gradio/queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaa/miniconda3/lib/python3.12/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaa/miniconda3/lib/python3.12/site-packages/gradio/blocks.py", line 1938, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaa/miniconda3/lib/python3.12/site-packages/gradio/blocks.py", line 1761, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaa/miniconda3/lib/python3.12/site-packages/gradio/components/audio.py", line 267, in postprocess
    file_path = processing_utils.save_audio_to_cache(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaa/miniconda3/lib/python3.12/site-packages/gradio/processing_utils.py", line 235, in save_audio_to_cache
    audio_to_file(sample_rate, data, filename, format=format)
  File "/home/aaa/miniconda3/lib/python3.12/site-packages/gradio/processing_utils.py", line 566, in audio_to_file
    file = audio.export(filename, format=format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaa/miniconda3/lib/python3.12/site-packages/pydub/audio_segment.py", line 895, in export
    wave_data.writeframesraw(pcm_for_wav)
  File "/home/aaa/miniconda3/lib/python3.12/wave.py", line 565, in writeframesraw
    self._ensure_header_written(len(data))
  File "/home/aaa/miniconda3/lib/python3.12/wave.py", line 606, in _ensure_header_written
    self._write_header(datasize)
  File "/home/aaa/miniconda3/lib/python3.12/wave.py", line 618, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'H' format requires 0 <= number <= 65535

**Comment by fumiama** [comment]
Try the latest commit.

**Comment by JUSTLIKEHU** [comment]
sorry, It's my fault; It works normally after I changed python version from 3.12 to 3.10

**Comment by fumiama** [comment]
> It works normally after I changed python version from 3.12 to 3.10

Well, I want it work on py3.12 as well. Maybe you can try the latest commit again.
