### ISSUE TITLE
AttributeError: 'memoryview' object has no attribute 'find'

### ISSUE THREAD

**Issue by panpan123456** [2noise/ChatTTS#548]
api运行请求的时候报错

请求参数：
{
  "text": [
    "测试一下"
  ],
  "stream": false,
  "lang": "zh",
  "skip_refine_text": false,
  "refine_text_only": false,
  "use_decoder": true,
  "do_text_normalization": true,
  "do_homophone_replacement": false,
  "audio_seed": 666,
  "text_seed": 42,
  "params_refine_text": {
    "prompt": "",
    "top_P": 0.7,
    "top_K": 20,
    "temperature": 0.7,
    "repetition_penalty": 1,
    "max_new_token": 384,
    "min_new_token": 0,
    "show_tqdm": true,
    "ensure_non_empty": true,
    "stream_batch": 24
  },
  "params_infer_code": {
    "prompt": "[speed_5]",
    "top_P": 0.7,
    "top_K": 20,
    "temperature": 0.3,
    "repetition_penalty": 1.05,
    "max_new_token": 2048,
    "min_new_token": 0,
    "show_tqdm": true,
    "ensure_non_empty": true,
    "stream_batch": 24
  }
}

**Comment by fumiama** [comment]
fixed in #546
