### ISSUE TITLE
import ChatTTS出错

### ISSUE THREAD

**Issue by XuWink** [2noise/ChatTTS#55]
![image](https://github.com/2noise/ChatTTS/assets/66192911/025c81f3-eb79-4503-8f17-a96896d10ac1)
我该怎样安装ChatTTS？
How can i install  ChatTTS ?

**Comment by XuWink** [comment]
已经解决了，参考https://github.com/2noise/ChatTTS/issues/46

**Comment by niuroumiantt** [comment]
参考了#46， 看不懂操作，尝试着降级也不行。 

就一直显示错误pull 不了chat TTS，macOS 系统 
import ChatTTS
ModuleNotFoundError: No module named 'ChatTTS'

然后就不能用了，试着下载旧版本pytorch，搞不定。 翻来覆去都在这个ChatTTS module 上，请教大家，谢谢
