### ISSUE TITLE
关于3s极速复刻，prompt参考音频格式bug

### ISSUE THREAD

**Issue by ZHUHF123** [2noise/ChatTTS#559]
想知道对于prompt音频格式有什么要求，输入的32khz采样率的音频报错
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.
显示输入的文件是非音频文件
但是输入采样率16khz和24khz的能正常生成，是音频采样率除了不低于16khz还有别的限制吗

**Comment by fumiama** [comment]
与本仓库无关。
