### ISSUE TITLE
audio[]括号中的数字代表什么？报错list index out of range

### ISSUE THREAD

**Issue by linmaobang** [2noise/ChatTTS#56]
Audio(wav[4], rate=24_000, autoplay=True)

为什么会出现IndexError: list index out of range

我以为不同的数字会出现不同的声音，但是为什么会报错呢？

**Comment by GrahLnn** [comment]
这个是你用的texts的元素个数

`["So we found being competitive and collaborative was a huge way of staying motivated towards our goals, so one person to call when you fall off, one person who gets you back on then one person to actually do the activity with.",]*3 \
        + ["我觉得像我们这些写程序的人，他，我觉得多多少少可能会对开源有一种情怀在吧我觉得开源是一个很好的形式。现在其实最先进的技术掌握在一些公司的手里的话，就他们并不会轻易的开放给所有的人用。"]*3`

这里就有0..5六个元素，所以你的wav的索引限制在0..5里面，要是你的texts只是字符串那么你的wav索引就只是[0]

**Comment by linmaobang** [comment]
> 这个是你用的texts的元素个数
> 
> `["So we found being competitive and collaborative was a huge way of staying motivated towards our goals, so one person to call when you fall off, one person who gets you back on then one person to actually do the activity with.",]*3 \ + ["我觉得像我们这些写程序的人，他，我觉得多多少少可能会对开源有一种情怀在吧我觉得开源是一个很好的形式。现在其实最先进的技术掌握在一些公司的手里的话，就他们并不会轻易的开放给所有的人用。"]*3`
> 
> 这里就有0..5六个元素，所以你的wav的索引限制在0..5里面，要是你的texts只是字符串那么你的wav索引就只是[0]

我不是很懂...元素类型不都是字符串嚒，而且也不能填0.5啊，一定是整数

**Comment by GrahLnn** [comment]
那你直接把问题扔给ChatGPT，会有更详细的答案
