### ISSUE TITLE
decoder.yaml sha256 hash mismatch

### ISSUE THREAD

**Issue by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [2noise/ChatTTS#567]
修改webui代码parser = argparse.ArgumentParser(description="ChatTTS demo Launch")
    parser.add_argument(
        "--server_name", type=str, default="0.0.0.0", help="server name"
    )
    parser.add_argument("--server_port", type=int, default=8080, help="server port")
    parser.add_argument("--root_path", type=str, default=None, help="root path")
    parser.add_argument(
        "--custom_path", type=str, default="D:\ChatTTS-Model", help="custom model path"
    )
    parser.add_argument(
        "--coef", type=str, default=None, help="custom dvae coefficient"
    )
    args = parser.parse_args()
后执行报错[+0800 20240713 10:03:04] [INFO] ChatTTS | core | try to load from local: D:\liu\ChatTTS-Model
[+0800 20240713 10:03:04] [INFO] ChatTTS | dl | checking assets...
[+0800 20240713 10:03:30] [INFO] ChatTTS | dl | checking configs...
[+0800 20240713 10:03:30] [WARN] ChatTTS | dl | D:\ChatTTS-Model\config\decoder.yaml sha256 hash mismatch.
[+0800 20240713 10:03:30] [INFO] ChatTTS | dl | expected: 0890ab719716b0ad8abcb9eba0a9bf52c59c2e45ddedbbbb5ed514ff87bff369
[+0800 20240713 10:03:30] [INFO] ChatTTS | dl | real val: 952d65eed43fa126e4ae257d4d7868163b0b1af23ccbe120288c3b28d091dae1
[+0800 20240713 10:03:30] [ERRO] ChatTTS | core | check models in custom path D:\ChatTTS-Model failed.
[+0800 20240713 10:03:30] [ERRO]  WebUI  | webui | Models load failed.

**Comment by fumiama** [comment]
确保decoders.yaml是直接由huggingface下载而来，而非复制粘贴。

**Comment by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [comment]
就是直接git下来的

**Comment by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [comment]
已经解决,在D:\ChatTTS\ChatTTS\res\sha256_map.json中 修改哈希编码为报错信息中的expected的值
