### ISSUE TITLE
自定义模型目录报错

### ISSUE THREAD

**Issue by Song367** [2noise/ChatTTS#570]
[+0800 20240714 18:33:41] [INFO]  WebUI  | webui | loading ChatTTS model...
[+0800 20240714 18:33:41] [INFO]  WebUI  | funcs | local model path: F:\workplace\ChatTTS\pre_model\ChatTTS
[+0800 20240714 18:33:41] [INFO] ChatTTS | core | try to load from local: F:\workplace\ChatTTS\pre_model\ChatTTS
[+0800 20240714 18:33:41] [INFO] ChatTTS | dl | checking assets...
[+0800 20240714 18:33:42] [INFO] ChatTTS | dl | checking configs...
[+0800 20240714 18:33:42] [WARN] ChatTTS | dl | F:\workplace\ChatTTS\pre_model\ChatTTS\config\decoder.yaml sha256 hash mismatch.
[+0800 20240714 18:33:42] [INFO] ChatTTS | dl | expected: 0890ab719716b0ad8abcb9eba0a9bf52c59c2e45ddedbbbb5ed514ff87bff369
[+0800 20240714 18:33:42] [INFO] ChatTTS | dl | real val: 952d65eed43fa126e4ae257d4d7868163b0b1af23ccbe120288c3b28d091dae1
[+0800 20240714 18:33:42] [ERRO] ChatTTS | core | check models in custom path F:\workplace\ChatTTS\pre_model\ChatTTS failed.
[+0800 20240714 18:33:42] [ERRO]  WebUI  | webui | Models load failed.

直接webui.py 不指定模型目录他也不会下载模型。所以下载后的模型该放在哪呢？

**Comment by fumiama** [comment]
> 不指定模型目录他也不会下载模型

custom不会下载模型。

> 所以下载后的模型该放在哪呢？

放在运行命令的当前路径。
