### ISSUE TITLE
'Chat' object has no attribute 'load_models'

### ISSUE THREAD

**Issue by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [2noise/ChatTTS#571]
执行代码
```py
import ChatTTS
import torch
import torchaudio

chat = ChatTTS.Chat()
chat.load_models(source='local', local_path='D:\liu\ChatTTS-Model')

text = '你好奥'

wavs = chat.infer(text, use_decoder=True)

torchaudio.save("./outputs/output-01.wav", torch.from_numpy(wavs[0]), 24000)
报错Traceback (most recent call last):
  File "D:\ChatTTS-main\test.py", line 12, in <module>
    chat.load_models(source='local', local_path='D:\ChatTTS-Model')
AttributeError: 'Chat' object has no attribute 'load_models'
```
怎么回事啊,请问

**Comment by fumiama** [comment]
看最新README，`load_models`已更名为`load`。

**Comment by AliArfa852** [comment]
just try 
print(dir(chat))
and check what you can use 
it can be load or load_model depending on version

**Comment by gg22mm** [comment]
> `load_models``load`
> 
> 看最新README，`load_models`已更名为`load`。

没看到的文档这样写？求个连接

**Comment by ledaladdin** [comment]
"F:\ComfyUI_windows_portable\python_embeded\ChatTTS_video.py", line 53, in <module>
    chat.load(
TypeError: Chat.load() got an unexpected keyword argument 'dvae_path'

**Comment by ledaladdin** [comment]
import os
import shutil
from moviepy.video.io.VideoFileClip import VideoFileClip
from moviepy.audio.io.AudioFileClip import AudioFileClip
import librosa
import numpy as np
import torch
import torchaudio
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import ChatTTS

# 设置路径
video_folder = "D:/TIKTOK25/youtube"
output_folder = "D:/TIKTOK25/youtube/output"
model_cache_dir = "F:/ComfyUI_windows_portable/model"
chattts_model_dir = "F:/ComfyUI_windows_portable/model/ChatTTS"

# 创建输出文件夹
os.makedirs(output_folder, exist_ok=True)

# 设置 transformers 库的缓存目录
os.environ['TRANSFORMERS_CACHE'] = model_cache_dir

# 初始化 GPT-2 模型和 tokenizer
model_name = 'gpt2'
print("Loading GPT-2 model and tokenizer...")
model = GPT2LMHeadModel.from_pretrained(model_name, cache_dir=model_cache_dir)
tokenizer = GPT2Tokenizer.from_pretrained(model_name, cache_dir=model_cache_dir)
print("GPT-2 model and tokenizer loaded.")

# 初始化 ChatTTS 模型
print("Initializing ChatTTS model...")
chat = ChatTTS.Chat()

# 确保模型文件已下载并放置在正确的目录中
chattts_model_files = {
    'dvae': os.path.join(chattts_model_dir, "DVAE.safetensors"),
    'decoder': os.path.join(chattts_model_dir, "Decoder.safetensors"),
    'embed': os.path.join(chattts_model_dir, "Embed.safetensors"),
    'gpt': os.path.join(chattts_model_dir, "GPT.pt"),
    'vocos': os.path.join(chattts_model_dir, "Vocos.safetensors"),
    'tokenizer': os.path.join(chattts_model_dir, "tokenizer.pt"),
    'spk_stat': os.path.join(chattts_model_dir, "spk_stat.pt")
}

# 检查所有必要的文件是否存在
for name, path in chattts_model_files.items():
    if not os.path.exists(path):
        print(f"Error: {name} model file not found at {path}")
        exit(1)

# 加载模型文件
chat.load(
    dvae_path=chattts_model_files['dvae'],
    decoder_path=chattts_model_files['decoder'],
    embed_path=chattts_model_files['embed'],
    gpt_path=chattts_model_files['gpt'],
    vocos_path=chattts_model_files['vocos'],
    tokenizer_path=chattts_model_files['tokenizer'],
    spk_stat_path=chattts_model_files['spk_stat']
)
print("ChatTTS model initialized.")

# 确认模型组件已加载
if not chat.has_loaded():
    print("Error: ChatTTS model components not loaded correctly.")
    exit(1)

# 处理视频文件夹中的每个视频
for video_file in os.listdir(video_folder):
    if video_file.endswith(".mp4"):
        print(f"Processing video: {video_file}")
        video_path = os.path.join(video_folder, video_file)
        base_name = os.path.splitext(video_file)[0]
        
        # 创建单个视频的输出文件夹
        individual_output_folder = os.path.join(output_folder, base_name)
        os.makedirs(individual_output_folder, exist_ok=True)
        
        audio_path = os.path.join(individual_output_folder, "extracted_audio.wav")
        original_text_path = os.path.join(individual_output_folder, "original_text.txt")
        modified_text_path = os.path.join(individual_output_folder, "modified_text.txt")
        modified_audio_path = os.path.join(individual_output_folder, "modified_audio.wav")
        new_video_path = os.path.join(individual_output_folder, "modified_video.mp4")
        
        # 提取音频
        print("Extracting audio from video...")
        video = VideoFileClip(video_path)
        audio = video.audio
        audio.write_audiofile(audio_path)
        print("Audio extracted.")
        
        # 提取音频特征
        print("Extracting audio features...")
        y, sr = librosa.load(audio_path)
        tempo, beats = librosa.beat.beat_track(y=y, sr=sr)
        rms = librosa.feature.rms(y=y)
        rms_db = librosa.amplitude_to_db(rms, ref=np.max)
        print("Audio features extracted.")
        
        # 使用 GPT-2 生成修改后的文本
        original_text = "Hello, how can I help you today? I'm looking for a new laptop."
        with open(original_text_path, "w") as f:
            f.write(original_text)
        
        input_ids = tokenizer.encode(original_text, return_tensors='pt')
        print("Generating modified text using GPT-2...")
        output = model.generate(input_ids, max_length=100, num_return_sequences=1)
        generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
        with open(modified_text_path, "w") as f:
            f.write(generated_text)
        print("Modified text generated.")
        
        # 使用 ChatTTS 生成语音
        print("Generating speech using ChatTTS...")
        wavs = chat.infer([generated_text])
        torchaudio.save(modified_audio_path, torch.from_numpy(wavs[0]), 24000)
        print("Speech generated.")
        
        # 合成新的视频
        print("Combining new audio with video...")
        new_audio = AudioFileClip(modified_audio_path)
        new_audio = new_audio.set_duration(video.duration)
        new_video = video.set_audio(new_audio)
        new_video.write_videofile(new_video_path)
        print(f"New video saved at {new_video_path}")

print("处理完成。")

**Comment by fumiama** [comment]
你看的文档太老了，一切以最新README为准，不要看国内那些中文教程，接口早就变了。
