### ISSUE TITLE
TypeError: 'RefineTextParams' object is not subscriptable

### ISSUE THREAD

**Issue by v-yunbin** [2noise/ChatTTS#572]
/data/disk1/ybZhang/ChatTTS-v2/ChatTTS/norm.py:14: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def _find_index(table: np.ndarray, val: np.uint16):
/data/disk1/ybZhang/ChatTTS-v2/ChatTTS/norm.py:22: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def _fast_replace(
use default LlamaModel for importing TELlamaModel error: No module named 'transformer_engine'
found invalid characters: {'5', '＞', '2', '0'}
Traceback (most recent call last):
  File "infer_.py", line 10, in <module>
    wavs = chat.infer(texts)
  File "/data/disk1/ybZhang/ChatTTS-v2/ChatTTS/core.py", line 238, in infer
    return next(res_gen)
  File "/data/disk1/ybZhang/ChatTTS-v2/ChatTTS/core.py", line 366, in _infer
    refined = self._refine_text(
  File "/home/ybZhang/miniconda3/envs/chattts2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/disk1/ybZhang/ChatTTS-v2/ChatTTS/core.py", line 591, in _refine_text
    text = [f"[Sbreak]{i}[Pbreak]{params['prompt']}" for i in text]
  File "/data/disk1/ybZhang/ChatTTS-v2/ChatTTS/core.py", line 591, in <listcomp>
    text = [f"[Sbreak]{i}[Pbreak]{params['prompt']}" for i in text]
TypeError: 'RefineTextParams' object is not subscriptable

**Comment by fumiama** [comment]
Please read README carefully.
