### ISSUE TITLE
最后一个单词发音不完整

### ISSUE THREAD

**Issue by Frankchen850** [2noise/ChatTTS#576]
输出音频中，还没读完就结束了，最后一个单词发音不完整。句子长度在20个单词左右。语言是英语。

**Comment by hello2mao** [comment]
+1

手动加了个[uv_break]在句末能缓解。

**Comment by Frankchen850** [comment]
> +1
> 
> 手动加了个[uv_break]在句末能缓解。

有用的，问题解决了！

**Comment by fumiama** [comment]
与 #503 重复。
