### ISSUE TITLE
开源协议 AGPL-v3.0

### ISSUE THREAD

**Issue by Ox0400** [2noise/ChatTTS#577]
请问 dev 分支 开源协议是 [AGPL-v3.0], 但是 readme 中声明不允许商用, 以哪个为准?

**Comment by fumiama** [comment]
> 但是 readme 中声明不允许商用

模型仍以 CC BY-NC 4.0 分发。也就是说，代码允许商用，但模型要用自己的。

**Comment by fastfading** [comment]
但又不说模型是如何训练的。    
训练方法， 代码， 训练集。 都不开源。   所以是伪开源

**Comment by fumiama** [comment]
张口就来。开源哪些部分是作者的自由，伸手就要反而是吃相难看。

目前，本项目已经开源除数据集外的绝大部分内容，懂的人自可以根据代码中的模型架构写出相应的训练/微调代码（如 LORA 等），进而生成自己的模型文件，因此模型是可以自定义的。

在大公司垄断大量AI算力和数据资源的当下，完全开源只会便宜了大公司，因为他们可以暗地里用算法优化自己的模型，但是改完后完全不开源，因为你没法证明他们到底借鉴了什么代码。他们推出的模型将由于训练集质量更优而碾压本模型，而且也有大把的人才再针对性做优化（当然，仍然不开源），进而将此项目倒逼至死路。

当然，大公司还可以选择**完全开源**他们做的更好的模型。为什么大公司更乐意完全开源呢？因为他们的人才储备和数据集规模可以保证他们是整个项目的领跑者，此时开源就成为了集全球程序员之力演进代码的正向循环。一般人，甚至中小公司都没有这个实力。同样，这将会将此项目倒逼至死路。

仓库目前的开源状态是当下最优解，在张口就骂**伪开源**前请记住：你以为你在帮助广大程序员实现开源正义，但是在国内开源生态极其恶劣的当下，你的话语只会成为倒卖模型的二道贩子和 AI 头部垄断大企业的帮凶。看看以`MIT`协议毫无保留地开源后的`RVC`乌烟瘴气的国内社区现状吧。

**Comment by fastfading** [comment]
这个你要说就说， 
要骂就骂。
你说的有道理，大家自然会看。 
大家也能理解不完全开源的顾虑。
你讲的也很有道理。

开源哪些部分是作者的自由。
但评论也是读者的自由， 说的不对， 你就指正。
你report spam 折叠隐藏评论的做法， 和某党有什么区别。

**Comment by fumiama** [comment]
你在我们的仓库撒野，还要惯着你了？

我还可以直接删除你的评论但并没有这么做，已经是给你留下了充足的言论自由了。你还觉得不满足，还要把这个问题发散到涉政层面，我不标记你spam我标记谁？

**Comment by kingmpw2015** [comment]
> 张口就来。开源哪些部分是作者的自由，伸手就要反而是吃相难看。
> 
> 目前，本项目已经开源除数据集外的绝大部分内容，懂的人自可以根据代码中的模型架构写出相应的训练/微调代码（如 LORA 等），进而生成自己的模型文件，因此模型是可以自定义的。
> 
> 在大公司垄断大量AI算力和数据资源的当下，完全开源只会便宜了大公司，因为他们可以暗地里用算法优化自己的模型，但是改完后完全不开源，因为你没法证明他们到底借鉴了什么代码。他们推出的模型将由于训练集质量更优而碾压本模型，而且也有大把的人才再针对性做优化（当然，仍然不开源），进而将此项目倒逼至死路。
> 
> 当然，大公司还可以选择**完全开源**他们做的更好的模型。为什么大公司更乐意完全开源呢？因为他们的人才储备和数据集规模可以保证他们是整个项目的领跑者，此时开源就成为了集全球程序员之力演进代码的正向循环。一般人，甚至中小公司都没有这个实力。同样，这将会将此项目倒逼至死路。
> 
> 仓库目前的开源状态是当下最优解，在张口就骂**伪开源**前请记住：你以为你在帮助广大程序员实现开源正义，但是在国内开源生态极其恶劣的当下，你的话语只会成为倒卖模型的二道贩子和 AI 头部垄断大企业的帮凶。看看以`MIT`协议毫无保留地开源后的`RVC`乌烟瘴气的国内社区现状吧。

难得的高质量开源项目，支持！！

**Comment by fumiama** [comment]
> 难得的高质量开源项目，支持！！

感谢支持🤝🤝刚才在看这个issue，发现之前那个人自觉理亏，把自己的评论都删了。所以我补充点上下文，大致就是那个人首先评论说这个项目是“伪开源”，我回复之后他承认我说的有道理，但是又这壶不开提那壶，从言论自由方向说事，还扯到“这和某党有什么区别”，所以才有了第二段评论。

**Comment by JiJiBo** [comment]
我们公司需要一个英文的推广视频，我能拿这个生成结果做配音吗？因为你们生成的很真实

**Comment by fumiama** [comment]
> 我们公司需要一个英文的推广视频，我能拿这个生成结果做配音吗？因为你们生成的很真实

目前暂无商用计划，因此你只要在显眼位置注明本项目，并且不直接售卖该配音即可。

**Comment by sunjianan9900** [comment]
请问生成的语音如果用作自己的自媒体账号（如ytb、tt等）的配音并且有收益，也算商用吗？
