### ISSUE TITLE
AttributeError: 'TELlamaDecoderLayer' object has no attribute 'mlp'

### ISSUE THREAD

**Issue by grantchenhuarong** [2noise/ChatTTS#579]
Hi,
when I using Python3.10.12，successfully installed the optional TransformerEngine ,I start the web ui, got this error:
AttributeError: 'TELlamaDecoderLayer' object has no attribute 'mlp'
![error1](https://github.com/user-attachments/assets/64361cf6-df72-48d3-9bee-d6657ef76076)

How can I fix it?

**Comment by grantchenhuarong** [comment]
The process of installation about TransformerEngine  is extremly slow, more than half an hour.

**Comment by grantchenhuarong** [comment]
I do some modifications with gpt.py and core.py ，maybe that's the reason why. But
gpt.py
# from torch.nn.utils.parametrizations import weight_norm
from torch.nn.utils import weight_norm

**Comment by fumiama** [comment]
> How can I run webui with TransformerEngine ?

Now TE does exist but cannot run properly. See the WARING of README in the related paragraph.

**Comment by ain-soph** [comment]
In `Chat`, `TransformerEngine` modifies `self.gpt.gpt`, which no longer has the `self.gpt.gpt.layers[0].mlp.gate_proj.in_features` used in `_sample_random_speaker`.

**Comment by fumiama** [comment]
> [!Warning]
>
> Now TE does exist but cannot run properly. The `infer_text` part will generate random result and the `infer_code` part is still broken. Also, the speed didn't increase and even decreased.
