### ISSUE TITLE
怎么取消掉文本优化？？？？！！！

### ISSUE THREAD

**Issue by Airgods** [2noise/ChatTTS#581]
只要中英文混合语音合成，怎么取消掉文本优化的部分，这可以极大地提高速度！！
![1](https://github.com/user-attachments/assets/c7d6a11b-4ed4-4637-a167-bd13790abaad)

**Comment by fumiama** [comment]
参考`examples/web`

**Comment by peakDay** [comment]
大佬cmd怎么运行啊
