### ISSUE TITLE
最新版多句推理时，refine_text问题

### ISSUE THREAD

**Issue by ZaymeShaw** [2noise/ChatTTS#588]
最新版多句推理时，短句的refine_text经常输出莫名其妙的结果。
skip_refine_text为true时推理正常，只推理单句也正常。

示例：
```py
data = chat.infer(
    [
        "总结一下，AI Agent是大模型功能的扩展，让AI更接近于通用人工智能，也就是我们常说的AGI。",
        "你真是太聪明啦。",
    ],
    refine_text_only=True,
    stream=False,
)
```

输出结果：
['总 结 一 下 啊 ， ai agent 是 大 模 型 功 能 的 扩 展 [uv_break] ， 让 ai 更 接 近 于 通 用 人 工 智 能 [uv_break] ， 也 就 是 我 们 常 说 的 agi 。',
 '不 知 道 你 有 没 有 过 这 种 ， 我 也 是 我 还 是 有 一 些 人 是 有 的 [uv_break] ， 我 也 是 我 们 这 个 节 目 里 的 一 个 人 。 我 我 们 这 个 节 目 里 的 一 个 人 ， 他 是 一 个 我 们 的 [uv_break] 一 个 小 男 孩 。 对 ， 他 是 一 个 一 个 小 男 孩 ， 然 后 他 是 我 们 的 ， 我 们 是 一 个 男 孩 。 对 ， 他 是 一 个 就 是 一 个 小 男 孩 ， 他 是 一 个 女 孩 ， 我 们 的 一 个 小 男 孩 ， 我 们 的 一 个 小 男 孩 ， 他 是 一 个 [uv_break] 呃 [uv_break] 一 个 小 女 孩 ， 她 是 一 个 女 孩 ， 她 是 一 个 小 女 孩 ， 他 是 一 个 女 孩 ， 他 是 一 个 女 孩 。 然 后 呢 ， 我 们 这 一 次 就 是 我 们 的 朋 友 是 一 个 女 孩 的 时 候 ， 我 们 就 说 [Pbreak] 你 真 是 太 聪 明 啦 [laugh] 。 [uv_break]']

**Comment by fumiama** [comment]
请尝试最新dev，应该已经修复。
