### ISSUE TITLE
api推理第一次加载完模型之后，生成输出文本和音频时间需要5分钟，太慢。

### ISSUE THREAD

**Issue by peakDay** [2noise/ChatTTS#593]

**Comment by peakDay** [comment]
![image](https://github.com/user-attachments/assets/8bb9a54a-6e70-4403-881f-32ecdc3b46c4)

**Comment by peakDay** [comment]
![image](https://github.com/user-attachments/assets/97055961-b83f-4322-8ada-a2de48dcaa1e)

**Comment by peakDay** [comment]
![image](https://github.com/user-attachments/assets/bfade7d3-1870-4045-ab0b-9113401558d8)

**Comment by peakDay** [comment]
![image](https://github.com/user-attachments/assets/37bd0727-bfbf-4a0c-8d20-89e9b0b81078)

**Comment by peakDay** [comment]
这些过程要5分钟

**Comment by peakDay** [comment]
@fumiama 请求帮助，谢谢

**Comment by fumiama** [comment]
与 #476 重复。
