### ISSUE TITLE
We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py:124: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.   warnings.warn(

### ISSUE THREAD

**Issue by peakDay** [2noise/ChatTTS#599]
We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)

/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py:124: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
这个问题怎么解决呢？
请求大佬帮忙。
并且第一次生成text和生成音频好5-6分钟，就很离谱。离了个特朗普
![0010](https://github.com/user-attachments/assets/8f64c73d-0722-4acc-8156-897c6557ac7a)

![0011](https://github.com/user-attachments/assets/e74fced8-dfca-4cc3-a6b7-6b3883a56b5b)

**Comment by peakDay** [comment]
@fumiama 救命救命

**Comment by fumiama** [comment]
与 #476 重复。

**Comment by peakDay** [comment]
> 与#476重复。

那怎么操作能第一次编译加快速度了

**Comment by fumiama** [comment]
编译速度无法加快。要不你就`load(compile=False)`取消编译，代价是每次循环速度减半。

**Comment by peakDay** [comment]
> 编译速度无法加快。要不是你就`load(compile=False)`取消编译，代价是每次循环速度减半。

那速度是多快了。我每次推理的text都不一样的

**Comment by fumiama** [comment]
实际试试呗

**Comment by peakDay** [comment]
> 实际试试呗

行

**Comment by peakDay** [comment]
> 编译速度无法加快。要不你就`load(compile=False)`取消编译，代价是每次循环速度减半。

这个参数是在哪里改了？谢谢您

**Comment by peakDay** [comment]
> 實際尝试
chat.load() 吗？
