### ISSUE TITLE
缺少ChatTTS/asset/spk_stat.pt

### ISSUE THREAD

**Issue by Prunoideae** [2noise/ChatTTS#6]
在Notebook里有：
```py
spk_stat = torch.load('ChatTTS/asset/spk_stat.pt')
rand_spk = torch.randn(768) * spk_stat.chunk(2)[0] + spk_stat.chunk(2)[1]
```

但是，HF上却并没有发布`asset/spk_stat.pt`，所以没办法运行这一段。

**Comment by stevezhang88** [comment]
耐心等着，作者开心，就会上传的。

**Comment by zhangmx** [comment]
在这下载 https://huggingface.co/2Noise/ChatTTS/tree/main/asset

**Comment by zhangshuyx** [comment]
国内可以从这个镜像站上下载 https://hf-mirror.com/2Noise/ChatTTS/tree/main/asset
