### ISSUE TITLE
苹果 M1电脑运行时 不支持 GPU 运算

### ISSUE THREAD

**Issue by rikuta** [2noise/ChatTTS#60]
```
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
```

虽然也有能用吧 但速度有点慢

**Comment by Lion-Wu** [comment]
可尝试把 pytorch 的 device 改为 mps，我暂时还没试过，但是理论上是可以支持的

**Comment by GarrickLin** [comment]
1. 用mps比cpu慢，同时需要 `export PYTORCH_ENABLE_MPS_FALLBACK=1`
2. 用mps结果不对

**Comment by Lion-Wu** [comment]
> 1. 用mps比cpu慢，同时需要 `export PYTORCH_ENABLE_MPS_FALLBACK=1`
> 2. 用mps结果不对

那等pytorch更新吧，现在关于tts的很多开源项目都没法很好地用mps跑起来

**Comment by shunlibest** [comment]
我是M1 Pro，现在我卡在0%的进度，一直不动，是不是有问题？

**Comment by rikuta** [comment]
> 我是M1 Pro，现在我卡在0%的进度，一直不动，是不是有问题？

肯定是有问题，正常跑起来是这种。

`INFO:ChatTTS.core:Load from local: /ChatTTS-main/ChatTTS/model
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
INFO:ChatTTS.core:All initialized.
 74%|██████████████████████████████████████████████████████████████████████████████████████▉                               | 283/384 [00:25<00:09, 10.98it/s]
 71%|██████████████████████████████████████████████████████████████████████████████████▊                                 | 1463/2048 [01:50<00:44, 13.22it/s]
Number of elements in wavs: 1
Element 0 type: <class 'numpy.ndarray'>
Element 0 shape: (1, 748800)
Audio file saved: /ChatTTS-main/chattts_wavs-0_7.wav`
