### ISSUE TITLE
报错AttributeError: 'Tensor' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Fernando-Zzs** [2noise/ChatTTS#601]
相关环境信息：chattts版本0.1.1 torch版本2.3.1
复现步骤：
rand_spk = chat.sample_random_speaker()
params_infer_code = ChatTTS.Chat.InferCodeParams(
    spk_emb = rand_spk, # add sampled speaker 
    temperature = .3,   # using custom temperature
    top_P = 0.7,        # top P decode
    top_K = 20,         # top K decode
)
params_refine_text = ChatTTS.Chat.RefineTextParams(
    prompt='[oral_2][laugh_0][break_6]',
)
wav = chat.infer('今天天气真不错', params_refine_text=params_refine_text, params_infer_code=params_infer_code)

**Comment by jianchang512** [comment]
是不是使用的从其他项目下载的pt文件？
已不可用，需要转码。

**Comment by fumiama** [comment]
无法复现。请确保给出的代码是出错的代码。

**Comment by yxygg** [comment]
> 是不是使用的从其他项目下载的pt文件？ 已不可用，需要转码。

请问要如何进行转码？有没有一个简单的代码示例？

**Comment by fumiama** [comment]
最新代码请使用`chat.tokenizer._encode_spk_emb`转码。较老的代码可以使用`chat._encode_spk_emb`

**Comment by wangaolin1** [comment]
最新代码请使用chat.tokenizer._encode_spk_emb转码。较老的代码可以使用chat._encode_spk_emb
 I tried this way and fixed it,

**Comment by Yaqing2023** [comment]
我有Version: 0.1.1, 当我用  spk = chat.tokenizer._encode_spk_emb 或 chat._encode_spk_emb， 我都得到

object has no attribute '_encode_spk_emb'
请大神赐教
