### ISSUE TITLE
勾选stream mode选项程序报错

### ISSUE THREAD

**Issue by whmyxh** [2noise/ChatTTS#611]
勾选这个选项后生成一次语音后，程序就无法运行了。

**Comment by peakDay** [comment]
对。bug多

**Comment by fumiama** [comment]
> 对。bug多。我们在测试bug啊

不会说话可以不说，不想用可以不用，没人逼你。不要在其他人的issue下用发泄情绪的方式打搅正常讨论。

**Comment by peakDay** [comment]
> > 对。bug多。我们在测试bug啊
> 
> 
> 
> 不会说话可以不说，不想用可以不用，没人逼你。不要在其他人的issue下用发泄情绪的方式打搅正常讨论。

好的。这就是所谓的支持流式输出。我只是说事实罢了，哎，心态要稳。

**Comment by fumiama** [comment]
> > > 对。bug多。我们在测试bug啊
> > 
> > 
> > 不会说话可以不说，不想用可以不用，没人逼你。不要在其他人的issue下用发泄情绪的方式打搅正常讨论。
> 
> 好的。这就是所谓的支持流式输出。我只是说事实罢了，哎，心态要稳。

请记住，您没有给开源社区一分钱，**没有人**有义务无偿为您解答任何问题。对于您这种不具有[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)的伸手党和完全不会做贡献，只会嘴皮子抱怨的开源蛀虫，我门今后将不会回答您的任何问题，除非您的态度改观。

**Comment by peakDay** [comment]
> > > > 对。bug多。我们在测试bug啊
> 
> > > 
> 
> > > 
> 
> > > 不会说话可以不说，不想用可以不用，没人逼你。不要在其他人的issue下用发泄情绪的方式打搅正常讨论。
> 
> > 
> 
> > 好的。这就是所谓的支持流式输出。我只是说事实罢了，哎，心态要稳。
> 
> 
> 
> 请记住，您没有给开源社区一分钱，**没有人**有义务无偿为您解答任何问题。对于您这种不具有[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)的伸手党和完全不会做贡献，只会嘴皮子抱怨的开源蛀虫，我门今后将不会回答您的任何问题，除非您的态度改观。

烂项目就别开源好吧，别丢人行吧。正因为bug多才有这么多问题，态度还不好，还回答别人问题。那个开发者在自己项目下说脏话，没素质。祝您的项目bug多多，不谢。流式bug。

**Comment by subway-jack** [comment]
enmm我早上尝试去看了一下gradio的源码，试了很多种办法，他原理上针对音频流是通过二进制数据输出到/stream/下的一个文件夹内，然后把改地址传到Audio里，但貌似浏览器不支持直接读取二进制文件。我就修改了一下gradio的源码把他弄成每次生成一个文件，包括历史，类似积累的输出吧，然后通过/file=/file_path读取，但每次输出太快会覆盖掉之前的wav文件，没办法也需要要等全部弄好才能播放。可能还是等他怎么处理/stream/。很难受

**Comment by fumiama** [comment]
> enmm我早上尝试去看了一下gradio的源码，试了很多种办法，他原理上针对音频流是通过二进制数据输出到/stream/下的一个文件夹内，然后把改地址传到Audio里，但貌似浏览器不支持直接读取二进制文件。我就修改了一下gradio的源码把他弄成每次生成一个文件，包括历史，类似积累的输出吧，然后通过/file=/file_path读取，但每次输出太快会覆盖掉之前的wav文件，没办法也需要要等全部弄好才能播放。可能还是等他怎么处理/stream/。很难受

还是得等待官方修复了😂

**Comment by whmyxh** [comment]
> > enmm我早上尝试去看了一下gradio的源码，试了很多种办法，他原理上针对音频流是通过二进制数据输出到/stream/下的一个文件夹内，然后把改地址传到Audio里，但貌似浏览器不支持直接读取二进制文件。我就修改了一下gradio的源码把他弄成每次生成一个文件，包括历史，类似积累的输出吧，然后通过/file=/file_path读取，但每次输出太快会覆盖掉之前的wav文件，没办法也需要要等全部弄好才能播放。可能还是等他怎么处理/stream/。很难受
> 
> 还是得等待官方修复了😂

## 直接屏蔽就没有这个bug了，等什么时候修好再恢复😊
