### ISSUE TITLE
cmd/run.py bug

### ISSUE THREAD

**Issue by peakDay** [2noise/ChatTTS#613]
![image](https://github.com/user-attachments/assets/729732e1-dc86-40b7-9574-64f921fa462a)

**Comment by fumiama** [comment]
无法复现。请给出更详细信息，如命令行的输入参数。

<img width="959" alt="截屏2024-07-23 上午12 52 24" src="https://github.com/user-attachments/assets/d452a2c2-1ed3-4ec6-830d-ff9aa8df69c5">
