### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by gabrieldechichi** [2noise/ChatTTS#616]
The current license for the repo (commit [51ec0c7](https://github.com/2noise/ChatTTS/commit/51ec0c784c2795b257d7a6b64274e7a36186b731)) is a `GNU Affero General Public License v3.0` which allows commercial use.

However, reading the README it states that the model is for non-commercial use only. Is the model itself not under `GNU Affero General Public License v3.0`?

**Comment by fumiama** [comment]
> Is the model itself not under `GNU Affero General Public License v3.0`?

Yes. The license of the model is `CC BY-NC 4.0`.

**Comment by gabrieldechichi** [comment]
Thanks for clarifying! Are there plans to release a version on commercial model in the future? Just wanted to make sure to ask as we are evaluating multiple TTS models for our company.

**Comment by fumiama** [comment]
> Are there plans to release a version on commercial model in the future?

Yes, now we're working on it.

**Comment by gabrieldechichi** [comment]
Great to hear, thanks for the responsiveness!

**Comment by lukaLLM** [comment]
Sorry, are there any updates about the commercial update I missed the model license part?
