### ISSUE TITLE
gpt.pt如何导出onnx?

### ISSUE THREAD

**Issue by Baiyuetribe** [2noise/ChatTTS#618]
其他模型导出很容易，就这个不会，希望能新增onnx导出

**Comment by ZaymeShaw** [comment]
同求方案

**Comment by ZillaRU** [comment]
可以分块导出，分成每个decoder layer、LM head、Embedding、sample head导出。

**Comment by ZillaRU** [comment]
https://github.com/2noise/ChatTTS/pull/622 之前写的导出脚本。
https://zhuanlan.zhihu.com/p/703240560

**Comment by Baiyuetribe** [comment]
@ZillaRU 哇，gpt竟然能分割导出10个以上的onnx文件，有点小困惑。真的不能再柔和一下吗？

**Comment by ZillaRU** [comment]
可以参考https://github.com/tpoisonooo/llama.onnx做导出，chatTTS的gpt其实是一个小型的llama。拆的细是因为每个decoder layer的结构是等同的，单独拆开方便对单个block的优化和测试验证。可以认为优化了单个就是优化了全部。

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech
