### ISSUE TITLE
代码分享

### ISSUE THREAD

**Issue by samqin123** [2noise/ChatTTS#62]
### 导入ChatTTS模块和soundfile模块
import ChatTTS
import soundfile as sf
import os

def text_to_mp3(text, filename):
    chat = ChatTTS.Chat()
    chat.load_models()
    wavs = chat.infer(text, use_decoder=True)
    sf.write(r"/文件路径/ChatTTS/{filename}.wav", wavs[0][0], 24000)

def split_and_convert_to_mp3(file_path, chunk_size=10000):
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()
        text_length = len(text)
        chunks = [text[i:i+chunk_size] for i in range(0, text_length, chunk_size)]
        
    for i, chunk in enumerate(chunks, start=1):
        mp3_filename = f"output_{i}"
        text_to_mp3(chunk, mp3_filename)

if __name__ == "__main__":
    file_path = "/path/test.txt"  # 替换为你的文本文件路径
    split_and_convert_to_mp3(file_path)

**Comment by cacard** [comment]
优化一下格式：
https://gist.github.com/cacard/612b29cc88cd4ef453a59a5ac999b1af
