### ISSUE TITLE
请问如何通过api训练自己的声音并使用呢？

### ISSUE THREAD

**Issue by ZhangDewei** [2noise/ChatTTS#623]
如题，请指点迷津。谢谢

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Comment by fumiama** [comment]
API只是简单的示例，要实现更高级功能需要自行封装调用接口。至于`zero shot`音色克隆功能，可以试用`examples/web`，并查看该文件夹下相关代码实现。
