### ISSUE TITLE
根据已有语音合成报错

### ISSUE THREAD

**Issue by hjy2008** [2noise/ChatTTS#641]
报错如下：
```
Traceback (most recent call last):
  File "d:\hjy\Anaconda\Lib\site-packages\gradio\queueing.py", line 536, in process_events    
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\hjy\Anaconda\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\hjy\Anaconda\Lib\site-packages\gradio\blocks.py", line 1919, in process_api        
    inputs = await self.preprocess_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\hjy\Anaconda\Lib\site-packages\gradio\blocks.py", line 1650, in preprocess_data    
    processed_input.append(block.preprocess(inputs_cached))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\hjy\Anaconda\Lib\site-packages\gradio\components\audio.py", line 231, in preprocess
    sample_rate, data = processing_utils.audio_from_file(temp_file_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\hjy\Anaconda\Lib\site-packages\gradio\processing_utils.py", line 536, in audio_from_file
    audio = AudioSegment.from_file(filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\hjy\Anaconda\Lib\site-packages\pydub\audio_segment.py", line 773, in from_file     
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 4294967274  

Output from ffmpeg/avlib:

ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with clang version 14.0.6
  configuration: --prefix=/c/b/abs_ca4f2jj2ps/croot/ffmpeg_1722024538388/_h_env/Library --cc=clang.exe --ar=llvm-ar --nm=llvm-nm --ranlib=llvm-ranlib --strip= --disable-doc --enable-swresample --enable-swscale --enable-openssl --enable-libxml2 --enable-libtheora --enable-demuxer=dash --enable-postproc --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libdav1d --enable-zlib --enable-libaom --enable-pic --enable-shared --disable-static --disable-gpl --enable-version3 --disable-sdl2 --ld=lld-link --target-os=win64 --toolchain=msvc --host-cc=clang.exe --enable-cross-compile --host-extralibs= --disable-pthreads --enable-w32threads --extra-libs='ucrt.lib vcruntime.lib oldnames.lib' --disable-stripping
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
[mp3 @ 000001B4203BAB80] Format mp3 detected only with low score of 1, misdetection possible! 
[mp3 @ 000001B4203BAB80] Failed to read frame size: Could not seek to 1026.
[in#0 @ 000001B420395DC0] Error opening input: Invalid argument
Error opening input file C:\Users\hankangfeng\AppData\Local\Temp\gradio\2f4d0ad3e8d8ae006e50ac34f07126a677960ca8\audio.mp3.
Error opening input files: Invalid argument
```

**Comment by fumiama** [comment]
音频文件可能有问题，尝试先转码为`wav`格式后上传。

**Comment by hjy2008** [comment]
我拿自带的录音进行录音报错。
更换格式还是报错：Traceback (most recent call last):
  File "D:\hjy\Anaconda\Lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hjy\Anaconda\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hjy\Anaconda\Lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hjy\Anaconda\Lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hjy\Anaconda\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hjy\Anaconda\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\hjy\Anaconda\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hjy\Anaconda\Lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\project\ChatTTS\examples\web\funcs.py", line 121, in on_upload_sample_audio
    spk_smp = chat.sample_audio_speaker(sample_audio)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Chat' object has no attribute 'sample_audio_speaker'. Did you mean: 'sample_random_speaker'?

**Comment by fumiama** [comment]
> AttributeError: 'Chat' object has no attribute 'sample_audio_speaker'. Did you mean: 'sample_random_speaker'?

请仔细阅读 README 并确保自己的代码为仓库中的最新版。

**Comment by huyx22** [comment]
我也报了同样的错，
{
	"name": "AttributeError",
	"message": "'Chat' object has no attribute 'sample_audio_speaker'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[17], line 12
      8 # 保存为wav格式
      9 audionew = audio.export(\"/home/hyx/voice cloning/Sound_resource/fjt.wav\", format=\"wav\")
---> 12 spk_smp = chat.sample_audio_speaker(load_audio(audionew, 24000))
     13 print(spk_smp)  # save it in order to load the speaker without sample audio next time
     15 params_infer_code = ChatTTS.Chat.InferCodeParams(
     16     spk_smp=spk_smp,
     17     txt_smp=\"与sample.mp3内容完全一致的文本转写。\",
     18 )

AttributeError: 'Chat' object has no attribute 'sample_audio_speaker'"
}
我看到我下载的core.py的Chat类里是有sample_audio_speaker这个函数的定义的：
 @torch.inference_mode()
    def sample_audio_speaker(self, wav: Union[np.ndarray, torch.Tensor]) -> str:
        if isinstance(wav, np.ndarray):
            wav = torch.from_numpy(wav).to(self.device)
        return self.tokenizer._encode_prompt(self.dvae(wav, "encode").squeeze_(0))
