### ISSUE TITLE
中文部分无法识别数字（1，2，3等）和句号（。）是需要设置什么吗？

### ISSUE THREAD

**Issue by uvtong** [2noise/ChatTTS#644]
如题，中文部分无法识别数字（1，2，3等）和句号（。）是需要设置什么吗？

**Comment by Papapaladin** [comment]
你可以把数字转成中文就可以了，小数点也可以对应匹配

**Comment by Papapaladin** [comment]
def digit_to_chinese(digit):
    chinese_digits = '零一二三四五六七八九'
    if 0 <= digit < 10:
        return chinese_digits[digit]
    elif 10 <= digit < 100:
        return (chinese_digits[digit // 10] + '十' +
                (chinese_digits[digit % 10] if digit % 10 != 0 else ''))
    elif 100 <= digit < 1000:
        return (chinese_digits[digit // 100] + '百' +
                (digit_to_chinese(digit % 100) if digit % 100 != 0 else ''))
    elif 1000 <= digit < 10000:
        return (chinese_digits[digit // 1000] + '千' +
                (digit_to_chinese(digit % 1000) if digit % 1000 != 0 else ''))
    else:
        return "超出范围"
def number_to_chinese(number):
    if number == 0:
        return "零"
    chinese_number = ''
    thousands = [10000, 1000, 100, 10, 1]
    units = ['万', '千', '百', '十', '']

    for i, unit in enumerate(thousands):
        part = number // unit
        if part > 0:
            chinese_number += digit_to_chinese(part) + units[i]
            number %= unit
    # 去除多余的"零"
    chinese_number = re.sub(r'零+', '零', chinese_number).strip('零')
    return chinese_number or "零"
def convert_numbers_to_chinese(text):
    def replace_number(match):
        number_str = match.group()
        if '.' in number_str:
            integer_part, decimal_part = number_str.split('.')
            integer_chinese = number_to_chinese(int(integer_part))
            decimal_chinese = ''.join([digit_to_chinese(int(digit)) for digit in decimal_part])
            return f"{integer_chinese}点{decimal_chinese}"
        else:
            return number_to_chinese(int(number_str))

    # 使用正则表达式匹配连续的数字或带有小数点的数字
    pattern = r'\d+(\.\d+)?'
    converted_text = re.sub(pattern, replace_number, text)
    return converted_text

**Comment by uvtong** [comment]
@Papapaladin 大佬，刚刚是贴了py代码么，我刚刷新没了。还能提供一份吗

**Comment by bugkiwi** [comment]
@uvtong 

```python
def init_chat():
    chat = ChatTTS.Chat(get_logger("ChatTTS"))
    chat.load(source="local", compile=True)
    try:
        chat.normalizer.register("en", normalizer_en_nemo_text())
    except ValueError as e:
        logger.error(e)
    except:
        logger.warning("Package nemo_text_processing not found!")
        logger.warning(
            "Run: conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing",
        )
    try:
        chat.normalizer.register("zh", normalizer_zh_tn())
    except ValueError as e:
        logger.error(e)
    except:
        logger.warning("Package WeTextProcessing not found!")
        logger.warning(
            "Run: conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing",
        )
    return chat
```

**Comment by uvtong** [comment]
`import re

def convert_numbers_to_chinese(text):
    # 定义中文数字映射
    chinese_digits = '零一二三四五六七八九'

    # 定义转换数字的函数
    def convert_number(match):
        number = match.group(0)
        if '.' in number:
            # 处理小数点
            integer_part, decimal_part = number.split('.')
            integer_chinese = ''.join(chinese_digits[int(digit)] for digit in integer_part if digit.isdigit())
            decimal_chinese = ''.join(chinese_digits[int(digit)] for digit in decimal_part if digit.isdigit())
            return f"{integer_chinese}点{decimal_chinese}"
        elif '%' in number:
            # 处理百分号
            number = number.replace('%', '')
            number_chinese = ''.join(chinese_digits[int(digit)] for digit in number if digit.isdigit())
            return f"百分之{number_chinese}"
        else:
            # 处理普通数字
            return ''.join(chinese_digits[int(digit)] for digit in number if digit.isdigit())

    # 处理年份（包括三位数和四位数）
    def convert_year(match):
        year = match.group(0)
        # 检查“年”字是否存在于匹配数字之后的3个字符内
        if '年' in text[match.end():match.end()+3]:
            return f"{convert_number(match)}年"
        else:
            return convert_number(match)

    # 替换所有小数点和百分比格式
    text = re.sub(r'\d+\.\d+%', convert_number, text)
    text = re.sub(r'\d+%', convert_number, text)
    # 处理年份（四位数和三位数的情况）
    text = re.sub(r'\b\d{4}\b', convert_year, text)  # 处理四位年份
    text = re.sub(r'\b\d{3}\b', convert_year, text)  # 处理三位年份
    # 处理其他数字（包括小数和百分比）
    text = re.sub(r'\d+\.\d+%?', convert_number, text)
    text = re.sub(r'\d+', convert_number, text)

    return text

# 测试
text = "2024年标志着一个激动人心的时刻。定于7月26日举行的开幕式承诺将是一场壮观的事件"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)

# 测试
text = "如果银行以5%的利率向你提供贷款，而对你的储蓄支付1%的利息，它就从4%的差额中获得利润"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)

# 测试
text = "最著名的太空任务之一是阿波罗11号任务，它在1969年将第一个人类送上了月球。"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)`

**Comment by uvtong** [comment]
import re

def convert_numbers_to_chinese(text):
    # 定义中文数字映射
    chinese_digits = '零一二三四五六七八九'

    # 定义转换数字的函数
    def convert_number(match):
        number = match.group(0)
        if '.' in number:
            # 处理小数点
            integer_part, decimal_part = number.split('.')
            integer_chinese = ''.join(chinese_digits[int(digit)] for digit in integer_part if digit.isdigit())
            decimal_chinese = ''.join(chinese_digits[int(digit)] for digit in decimal_part if digit.isdigit())
            return f"{integer_chinese}点{decimal_chinese}"
        elif '%' in number:
            # 处理百分号
            number = number.replace('%', '')
            number_chinese = ''.join(chinese_digits[int(digit)] for digit in number if digit.isdigit())
            return f"百分之{number_chinese}"
        else:
            # 处理普通数字
            return ''.join(chinese_digits[int(digit)] for digit in number if digit.isdigit())

    # 处理年份（包括三位数和四位数）
    def convert_year(match):
        year = match.group(0)
        # 检查“年”字是否存在于匹配数字之后的3个字符内
        if '年' in text[match.end():match.end()+3]:
            return f"{convert_number(match)}年"
        else:
            return convert_number(match)

    # 替换所有小数点和百分比格式
    text = re.sub(r'\d+\.\d+%', convert_number, text)
    text = re.sub(r'\d+%', convert_number, text)
    # 处理年份（四位数和三位数的情况）
    text = re.sub(r'\b\d{4}\b', convert_year, text)  # 处理四位年份
    text = re.sub(r'\b\d{3}\b', convert_year, text)  # 处理三位年份
    # 处理其他数字（包括小数和百分比）
    text = re.sub(r'\d+\.\d+%?', convert_number, text)
    text = re.sub(r'\d+', convert_number, text)

    return text

# 测试
text = "2024年标志着一个激动人心的时刻。定于7月26日举行的开幕式承诺将是一场壮观的事件"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)

# 测试
text = "如果银行以5%的利率向你提供贷款，而对你的储蓄支付1%的利息，它就从4%的差额中获得利润"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)

# 测试
text = "最著名的太空任务之一是阿波罗11号任务，它在1969年将第一个人类送上了月球。"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)

**Comment by uvtong** [comment]
import re

def convert_numbers_to_chinese(text):
    chinese_digits = '零一二三四五六七八九'

    def convert_number(match):
        number = match.group(0)
        if '.' in number:
            # 处理小数点
            integer_part, decimal_part = number.split('.')
            integer_chinese = ''.join(chinese_digits[int(digit)] for digit in integer_part if digit.isdigit())
            decimal_chinese = ''.join(chinese_digits[int(digit)] for digit in decimal_part if digit.isdigit())
            return f"{integer_chinese}点{decimal_chinese}"
        elif '%' in number:
            # 处理百分号
            number = number.replace('%', '')
            number_chinese = ''.join(chinese_digits[int(digit)] for digit in number if digit.isdigit())
            return f"百分之{number_chinese}"
        else:
            # 处理普通数字
            return ''.join(chinese_digits[int(digit)] for digit in number if digit.isdigit())

    # 处理年份（包括三位数和四位数）
    def convert_year(match):
        year = match.group(0)
        # 检查“年”字是否存在于匹配数字之后的3个字符内
        if '年' in text[match.end():match.end()+3]:
            return f"{convert_number(match)}年"
        else:
            return convert_number(match)

    # 替换所有小数点和百分比格式
    text = re.sub(r'\d+\.\d+%', convert_number, text)
    text = re.sub(r'\d+%', convert_number, text)
    # 处理年份（四位数和三位数的情况）
    text = re.sub(r'\b\d{4}\b', convert_year, text)  # 处理四位年份
    text = re.sub(r'\b\d{3}\b', convert_year, text)  # 处理三位年份
    # 处理其他数字（包括小数和百分比）
    text = re.sub(r'\d+\.\d+%?', convert_number, text)
    text = re.sub(r'\d+', convert_number, text)

    return text

text = "2024年标志着一个激动人心的时刻。定于7月26日举行的开幕式承诺将是一场壮观的事件"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)

text = "如果银行以5%的利率向你提供贷款，而对你的储蓄支付1%的利息，它就从4%的差额中获得利润"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)

text = "最著名的太空任务之一是阿波罗11号任务，它在1969年将第一个人类送上了月球。"
converted_text = convert_numbers_to_chinese(text)
print(converted_text)

**Comment by fumiama** [comment]
注册`normalizer`或直接用汉字写出数字。

**Comment by Yaqing2023** [comment]
pynini - 这个只能在Linux上跑吧？ 有没有windows或Mac的解决方案？

**Comment by fumiama** [comment]
可以自行寻找其他解决方案，将其注册到normalizer。
