### ISSUE TITLE
doesn't work on rtx 3080

### ISSUE THREAD

**Issue by loca1first** [2noise/ChatTTS#653]
tried this on rtx 3080 but just stuck at 0%

i tried the webui and also the example run.py

```
text:   0%|                                                                                                                                                                    0/384(max) [00:00, ?it/s]
```

it just hangs like that for several minutes

**Comment by fumiama** [comment]
Please provide detailed info (ex. the code or command you used) for re-producing this bug.

**Comment by loca1first** [comment]
when i ran the sample code from examples

for webui and run.py it gets stuck at 0%

**Comment by fumiama** [comment]
Well, it may related to your environment. Please provide the torch version and CUDA version you use.

**Comment by BiboyQG** [comment]
I use torch2.3.1+cu121 and also came across this problem.

**Comment by BiboyQG** [comment]
> I use torch2.3.1+cu121 and also came across this problem.

I solved the stuck by passing `device = 'cuda'` into the load function from Chat. Like this:
```python
def load_chat(cust_path: Optional[str], coef: Optional[str]) -> bool:
    if cust_path == None:
        ret = chat.load(
            coef=coef,
            # compile=sys.platform != "win32"
            compile = False,
            device='cuda'
        )
    else:
        logger.info("local model path: %s", cust_path)
        ret = chat.load(
            "custom",
            custom_path=cust_path,
            coef=coef,
            # compile=sys.platform != "win32"
            compile = False,
            device='cuda'
        )
        global custom_path
        custom_path = cust_path
```

**Comment by fumiama** [comment]
Theoretically, the program can select the cuda device automatically. You can paste the program log with and without this modification.

**Comment by mercuryyy** [comment]
I had the same issue, it does not select it automatically
