### ISSUE TITLE
模型存在还要下载？ 运行Dev下的python examples/web/webui.py      应该是tokenizer.py的问题

### ISSUE THREAD

**Issue by watch-Ultra** [2noise/ChatTTS#668]
[+0000 20240806 06:41:34] [INFO]  WebUI  | webui | loading ChatTTS model...
[+0000 20240806 06:41:34] [INFO] ChatTTS | dl | checking assets...
[+0000 20240806 06:41:38] [INFO] ChatTTS | dl | /app/asset/tokenizer/special_tokens_map.json not exist.
[+0000 20240806 06:41:38] [INFO] ChatTTS | dl | downloading https://github.com/fumiama/RVC-Models-Downloader/releases/download/v0.2.6/rvcmd_linux_amd64.tar.gz
[+0000 20240806 06:41:48] [INFO] ChatTTS | dl | downloading https://raw.gitcode.com/u011570312/RVC-Models-Downloader/raw/main/dns.yaml
[+0000 20240806 06:41:49] [INFO] ChatTTS | dl | downloaded into /home/model-server/tmp/tmpwt65k5zp
[+0000 20240806 06:41:49] [INFO] ChatTTS | dl | downloading https://raw.gitcode.com/u011570312/RVC-Models-Downloader/assets/990
[+0000 20240806 06:41:50] [INFO] ChatTTS | dl | downloaded.
[+0000 20240806 06:41:50] [INFO] ChatTTS | dl | extracted into /home/model-server/tmp/tmpwt65k5zp
INFO[0000] RVC Models Downloader start at 2024-08-06 06:41:50 (UTC) 
INFO[0000] operating system: linux, architecture: amd64 
INFO[0000] is ipv6 available: false                     
INFO[0000] custom dns file added                        
INFO[0000] #1 open target folder 'asset'.               
INFO[0000] #1 download copy: '[asset/DVAE.pt asset/DVAE_full.pt asset/Decoder.pt asset/GPT.pt asset/Vocos.pt asset/spk_stat.pt asset/tokenizer.pt]'. 
WARN[0000] #1.7 skip exist file asset/tokenizer.pt      
WARN[0000] #1.1 skip exist file asset/DVAE.pt           
WARN[0000] #1.2 skip exist file asset/DVAE_full.pt      
WARN[0000] #1.3 skip exist file asset/Decoder.pt        
WARN[0000] #1.4 skip exist file asset/GPT.pt            
WARN[0000] #1.5 skip exist file asset/Vocos.pt          
WARN[0000] #1.6 skip exist file asset/spk_stat.pt       
INFO[0000] all download tasks finished.                 
[+0000 20240806 06:41:50] [INFO] ChatTTS | dl | checking assets...
[+0000 20240806 06:41:52] [INFO] ChatTTS | dl | /app/asset/tokenizer/special_tokens_map.json not exist.
[+0000 20240806 06:41:52] [ERRO] ChatTTS | core | download to local path /app failed.
[+0000 20240806 06:41:52] [ERRO]  WebUI  | webui | Models load failed.

**Comment by JimWang151** [comment]
> [+0000 20240806 06:41:34] [INFO] WebUI | webui | loading ChatTTS model... [+0000 20240806 06:41:34] [INFO] ChatTTS | dl | checking assets... [+0000 20240806 06:41:38] [INFO] ChatTTS | dl | /app/asset/tokenizer/special_tokens_map.json not exist. [+0000 20240806 06:41:38] [INFO] ChatTTS | dl | downloading https://github.com/fumiama/RVC-Models-Downloader/releases/download/v0.2.6/rvcmd_linux_amd64.tar.gz [+0000 20240806 06:41:48] [INFO] ChatTTS | dl | downloading https://raw.gitcode.com/u011570312/RVC-Models-Downloader/raw/main/dns.yaml [+0000 20240806 06:41:49] [INFO] ChatTTS | dl | downloaded into /home/model-server/tmp/tmpwt65k5zp [+0000 20240806 06:41:49] [INFO] ChatTTS | dl | downloading https://raw.gitcode.com/u011570312/RVC-Models-Downloader/assets/990 [+0000 20240806 06:41:50] [INFO] ChatTTS | dl | downloaded. [+0000 20240806 06:41:50] [INFO] ChatTTS | dl | extracted into /home/model-server/tmp/tmpwt65k5zp INFO[0000] RVC Models Downloader start at 2024-08-06 06:41:50 (UTC) INFO[0000] operating system: linux, architecture: amd64 INFO[0000] is ipv6 available: false INFO[0000] custom dns file added INFO[0000] #1 open target folder 'asset'. INFO[0000] #1 download copy: '[asset/DVAE.pt asset/DVAE_full.pt asset/Decoder.pt asset/GPT.pt asset/Vocos.pt asset/spk_stat.pt asset/tokenizer.pt]'. WARN[0000] #1.7 skip exist file asset/tokenizer.pt WARN[0000] #1.1 skip exist file asset/DVAE.pt WARN[0000] #1.2 skip exist file asset/DVAE_full.pt WARN[0000] #1.3 skip exist file asset/Decoder.pt WARN[0000] #1.4 skip exist file asset/GPT.pt WARN[0000] #1.5 skip exist file asset/Vocos.pt WARN[0000] #1.6 skip exist file asset/spk_stat.pt INFO[0000] all download tasks finished. [+0000 20240806 06:41:50] [INFO] ChatTTS | dl | checking assets... [+0000 20240806 06:41:52] [INFO] ChatTTS | dl | /app/asset/tokenizer/special_tokens_map.json not exist. [+0000 20240806 06:41:52] [ERRO] ChatTTS | core | download to local path /app failed. [+0000 20240806 06:41:52] [ERRO] WebUI | webui | Models load failed.

兄弟，你怎么解决这个问题的？我也遇到这个状况。多谢。

**Comment by JimWang151** [comment]
再重新运行一次就OK了,多谢。
