### ISSUE TITLE
Provide a docker image which you can run ChatTTS without caring about environment.

### ISSUE THREAD

**Issue by ridiculers** [2noise/ChatTTS#67]
### Statement
Pull the image and create a container as the following steps.
You don't need to care about environment configuration and model weight files. 
### Environment
This image can run in Windows Subsystem for Linux (WSL) version 2.
**Macos havn't been verified yet**.
### Address
https://hub.docker.com/r/lcs13324/chattts
### The way to use it
- Pull image. <br/> `docker pull lcs13324/chattts:v1.0`</br>
- Create and run a new container from this image. <br/> `docker run -it --gpus=[your gpu id] -p [container port]:[localhost port] lcs13324/chattts:v1.0 /bin/bash` <br/>Allow use gpu and port mapping for jupyter notebook.<br/> eg. `docker run -it --gpus=all -p 8888:8888 lcs13324/chattts:v1.0 /bin/bash` </br>
- Run jupyter notebook.<br/> `cd workspace/ChatTTS/` <br/> `jupyter notebook --allow root --ip=0.0.0.0`

**Comment by montoulieu** [comment]
Awesome work. Any way you could add an api endpoint to this?

**Comment by ridiculers** [comment]
> Awesome work. Any way you could add an api endpoint to this?

Hi,sry for late reply.I'm not sure about "api endpoint",could you please give me an example or make an specific explanation?
Thank you.
