### ISSUE TITLE
英文情况下朗读会包含停顿，也就是会把 [uv_break] 也给读了

### ISSUE THREAD

**Issue by jingxdy** [2noise/ChatTTS#683]
<img width="1727" alt="1723431686997" src="https://github.com/user-attachments/assets/90b7d477-5638-4a4c-8bec-3a46163f57bb">

**Comment by Ziyi6** [comment]
看了下作者给的例子，[uv_break]和单词是连着的，中间没有空格，你可以试一下把空格去掉？

**Comment by jingxdy** [comment]
> 看了下作者给的例子，[uv_break]和单词是连着的，中间没有空格，你可以试一下把空格去掉吗？

我输入的文本是不带有空格的，输出的文本也没有空格，自动补充了停顿，我也无法删除，但是在同样的参数下，中文不会有类似问题，所以我想是不是英文要做些什么处理

**Comment by fumiama** [comment]
与 #655 重复。请尝试最新dev，应该已经修复。
