### ISSUE TITLE
token过长，如200-300字时，会出现尾部信息消失问题

### ISSUE THREAD

**Issue by Shengrun2020** [2noise/ChatTTS#687]
请问作者出现这种情况是超参的问题吗？

**Comment by xldistance** [comment]
文本截断，每段长度150左右，分别生成音频再合成整段音频。chattts每次只能生成30秒左右的音频，文字多了后面的就被截断了，推荐用整合包https://github.com/lenML/ChatTTS-Forge

**Comment by fumiama** [comment]
与 #503 重复。
