### ISSUE TITLE
请问有比较有特色的音色吗，类似动漫中的音色，或者说萝莉、正太的音色，或者带方言的音色，如果有可以分享一下pt文件吗

### ISSUE THREAD

**Issue by wangqiaoch** [2noise/ChatTTS#691]
Could you please let me know if there are distinctive vocal tones, similar to those in anime, or tones associated with loli or shota characters, or even tones with dialects? available, could you share a ".pt" file?

**Comment by fumiama** [comment]
🈚️，因为训练数据集目前只有成男成女。后续出微调之后可以自己训练新的音色。
