### ISSUE TITLE
Lacking  documentation

### ISSUE THREAD

**Issue by leos-code** [2noise/ChatTTS#692]
In the absence of foundational documentation, encountering errors can indeed pose a significant challenge in resolving issues.

**Comment by fumiama** [comment]
Currently the README is detail enough from my point of view. Please point out where you're confusing in order to make it possible for us to explain them and append to README.

**Comment by goshut** [comment]
我对这些关键字:
[uv_break][laugh][lbreak]
[oral_2][laugh_0][break_4]
感到困惑.
例子中出现的是否就是他们的全部?
采用这种格式的源头在哪?
如果有更详细的说明就好了.

**Comment by fumiama** [comment]
> 采用这种格式的源头在哪? 

见 https://huggingface.co/2Noise/ChatTTS/blob/main/asset/tokenizer/special_tokens_map.json
