### ISSUE TITLE
为甚麽执行的时候，windows告诉我里面有木马

### ISSUE THREAD

**Issue by Jung217** [2noise/ChatTTS#693]
> 刚想尝试这个模型，结果 windows defender 就给挡了下来，说有trojan
>  (用 Jupyter Notebook 在本地执行)

![螢幕擷取畫面 2024-08-16 154028](https://github.com/user-attachments/assets/df03affa-0d4d-4975-9866-51928b9ce314)

**Comment by fumiama** [comment]
因为默认会自动下载并执行一个可以直接从HuggingFace下载模型的网络程序[RVC-Models-Downloader](https://github.com/fumiama/RVC-Models-Downloader)，如果觉得不安全，可以使用`load(source="huggingface")`绕过该下载程序，直接从HuggingFace下载模型文件或使用`load(source="custom", custom_path="./")`加载自己下载好的模型文件。
