### ISSUE TITLE
文案中 带有日期的文字识别错误

### ISSUE THREAD

**Issue by yangtyu** [2noise/ChatTTS#695]
[Uploading basic_output0.zip…]()
“2024年7月30日10:00至2024年8月12日24:00”识别错误
完整文案："尊敬的用户： 为了更好地为您提供高效、安全、便捷的服务，定于2024年7月30日10:00至2024年8月12日24:00期间，对APP及小程序进行全面系统升级。"

**Comment by yangtyu** [comment]
[Uploading basic_output0.zip…]()

**Comment by fumiama** [comment]
与 #644 重复。
