### ISSUE TITLE
APIConnectionError: Connection error.

### ISSUE THREAD

**Issue by raimmm** [2noise/ChatTTS#70]
from ChatTTS.experimental.llm import llm_api

API_KEY = ''
client = llm_api(api_key=API_KEY,
        base_url="https://api.deepseek.com",
        model="deepseek-chat")

user_question = '四川有哪些好吃的美食呢?'
text = client.call(user_question, prompt_version = 'deepseek')
text = client.call(text, prompt_version = 'deepseek_TN')

运行demo时，出现APIConnectionError: Connection error.
访问https://api.deepseek.com这个网站也无法访问，求解答

**Comment by raimmm** [comment]
https://www.deepseek.com/   将url替换成这个url生辰api_key复制上去就行，已解决

**Comment by Guo-Bill** [comment]
还是报错，还是“APIConnectionError: Connection error.”

**Comment by raimmm** [comment]
> 还是报错，还是“APIConnectionError: Connection error.”

https://www.deepseek.com/在这个网页上面生成api_key后复制到ChatTTS里面的API_KEY里面，如果不需要用chatgpt接口，只想玩一玩TTS的话也可以不用这个

**Comment by raimmm** [comment]
> 还是报错，还是“APIConnectionError: Connection error.”

https://www.deepseek.com/   在这个网页上面生成api_key后复制到ChatTTS里面的API_KEY里面，如果不需要用chatgpt接口，只想玩一玩TTS的话也可以不用这个
