### ISSUE TITLE
new version load model and voice pt model not work 

### ISSUE THREAD

**Issue by LivinLuo1993** [2noise/ChatTTS#704]
when use new version, something occurred to me:

1.  load model

cannot use

```py
chat.load(source="custom", custom_path=MODEL_PATH,  device='cpu', compile=False)
```

and meet the question `assert self.has_loaded(use_decoder=use_decoder)`

2. self-define voice pt not work

when load model with the flowing codes:

```py
chat._load(
        vocos_config_path=f'{MODEL_PATH}/config/vocos.yaml',
        vocos_ckpt_path=f'{MODEL_PATH}/asset/Vocos.pt',
        dvae_config_path=f'{MODEL_PATH}/config/dvae.yaml',
        dvae_ckpt_path=f'{MODEL_PATH}/asset/DVAE.pt',
        gpt_config_path=f'{MODEL_PATH}/config/gpt.yaml',
        gpt_ckpt_path=f'{MODEL_PATH}/asset/GPT.pt',
        decoder_config_path=f'{MODEL_PATH}/config/decoder.yaml',
        decoder_ckpt_path=f'{MODEL_PATH}/asset/Decoder.pt',
        tokenizer_path=f'{MODEL_PATH}/asset/tokenizer.pt',
        compile=False
    )

spk_stat = torch.load(f'{MODEL_PATH}/speaker/seed_1397_restored_emb.pt',  map_location=torch.device("cpu"))

rand_spk = chat._encode_spk_emb(spk_stat)

wav = chat.infer(
                        input_text,
                        skip_refine_text=True,
                        params_refine_text=params_refine_text,
                        params_infer_code=params_infer_code,
                        use_decoder=True,
                        do_text_normalization=False
                    )
```

output audio is the same with `rand_spk = chat.sample_random_speaker()`

**Comment by fumiama** [comment]
Now  in `dev` branch,

- File `spk_stat.pt` has been removed and embedded into package `config`.
- File `tokenizer.pt` has been removed, replaced by the `json` files.

You can refer to the HuggingFace repo for more details.

**Comment by goshut** [comment]
@LivinLuo1993 
你在infer时都没有对声模进行传参吧..
```python
import ChatTTS
from ChatTTS.model import Tokenizer

'''省略若干代码'''

spk = torch.load('声模.pt',
                         map_location='cpu',
                         weights_only=True,
                         )
spk = Tokenizer._encode_spk_emb(spk)# 字符串化
params_infer_code = ChatTTS.Chat.InferCodeParams(
            spk_emb=spk, 
        )
wavs = chat.infer(texts, params_infer_code=params_infer_code)
```

**Comment by developer-yl** [comment]
I am having the same issue when I try to capture an audio sample and use it as a fixed speaker. The speaker will stay the same for the first 3 tries but then suddenly change from a girl to a man's voice

```
from tools.audio import load_audio
spk_smp = chat.sample_audio_speaker(torch.tensor(load_audio("sample.mp3", 24000)).to('cuda'))
params_infer_code = ChatTTS.Chat.InferCodeParams(
    spk_smp=spk_smp,
    txt_smp="hands off the keyboard",
    prompt="[speed_5]",
    temperature=0.01,
    top_P = 0.01,        # top P decode
    top_K = 1,   
)
text = "You really think thats real [laugh]"
refined_text = chat.infer(text, refine_text_only=True)
print(refined_text)
params_refine_text = ChatTTS.Chat.RefineTextParams(
    prompt='[oral_1][laugh_1][break_4]',
)



wav = chat.infer(
    refined_text,
    # text,
    params_refine_text=params_refine_text,
    skip_refine_text=True,
    params_infer_code=params_infer_code,
)
Audio(wav[0], rate=24_000, autoplay=True)
```

**Comment by 0zhangsan0** [comment]
> 当我尝试捕获音频样本并将其用作固定扬声器时，我遇到了同样的问题。扬声器在前 3 次尝试中将保持不变，但随后突然从女孩的声音变为男性的声音
> 
> ```python
> from tools.audio import load_audio
> spk_smp = chat.sample_audio_speaker(torch.tensor(load_audio("sample.mp3", 24000)).to('cuda'))
> params_infer_code = ChatTTS.Chat.InferCodeParams(
>     spk_smp=spk_smp,
>     txt_smp="hands off the keyboard",
>     prompt="[speed_5]",
>     temperature=0.01,
>     top_P = 0.01,        # top P decode
>     top_K = 1,   
> )
> text = "You really think thats real [laugh]"
> refined_text = chat.infer(text, refine_text_only=True)
> print(refined_text)
> params_refine_text = ChatTTS.Chat.RefineTextParams(
>     prompt='[oral_1][laugh_1][break_4]',
> )
> 
> 
> 
> wav = chat.infer(
>     refined_text,
>     # text,
>     params_refine_text=params_refine_text,
>     skip_refine_text=True,
>     params_infer_code=params_infer_code,
> )
> Audio(wav[0], rate=24_000, autoplay=True)
> ```

When I copied and ran your code, it got stuck in a strange loop.
`code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [0]
code:   0%|          | 0/2048(max) [00:08, ?it/s]
regenerate in order to ensure non-empty
code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [0]
code:   0%|          | 0/2048(max) [00:07, ?it/s]
regenerate in order to ensure non-empty
code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [0]
code:   0%|          | 0/2048(max) [00:07, ?it/s]`

**Comment by 0zhangsan0** [comment]
> > 当我尝试捕获音频样本并将其用作固定扬声器时，我遇到了同样的问题。扬声器在前 3 次尝试中将保持不变，但随后突然从女孩的声音变为男性的声音
> > ```python
> > from tools.audio import load_audio
> > spk_smp = chat.sample_audio_speaker(torch.tensor(load_audio("sample.mp3", 24000)).to('cuda'))
> > params_infer_code = ChatTTS.Chat.InferCodeParams(
> >     spk_smp=spk_smp,
> >     txt_smp="hands off the keyboard",
> >     prompt="[speed_5]",
> >     temperature=0.01,
> >     top_P = 0.01,        # top P decode
> >     top_K = 1,   
> > )
> > text = "You really think thats real [laugh]"
> > refined_text = chat.infer(text, refine_text_only=True)
> > print(refined_text)
> > params_refine_text = ChatTTS.Chat.RefineTextParams(
> >     prompt='[oral_1][laugh_1][break_4]',
> > )
> > 
> > 
> > 
> > wav = chat.infer(
> >     refined_text,
> >     # text,
> >     params_refine_text=params_refine_text,
> >     skip_refine_text=True,
> >     params_infer_code=params_infer_code,
> > )
> > Audio(wav[0], rate=24_000, autoplay=True)
> > ```
> 
> When I copied and ran your code, it got stuck in a strange loop. `code: 0%| | 0/2048(max) [00:00, ?it/s]unexpected end at index [0] code: 0%| | 0/2048(max) [00:08, ?it/s] regenerate in order to ensure non-empty code: 0%| | 0/2048(max) [00:00, ?it/s]unexpected end at index [0] code: 0%| | 0/2048(max) [00:07, ?it/s] regenerate in order to ensure non-empty code: 0%| | 0/2048(max) [00:00, ?it/s]unexpected end at index [0] code: 0%| | 0/2048(max) [00:07, ?it/s]`

`code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [0]`
`code:   0%|          | 0/2048(max) [00:07, ?it/s]`
`regenerate in order to ensure non-empty`
`code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [0]`
`code:   0%|          | 0/2048(max) [00:07, ?it/s]`
`regenerate in order to ensure non-empty`
`code:   0%|          | 0/2048(max) [00:00, ?it/s]unexpected end at index [0]`
`code:   0%|          | 0/2048(max) [00:07, ?it/s]`
`regenerate in order to ensure non-empty`

**Comment by developer-yl** [comment]
Weird that didn't happen to me it worked.

**Comment by 0zhangsan0** [comment]
> Weird that didn't happen to me it worked.

Could you share your "sample.mp3" ? I want to try again.

**Comment by developer-yl** [comment]
I may have deleted the project folder already but I will try to find it if I can.

**Comment by 0zhangsan0** [comment]
> I may have deleted the project folder already but I will try to find it if I can.

Thank you for sharing

**Comment by gg22mm** [comment]
> ```python
> custom_path
> ```

看源码，就懂了，我也是刚看了源码就知道了

![1729153298947](https://github.com/user-attachments/assets/fdf1710c-94f6-4469-8fc9-bfdd4c11c566)
应该这样传：
chat.load(compile=False, source="local",device="cpu",custom_path="./models/2Noise/ChatTTS")

**Comment by gg22mm** [comment]
> when use new version, something occurred to me:
> 
>     1. load model
> 
> 
> cannot use
> 
> ```python
> chat.load(source="custom", custom_path=MODEL_PATH,  device='cpu', compile=False)
> ```
> 
> and meet the question `assert self.has_loaded(use_decoder=use_decoder)`
> 
>     2. self-define voice pt not work
> 
> 
> when load model with the flowing codes:
> 
> ```python
> chat._load(
>         vocos_config_path=f'{MODEL_PATH}/config/vocos.yaml',
>         vocos_ckpt_path=f'{MODEL_PATH}/asset/Vocos.pt',
>         dvae_config_path=f'{MODEL_PATH}/config/dvae.yaml',
>         dvae_ckpt_path=f'{MODEL_PATH}/asset/DVAE.pt',
>         gpt_config_path=f'{MODEL_PATH}/config/gpt.yaml',
>         gpt_ckpt_path=f'{MODEL_PATH}/asset/GPT.pt',
>         decoder_config_path=f'{MODEL_PATH}/config/decoder.yaml',
>         decoder_ckpt_path=f'{MODEL_PATH}/asset/Decoder.pt',
>         tokenizer_path=f'{MODEL_PATH}/asset/tokenizer.pt',
>         compile=False
>     )
> 
> spk_stat = torch.load(f'{MODEL_PATH}/speaker/seed_1397_restored_emb.pt',  map_location=torch.device("cpu"))
> 
> rand_spk = chat._encode_spk_emb(spk_stat)
> 
> wav = chat.infer(
>                         input_text,
>                         skip_refine_text=True,
>                         params_refine_text=params_refine_text,
>                         params_infer_code=params_infer_code,
>                         use_decoder=True,
>                         do_text_normalization=False
>                     )
> ```
> 
> output audio is the same with `rand_spk = chat.sample_random_speaker()`

![1729153298947](https://github.com/user-attachments/assets/339247e9-67ad-4508-804b-2e775c9d24f8)

看了代码发现： chat.load 默认就是用 local,  如果没有的话，就会下载放到跟目录下面的 asset, 不支持自定义。
![1729154945986](https://github.com/user-attachments/assets/5234b4f9-2f4b-453d-b538-71127db0b8a1)

custom 瞄了一下，好象custom说的跟目录 与实际代码的根目录是不一样的，用了custom应该必须要用绝对路径吧。 

chat.load(compile=False,source="local",device="cpu") #不指定 source 为local 则会自动从huggingface下载权重文件,  用了 local 模型是在根目录：asset下面，asset没有设置 custom_path的代码
