### ISSUE TITLE
The tts audio is odd on generating the last preset english example

### ISSUE THREAD

**Issue by neoyxm** [2noise/ChatTTS#707]
This is what I selected :
<img width="800" alt="截屏2024-08-21 11 48 38" src="https://github.com/user-attachments/assets/1896a2ee-16e7-4486-bd40-79cda5a1a30b">

And here the odd audio:
https://github.com/neoyxm/misc/raw/main/audio.mp3

Sounds like a German is speaking.

**Comment by fumiama** [comment]
We need more information. Are all the other settings default? In my platform (Apple M1), this audio sounds like

[audio.mp3.zip](https://github.com/user-attachments/files/16695180/audio.mp3.zip)

**Comment by neoyxm** [comment]
> We need more information. Are all the other settings default? What's your environment? In my platform (Apple M1), this audio sounds like [audio.mp3.zip](https://github.com/user-attachments/files/16695180/audio.mp3.zip)

I didn't change any code, just clone the code and run:   python example/web/webui.py
Here is more info:

GPU: RTX 4090
Platform: Ubuntu 22.04.3 
Dirver and CUDA:  NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2  
key pip  packages:
`
Package                   Version     Editable project location
------------------------- ----------- -------------------------
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.5.82
nvidia-nvtx-cu12          12.1.105
torch                     2.3.1
torchaudio                2.3.1
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.42.4
triton                    2.3.1
`

**Comment by fumiama** [comment]
Try
```py
import torch

print(torch.cuda.is_available())
```
If the output is `False`, try to install the right torch version with CUDA enabled. If it's `True`, try to run on CPU by editing `examples/web/funcs.py` function `load_chat`, replace
```py
ret = chat.load(coef=coef, compile=sys.platform != "win32")
```
with
```py
ret = chat.load(coef=coef, compile=sys.platform != "win32", device="cpu")
```

**Comment by neoyxm** [comment]
> We need more information. Are all the other settings default? What's your environment? In my platform (Apple M1), this audio sounds like [audio.mp3.zip](https://github.com/user-attachments/files/16695180/audio.mp3.zip)

I reproduced the similiar problem on my Mac M2 book. Reproduce steps:
1.clone the latest code from github rev: 51ec0c784c2795b257d7a6b64274e7a36186b731
2. create an new conda env + python 3.10
3.  pip install -r requirements.txt
4. python examples/web/webui.py

Here is the sample audio: https://github.com/neoyxm/misc/raw/main/audio_mac_m2.mp3

**Comment by fumiama** [comment]
> clone the latest code from github rev: 51ec0c784c2795b257d7a6b64274e7a36186b731

try latest `dev` branch.

**Comment by neoyxm** [comment]
> > clone the latest code from github rev: [51ec0c7](https://github.com/2noise/ChatTTS/commit/51ec0c784c2795b257d7a6b64274e7a36186b731)
> 
> try latest `dev` branch.

The dev branch works.
It seems something has been broken on main branch. And the defect not only affects the english text, but also affects the chinese text + cuda on Linux platform. 

Please have a look at that.

**Comment by fumiama** [comment]
Well, it seems that we need to sync the dev branch to main even though the vLLM function is still under development.
