### ISSUE TITLE
The first time to infer costs a long time

### ISSUE THREAD

**Issue by neoyxm** [2noise/ChatTTS#713]
Platform: ubuntu 20.04,  nvidia-driver 535, cuda 12.2

Every time startup the webui and start to infer, it will hang up for several minutes.

After checking, I found there **pt_main_thread** was comsuming the 100% cpu resource.
<img width="787" alt="截屏2024-08-23 10 19 18" src="https://github.com/user-attachments/assets/1d947494-7bd4-4961-ba3e-af0dcde930ae">

And the below is the detail of this process:
<img width="1423" alt="截屏2024-08-23 10 19 46" src="https://github.com/user-attachments/assets/7feee81a-7890-41f6-b602-14c40507381f">

It looks like torch  was compiling something.

**Comment by fumiama** [comment]
Yes. Please try the latest commit, the compile option is set to `False` by default.

**Comment by neoyxm** [comment]
> Yes. Please try the latest commit, the compile option has been set to `False` by default.

Not work with webui.py, cause **compile**  argument has been set to true on non-win32 platform in funcs.py
<img width="652" alt="截屏2024-08-23 15 53 46" src="https://github.com/user-attachments/assets/e794de26-0574-4fa8-bd21-a5955fc2ef61">

**Comment by fumiama** [comment]
That's a missing place. Fixed in the latest `dev` branch.
