### ISSUE TITLE
Empty or noisy audio output if generate tts with same params second / third / fourth ... time 

### ISSUE THREAD

**Issue by neoyxm** [2noise/ChatTTS#715]
Platform: ubuntu 20.04, nvidia-driver 535, cuda 12.2

Latest code rev on main: a27357fbcf4beeeade197000c42194d265cac094

reproduce steps:
1. start up the webui
2. generate the audio by default param, and get the correct output
3. click the generate again, and get the bad audio
4. click the generate again, and bad audio again
5. ...

**Comment by fumiama** [comment]
Can't reproduce this bug under

- Apple M1, CPU
- Google Colab Tesla T4, NVIDIA Driver Version 535.104.05, CUDA Version 12.2

Anyone who also have this issue?

**Comment by neoyxm** [comment]
> Can't reproduce this bug under
> 
> * Apple M1, CPU
> * Google Colab Tesla T4, NVIDIA Driver Version 535.104.05, CUDA Version 12.2
> 
> Anyone who also have this issue?

I will check more variables  in my env if these variables caused this issue.

**Comment by neoyxm** [comment]
> Can't reproduce this bug under
> 
> * Apple M1, CPU
> * Google Colab Tesla T4, NVIDIA Driver Version 535.104.05, CUDA Version 12.2
> 
> Anyone who also have this issue?

May I know the version of your torch and transtformer on Tesla T4?

**Comment by fumiama** [comment]
> > Can't reproduce this bug under
> > 
> > * Apple M1, CPU
> > * Google Colab Tesla T4, NVIDIA Driver Version 535.104.05, CUDA Version 12.2
> > 
> > Anyone who also have this issue?
> 
> May I know the version of your torch and transtformer on Tesla T4?

All default. Just try the colab notebook by clicking README badge.

**Comment by neoyxm** [comment]
After re-install all the pip packages, this issue was fixed.

Sorry for disturbing.
