### ISSUE TITLE
求助~~

### ISSUE THREAD

**Issue by gdmec07150701** [2noise/ChatTTS#726]
$ python.exe examples/web/webui.py
C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\site-packages\vector_quantize_pytorch\vector_quantize_pytorch.py:461: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\site-packages\vector_quantize_pytorch\vector_quantize_pytorch.py:674: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\site-packages\vector_quantize_pytorch\finite_scalar_quantization.py:162: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
[+0800 20240828 17:55:33] [INFO]  WebUI  | webui | loading ChatTTS model...
[+0800 20240828 17:55:33] [INFO] ChatTTS | dl | checking assets...
[+0800 20240828 17:55:33] [INFO] ChatTTS | dl | E:\ChatTTS\asset\Decoder.pt not exist.
[+0800 20240828 17:55:33] [INFO] ChatTTS | dl | downloading https://github.com/fumiama/RVC-Models-Downloader/releases/download/v0.2.5/rvcmd_windows_amd64.zip
[+0800 20240828 17:55:35] [INFO] ChatTTS | dl | downloaded.
[+0800 20240828 17:55:36] [INFO] ChatTTS | dl | extracted into C:\Users\1\AppData\Local\Temp\tmpm70sje9x
panic: The handle is invalid.

goroutine 1 [running]:
rvcmd/console.init.0()
        rvcmd/console/console_windows.go:46 +0x1d4
[+0800 20240828 17:55:36] [INFO] ChatTTS | dl | checking assets...
[+0800 20240828 17:55:36] [INFO] ChatTTS | dl | E:\ChatTTS\asset\Decoder.pt not exist.
[+0800 20240828 17:55:36] [ERRO] ChatTTS | core | download to local path E:\ChatTTS failed.
[+0800 20240828 17:55:36] [ERRO]  WebUI  | webui | Models load failed.

**Comment by fumiama** [comment]
请使用powershell/cmd运行python命令。

**Comment by gdmec07150701** [comment]
你好 是否有新的群可以加入，我看目前发布的4个群都是满员的呢
