### ISSUE TITLE
一个windows配置过程

### ISSUE THREAD

**Issue by cacard** [2noise/ChatTTS#73]
1【手动下载model，见huggingface；自动下载的话，1，2忽略】
2【修改core.py】里面的路径为本地
在core.py中，有load_models，可以修改为本地路径
—— source修改为：local
—— local_path修改为：你的model的绝对路径

3【配置环境】
—— 先配置个venv，不细说。
—— 先不要直接安装requirements
—— 安装pytorch 2.1.0，否则可能会出现一些错误
—— 参考requirements安装其它依赖

【如果是手动下载的model】：
—— 把huggingface pt/config下面的所有config_开头的，改成去掉config_，并把path.yaml里面的/改成\【因为是windows】

4【运行】
用这个代码：
https://gist.github.com/cacard/612b29cc88cd4ef453a59a5ac999b1af

**Comment by yuhaolove** [comment]
对于还没有安装成功或使用成功的用户，这个WebUI可以大大帮助您。请大家尝试一下，并告诉我您的反馈。您的意见对改进这个工具、让它变得更加用户友好非常重要。

[ChatTTS-WebUI](https://github.com/yuhaolove/ChatTTS-WebUI)

**Comment by zpengcom** [comment]
> 1【手动下载model，见huggingface；自动下载的话，1，2忽略】 2【修改core.py】里面的路径为本地 在core.py中，有load_models，可以修改为本地路径 —— source修改为：local —— local_path修改为：你的model的绝对路径
> 
> 3【配置环境】 —— 先配置个venv，不细说。 —— 先不要直接安装requirements —— 安装pytorch 2.1.0，否则可能会出现一些错误 —— 参考requirements安装其它依赖
> 
> 【如果是手动下载的model】： —— 把huggingface pt/config下面的所有config_开头的，改成去掉config_，并把path.yaml里面的/改成\【因为是windows】
> 
> 4【运行】 用这个代码： https://gist.github.com/cacard/612b29cc88cd4ef453a59a5ac999b1af


还是报错了
![image](https://github.com/2noise/ChatTTS/assets/8217132/73929972-9262-4474-82ca-e8a8fe3efa9c)

**Comment by bicoll** [comment]
> > 1【手动下载model，见huggingface；自动下载的话，1，2忽略】 2【修改core.py】里面的路径为本地 在core.py中，有load_models，可以修改为本地路径 —— source修改为：local —— local_path修改为：你的model的绝对路径
> > 3【配置环境】 —— 先配置个venv，不细说。 —— 先不要直接安装requirements —— 安装pytorch 2.1.0，否则可能会出现一些错误 —— 参考requirements安装其它依赖
> > 【如果是手动下载的model】： —— 把huggingface pt/config下面的所有config_开头的，改成去掉config_，并把path.yaml里面的/改成\【因为是windows】
> > 4【运行】 用这个代码： https://gist.github.com/cacard/612b29cc88cd4ef453a59a5ac999b1af
> 
> 还是报错了 ![image](https://private-user-images.githubusercontent.com/8217132/335290845-73929972-9262-4474-82ca-e8a8fe3efa9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTQ5MzMsIm5iZiI6MTcxNzE1NDYzMywicGF0aCI6Ii84MjE3MTMyLzMzNTI5MDg0NS03MzkyOTk3Mi05MjYyLTQ0NzQtODJjYS1lOGE4ZmUzZWZhOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTEyMzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk0YWI0ZmVjMmJlZWQ4Njg5YzBiOTVhMWQzOWFhMTdlYzQ2MzQ3NjNjMjJiYTIwZjc1YzJmYTE2NGM5Y2IwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kaucy41ghj8MhfR2t8igqASzAKMmjRsUOwJuK9E7RlM)

我也是卡到这里，折腾了一天，python的依赖管理真是差
