### ISSUE TITLE
ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by isaacchan15947** [2noise/ChatTTS#736]
大大你好, 我在使用ChatTTS 的Google Lab colab版本

在Inference項目下的Zero shot (simulate speaker)運行時, 系統說「ModuleNotFoundError: No module named 'tools'」然後把第一句「from tools.audio import load_audio」紅標起來, 請問我可以怎麼辦?

![未命名](https://github.com/user-attachments/assets/663fcd2a-48ed-478b-ba82-58efc5118b6a)

**Comment by fumiama** [comment]
此处需要修改为
```py
from ChatTTS.tools.audio import load_audio
```
不过目前即使修改，也会遇到 #603 的问题，临时的解决办法是使用`device=cpu`推理，这样会让速度下降。请等待后续修复。

**Comment by IrisSally** [comment]
> 此处需要修改为
> 
> ```python
> from ChatTTS.tools.audio import load_audio
> ```
> 
> 不过目前即使修改，也会遇到 #603 的问题，临时的解决办法是使用`device=cpu`推理，这样会让速度下降。请等待后续修复。



I submitted a PR  #736 to fix the device mismatch issue.

**Comment by romain130492** [comment]
```
from ChatTTS.tools.audio import load_audio
```

```
ModuleNotFoundError: No module named 'ChatTTS.tools'
```

怎么办。？ @fumiama fu 谢谢
