### ISSUE TITLE
我写了一个WebUI，非常适合小白来使用，分享给大家

### ISSUE THREAD

**Issue by yuhaolove** [2noise/ChatTTS#74]
为ChatTTS项目开发了一个WebUI。这个界面设计得非常友好，非常适合不熟悉编程的小白用户使用。通过这个WebUI，您可以无需编写任何代码就能与ChatTTS模型进行交互，极大地简化了使用过程。

对于还没有安装成功或使用成功的用户，这个WebUI可以大大帮助您。请大家尝试一下，并告诉我您的反馈。您的意见对改进这个工具、让它变得更加用户友好非常重要。

> [ChatTTS-WebUI](https://github.com/yuhaolove/ChatTTS-WebUI)

**Comment by AkaBob0516** [comment]
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
这个怎么解决？ 没法找到GPU

**Comment by sihai2933** [comment]
> WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead 这个怎么解决？ 没法找到GPU

正常的，你电脑没有独立显卡，程序会自动转向调用CPU

**Comment by charrency** [comment]
> WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead 这个怎么解决？ 没法找到GPU

你看看是不是说少了个spk_stat.pt

**Comment by jianchang512** [comment]
也可以看看我的 https://github.com/jianchang512/ChatTTS-ui

![image](https://github.com/2noise/ChatTTS/assets/3378335/9b7e78e5-cb16-4870-913e-9ca5e145a54b)
