### ISSUE TITLE
停顿[uv_break]和大笑[laugh]失效

### ISSUE THREAD

**Issue by XHB-ZMM** [2noise/ChatTTS#740]
![image](https://github.com/user-attachments/assets/eff47751-1eb0-46e0-bcd1-3e6c8630eb6d)
如图所示，为什么我的停顿和大笑都不起作用，我是直接pip install CahtTTS。请问各位大佬，这是什么回事呀？

**Comment by fumiama** [comment]
pip安装的是较旧的版本，未修复此问题。请使用git上最新提交。
