### ISSUE TITLE
为什么mac mps 加速比cpu 慢

### ISSUE THREAD

**Issue by wuhongsheng** [2noise/ChatTTS#742]

**Comment by fumiama** [comment]
因为pytorch对mps的适配不完善，mps运行时内存泄漏，导致大量时间用于写入磁盘缓存。

**Comment by wuhongsheng** [comment]
> 因为pytorch对mps的适配不完善，mps运行时内存泄漏，导致大量时间用于写入磁盘缓存。

能说下具体是哪个算子或操作导致性能瓶颈吗

**Comment by fumiama** [comment]
> 能说下具体是哪个算子或操作导致性能瓶颈吗

mask相关的。
