### ISSUE TITLE
API如何控制生成的音频音量

### ISSUE THREAD

**Issue by 6666665** [2noise/ChatTTS#754]
我现在遇到的问题就是 用API生成的音频 ，音量有时候大有时候小
有没有参数可以控制，非常感谢！！！

**Comment by fumiama** [comment]
目前没有，可以在后端使用相关音频处理方法手动均衡。

**Comment by avords** [comment]
> 目前没有，可以在后端使用相关音频处理方法手动均衡。

语速和音量怎么控制呢？没看到example

**Comment by 6666665** [comment]
> 目前没有，可以在后端使用相关音频处理方法手动均衡。

好的谢谢。我对音频这块不是很懂。我是否可以通过ffmpeg对音频进行 音量处理呢

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Comment by rose07** [comment]
> 我现在遇到的问题就是 用API生成的音频 ，音量有时候大有时候小 有没有参数可以控制，非常感谢！！！

https://tts.byylook.com/ai/text-to-speech
