### ISSUE TITLE
加载模型

### ISSUE THREAD

**Issue by gaoleihero** [2noise/ChatTTS#76]
![image](https://github.com/2noise/ChatTTS/assets/31463641/800336a7-74a0-4415-824c-9c0a6df204b7)

**Comment by yuhaolove** [comment]
没有下载好模型


对于还没有安装成功或使用成功的用户，这个WebUI可以大大帮助您。请大家尝试一下，并告诉我您的反馈。您的意见对改进这个工具、让它变得更加用户友好非常重要。

[ChatTTS-WebUI](https://github.com/yuhaolove/ChatTTS-WebUI)

**Comment by gaoleihero** [comment]
重新下载了，依然是这个报错
