### ISSUE TITLE
API参数没注释

### ISSUE THREAD

**Issue by yushanyong** [2noise/ChatTTS#763]
```py
ChatTTS.Chat.infer(
    self,
    text,
    stream=False,
    lang=None,
    skip_refine_text=False,
    refine_text_only=False,
    use_decoder=True,
    do_text_normalization=True,
    do_homophone_replacement=True,
    params_refine_text=<ChatTTS.core.Chat.RefineTextParams object at 0x17ae4bee0>,
    params_infer_code=<ChatTTS.core.Chat.InferCodeParams object at 0x17ae4be50>,
)
```
其中如下几个参数，不理解是什么意思，具体是什么作用
```py
    lang=None,
    skip_refine_text=False,
    refine_text_only=False,
    use_decoder=True,
```

**Comment by fumiama** [comment]
- **lang**: en 或 zh，不指定则自动检测。
- **skip_refine_text**: 跳过 refine_text 步骤
- **refine_text_only**: 仅进行 refine_text 步骤
- **use_decoder**: 使用`Decoder.pt`而非`DVAE_full.pt`（一般来说效果更差）

**Comment by yushanyong** [comment]
好的，谢谢！

**Comment by LingfengPan** [comment]
麻烦请教下这两个参数是什么意思呀，do_text_normalization 和 do_homophone_replacement

**Comment by fumiama** [comment]
> 麻烦请教下这两个参数是什么意思呀，do_text_normalization 和 do_homophone_replacement

text_normalization 是将文本正规化为模型支持的文字，如`12`变为`十二`。homophone_replacement 将生僻字替换为同音的简单字，你可以用`关关雎鸠，在河之洲`做测试。
