### ISSUE TITLE
支持多少种音色？

### ISSUE THREAD

**Issue by WGS-note** [2noise/ChatTTS#765]
hello，想问一下，可以支持多少种音色？

**Comment by fumiama** [comment]
理论上几乎没有上限。

**Comment by WGS-note** [comment]
请问，那如何更换不同音色呢？

**Comment by fumiama** [comment]
你运行WebUI，可以随机音色种子。

**Comment by WGS-note** [comment]
好，谢谢！

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Comment by rose07** [comment]
> 请问，那如何更换不同音色呢？

https://tts.byylook.com/ai/text-to-speech
