### ISSUE TITLE
There may be page display abnormalities on laptops with a resolution of 2K or higher

### ISSUE THREAD

**Issue by dd3389** [2noise/ChatTTS#766]
官方windows代码可能存在问题，经本人测试，ui页面在2K分辨率以上的笔记本电脑上显示会出现版面混乱的问题（将系统分辨率从2k改为1920*1080后即正常），以下为chattts某一分支存在的问题，实际测试其他分支存在同样的问题，最终的bug应该在官方源码中，是否有相关的解决方案呢
There may be page display abnormalities on laptops with a resolution of 2K or higher；

The following is a UI interface display issue that exists in a certain branch of chattts. In actual testing, almost all branches have the same problem, and these branches are based on the official source code

![QQ图片20240926202530](https://github.com/user-attachments/assets/99d518f3-beba-4f9d-a9dd-becc58db6e8e)

**Comment by fumiama** [comment]
gradio问题吧，和ChatTTS无关，建议找gradio报告。
