### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by benojan** [2noise/ChatTTS#771]
一开始没有用GPU，从这里解决了，
> https://github.com/jianchang512/ChatTTS-ui/issues/35

我的CUDA是11.x，所以按照操作：
> pip uninstall -y torch torchaudio
> 如果cuda是11.x 执行这个
> pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu118
> 如果是 12.x 执行这个
> pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu121

----------------------------
现在出现了新的问题：
> RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

貌似是因为GPU太小，网上说要把batch_size调小，但是我不知道如何调？谁知道怎么解决吗？

**Comment by benojan** [comment]
我的GPU是2G

**Comment by fumiama** [comment]
CUDA自身版本问题，与本程序无关。
