### ISSUE TITLE
Add Ascend NPU as a backend

### ISSUE THREAD

**Issue by shen-shanshan** [2noise/ChatTTS#776]
## Description

Ascend is a full-stack AI computing infrastructure for industry applications and services based on Huawei Ascend processors and software. For more information about Ascend, see [<u>Ascend Community</u>](https://www.hiascend.com/en/).

[<u>CANN</u>](https://www.hiascend.com/en/software/cann) (Compute Architecture of Neural Networks), developped by Huawei, is a heterogeneous computing architecture for AI.

Pytorch has officially announced [<u>support for Ascend NPU</u>](https://pytorch.org/blog/pytorch-2-1/) (through key PrivateUse1), please see the PrivateUse1 tutorial [<u>here</u>](https://pytorch.org/tutorials/advanced/privateuseone.html).

## Motivation

Currently, the number of developers using Ascend NPU for AI training and inferencing has been significantly increasing, especially in China. Therefore, I would like to add support for Ascend NPU backend for this project.

see：#662.

## Examples

To start with, the library `torch_npu` should be installed and imported, after which we can set `torch.device("npu:0")` if `torch.npu.is_available()` is `True`. Part of the codes are showed below:

```diff, python
# ChatTTS/utils/gpu.py:
  import torch
+ import torch_npu

...

  def select_device(min_memory=2047, experimental=False):
      if torch.cuda.is_available():
          ...
+     elif torch.npu.is_available():
+         ...
+         logger.get_logger().info("found Ascend NPU, using NPU.")
+         device = torch.device("npu:0")
      elif torch.backends.mps.is_available():
          ...
      else:
          logger.get_logger().warning("no GPU found, use CPU instead")
          device = torch.device("cpu")

      return device
```

Plus, there are some other places of the codes might be adjusted, which won't be too much.

What do you think of this idea? Feel free to leave comments to guide me in further improvements~

**Comment by UNSaWEN** [comment]
> > Plus, there are some other places of the codes might be adjusted, which won't be too much.
> 
> We're welcome for the people who have this NPU to implement it, test it and then open a PR.

modify only this one for 1st test version may be a good idea.  [torchversion](https://github.com/2noise/ChatTTS/blob/main/ChatTTS/utils/gpu.py)

I may be able free to test  it at november using 310B.

can chattts using onnx for offline infer?
(this will make convert to om and runing much easier)

**Comment by shen-shanshan** [comment]
@fumiama
The PR has been opened, see: #777, thanks for reviewing~
