### ISSUE TITLE
Sample Audio和Sample Audio Code怎么用？

### ISSUE THREAD

**Issue by yourengod** [2noise/ChatTTS#781]
在Sample Audio上传后，是要复制Sample Audio Code这个到Speaker Embedding这里吗？我试了一下，生成不出来声音啊。请问为什么啊？

**Comment by yourengod** [comment]
谢谢，你好，stream mode报错：”FileNotFoundError: [Errno 2] No such file or directory: '69dlu8rbgix/126256225864384/50/playlist.m3u8'“

**Comment by fumiama** [comment]
已知问题，应该是gradio本身的问题，如果自己对接stream接口，不会有这个报错。
