### ISSUE TITLE
使用sample_audio_speaker功能生成其它音色会因为输入音频太长导致推理失败吗？

### ISSUE THREAD

**Issue by 0zhangsan0** [2noise/ChatTTS#784]
我尝试了几段音频，文本分别为：
1、txt_smp="从博弈论的定义中我们知道[uv_break]，双方[uv_break]或者多方[uv_break]进行博弈的最终目的[uv_break]，都是为自己争取最大利益[uv_break]，因此[uv_break]利益是博弈中[uv_break]必不可少的[uv_break]一个要素[uv_break]。"，新的音频生成成功。
2、txt_smp="好久不见。你[uv_break]还记得咱们大学那会儿吗？你听到的是[uv_break]开源项目 T T S List[uv_break]。那可是风华正茂的[uv_break]岁月啊[uv_break]！还记得[uv_break]咱俩爬那个[uv_break]山顶[uv_break]看日出吗[uv_break]？当时许的愿望[uv_break]，我到现在还记得呢[uv_break]。"，生成成功。
3、txt_smp="会议强调[uv_break]，开展[uv_break]知识产权综合管理改革试点[uv_break]，要紧扣[uv_break]创新发展需求[uv_break]，发挥[uv_break]专利[uv_break]、商标[uv_break]、版权[uv_break]等知识产权的引领作用[uv_break]，打通知识产权[uv_break]创造[uv_break]、运用[uv_break]、保护[uv_break]、管理[uv_break]、服务[uv_break]全链条[uv_break]，建立[uv_break]高效的知识产权综合管理体制[uv_break]，构建便民利民的[uv_break]知识产权公共服务体系[uv_break]，探索[uv_break]支撑创新发展的知识产权运行机制[uv_break]，推动形成[uv_break]权界清晰[uv_break]、分工合理[uv_break]、责权一致[uv_break]、运转高效的[uv_break]体制机制[uv_break]。",生成失败。
具体报错为：
Traceback (most recent call last):
  File "F:\Sounds Transfor\ChatTTS-main\news_report_spk.py", line 26, in <module>
    wav = chat.infer(
  File "F:\Sounds Transfor\ChatTTS-main\ChatTTS\core.py", line 220, in infer
    return next(res_gen)
StopIteration
生成目标音频均为text = "这些建议是根据搜索结果中提供的信息总结的，具体解决方案可能需要根据你的实际情况进行调整。"

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Comment by fumiama** [comment]
会。参考音频不宜太长，如果之前单独生成30s为宜，那么加上参考后，参考+生成不超过30s为宜。
