### ISSUE TITLE
为什么生成的音频有很大的噪声

### ISSUE THREAD

**Issue by dyjiangjh** [2noise/ChatTTS#79]
我生成的音频有很大的背景噪声，不知道为什么

**Comment by ligenxun** [comment]
因为开源模型里面，估计生成时候添加高音，避免违法使用。

**Comment by dyjiangjh** [comment]
需要商业版的才能没有背景杂音吗？另外这个好像比较慢，不能做到实时音频流

**Comment by ligenxun** [comment]
不是，是他们编码上加入高频声音处理了。看他们demo代码就懂了，如果看不懂那就没法。实时的话，这个得找他们联系商用定制化开发了吧。感觉这个对MCN来说也是一个颠覆，尤其是二次元套皮主播来说，以后基本上就是赛博主播了吧。

**Comment by GioGioBond** [comment]
我用的时候，文本过长就会有噪声，文本截断短点就没事
