### ISSUE TITLE
我发现有时候越说越快 ，不知道是不是正常的？

### ISSUE THREAD

**Issue by gg22mm** [2noise/ChatTTS#790]
我发现会越说越快 ，不知道是不是正常的？

[测试声音.zip](https://github.com/user-attachments/files/17408151/default.zip)
params_infer_code = ChatTTS.Chat.InferCodeParams(
    spk_emb=spk_dic,
    temperature=0.3,
    top_P=0.7,
    top_K=20,
)

我也测试了： https://huggingface.co/spaces/Dzkaka/ChatTTS

内容： 9月17日凌晨，刚刚在全国田径锦标赛夺冠的吴艳妮在社交平台发文，为自己第一次实现年度大满贯而感到自豪，同时祝大家中秋节快乐

**Comment by fumiama** [comment]
末尾的句号不要忘加。
