### ISSUE TITLE
在运行官方给的Advanced Usage示例时报错

### ISSUE THREAD

**Issue by AstronautBase** [2noise/ChatTTS#794]
运行Basic Usage没有问题，但运行Advanced Usage时出现以下报错

Traceback (most recent call last):
  File "xxx/test1.py", line 10, in <module>
    rand_spk = chat.sample_random_speaker()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx/ChatTTS/ChatTTS/core.py", line 160, in sample_random_speaker
    return self.speaker.sample_random()
           ^^^^^^^^^^^^
AttributeError: 'Chat' object has no attribute 'speaker'

![屏幕截图 2024-10-21 154855](https://github.com/user-attachments/assets/841db745-ee6a-4ff0-8991-93a6001a804b)

**Comment by Jarvanen** [comment]
请问下解决了吗  是什么原因

**Comment by roseonB612** [comment]
请问下解决了吗 是什么原因
