### ISSUE TITLE
无法拉起webui

### ISSUE THREAD

**Issue by Djooxx** [2noise/ChatTTS#798]
![image](https://github.com/user-attachments/assets/1c26a76a-9165-4500-a300-a2072128f758)
执行
git clone https://github.com/2noise/ChatTTS
cd ChatTTS
pip install --upgrade -r requirements.txt
python examples/web/webui.py

没有任何日志输出,8080端口也无法访问

**Comment by fumiama** [comment]
确保python正确安装。
