### ISSUE TITLE
怎么调整成女生音色?

### ISSUE THREAD

**Issue by ghost** [2noise/ChatTTS#80]
怎么调整成女生音色?

**Comment by charSLee013** [comment]
通过设置`torch.manual_seed(SEED)`来调整声色
```python
torch.manual_seed(1122)  # 比如说1122是女生音色
params_infer_code = {
        'spk_emb': chat.sample_random_speaker(), 
        'temperature': 0.1,
        'top_P': 0.9,
        'top_K': 20,
        }

wavs = chat.infer([<put you text in here>], use_decoder=True,
                  params_infer_code=params_infer_code)
```

**Comment by aeknow** [comment]
> 通过设置`torch.manual_seed(SEED)`来调整声色
> 
> ```python
> torch.manual_seed(1122)  # 比如说1122是女生音色
> params_infer_code = {
>         'spk_emb': chat.sample_random_speaker(), 
>         'temperature': 0.1,
>         'top_P': 0.9,
>         'top_K': 20,
>         }
> 
> wavs = chat.infer([<put you text in here>], use_decoder=True,
>                   params_infer_code=params_infer_code)
> ```

请问大佬这个音色表在哪里可以找到？

**Comment by ChinaStark** [comment]
me too

**Comment by MengXiangxi** [comment]
> 通过设置`torch.manual_seed(SEED)`来调整声色
> 
> ```python
> torch.manual_seed(1122)  # 比如说1122是女生音色
> params_infer_code = {
>         'spk_emb': chat.sample_random_speaker(), 
>         'temperature': 0.1,
>         'top_P': 0.9,
>         'top_K': 20,
>         }
> 
> wavs = chat.infer([<put you text in here>], use_decoder=True,
>                   params_infer_code=params_infer_code)
> ```

我不认为它有效果。
