### ISSUE TITLE
无法合成数字

### ISSUE THREAD

**Issue by di-osc** [2noise/ChatTTS#841]
我在合成电话号码相关的文本时候碰到数字无法合成的问题。具体代码如下：

chat = Chat()
chat.load()

text = "我的电话号码是1234567889“
waveform = chat.infer(text)
此时合成的声音没有后面的数字内容并且打印如下信息
**found invalid characters: {'8', '2', '3', '6', '7', '4', '5', '1'}**

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the reject_pattern in the Normalizer class to allow digits (0-9) in the text, fixing the issue where numbers were being filtered out during normalization.

You can review changes in this commit: https://github.com/kkpo4553/2noise-ChatTTS-841/commit/11a65fc4c78ac8ee085670bc074b080b3e0824ed.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by hwzhang1987** [comment]
遇到同样的问题、但是下载的UI完整包（ChatTTS-ui ）的可以，如何解决？
你后来解决了吗？
