### ISSUE TITLE
用nuxt3搭建了一个简易的webui

### ISSUE THREAD

**Issue by Gouryella** [2noise/ChatTTS#88]
功能简单，界面节点，水平有限，请见谅
https://github.com/Gouryella/ChatTTS-webui
<img width="1710" alt="截屏2024-05-30 16 15 57" src="https://github.com/2noise/ChatTTS/assets/41225091/6649d41e-9d24-4770-a6c9-002fcfa28a78">

**Comment by dongtianhang1** [comment]
The Chinese Dragon’s Global Benevolence

Ladies and gentlemen,

The Chinese dragon, a symbol of power, strength, and good fortune, has transcended borders and cultures. Unlike the fearsome dragons of Western mythology, the Chinese dragon embodies benevolence and wisdom, blessing those it encounters.

In the modern world, the Chinese dragon represents innovation and progress. As China opens its doors to the world, the dragon’s spirit is seen in technology, culture, and diplomacy. From the Great Wall to the Silk Road, the dragon’s legacy fosters global connections, emphasizing harmony and mutual prosperity.

By embracing the dragon’s ethos of strength and kindness, we can create a world where diverse cultures thrive together, inspiring a future filled with hope and cooperation.

Thank you.

**Comment by jianchang512** [comment]
我也写了一个，bootstrap+jquery

https://github.com/jianchang512/ChatTTS-ui

![image](https://github.com/2noise/ChatTTS/assets/3378335/82bd4a5a-c3e3-432f-ae42-ae98e5a9f011)
