### ISSUE TITLE
大家有没有发现感叹号、减号都会发音，而且有时候会多发一些音  挺奇怪的。

### ISSUE THREAD

**Issue by violet17** [2noise/ChatTTS#90]
比如输入：
你好！我是人工智能助手 Chat G L M - 6 B,很高兴见到你,欢迎问我任何问题。AI PC是2024年的一大热点，文生文应用、文生图应用非常hot!

**Comment by tongxin3267** [comment]
+1

> 比如输入： 你好！我是人工智能助手 Chat G L M - 6 B,很高兴见到你,欢迎问我任何问题。AI PC是2024年的一大热点，文生文应用、文生图应用非常hot!

**Comment by lich99** [comment]
目前符号只有逗号和句号支持, 其他符号会随机发音

**Comment by violet17** [comment]
@lich99 所以需要对文本做一个处理？
