### ISSUE TITLE
数字和字母都不行！

### ISSUE THREAD

**Issue by xiaojianbj** [2noise/ChatTTS#91]
“数字：1，2，3，4，5，6，7，8，9，0；字母：a，b，c，d，e，f，g”
大家试试这句话，输出的语音乱七八糟的

**Comment by findlymw** [comment]
我这边没有问题，我生成的prompt是：我们现在开始数数，一 二 三 四 五 六 七 八 九 十，现在开始说字母，A B C，还有小写字母：a b c d e f g

我觉得是chatTTS的embedding模型没有识别出阿拉伯数字，写成中文就行了

**Comment by lin16303** [comment]
发现同样问题，中文语句中的阿拉伯数字无法准确读出，或者说是乱码，比如10斤苹果5.5元

**Comment by zhuyr97** [comment]
我尝试中英文混杂，针对英语内容的输出也不好！

**Comment by JohnnyZhang0628** [comment]
请问有解决办法吗？我想生成这样一句语音：正方形ABCD。
有什么好的办法吗？

**Comment by songofhawk** [comment]
这个问题，到现在都没解决么？
