### ISSUE TITLE
数字、标点符号，字母，都会出错

### ISSUE THREAD

**Issue by weiyi88** [2noise/ChatTTS#93]
数字、标点符号，字母，都会出错

**Comment by weiyi88** [comment]
123456789,1,2,3,4,5,6。how are you ！ I'm fine , thank you 。啊！啊？啊，啊。你知道么，你知不知道，我问你知不知道到啊，你真的是，abb一样，246一样。能不能说清楚&（*"


试试这个，精神攻击拉满 。。。。。。。。

**Comment by zhchx601** [comment]
唐

**Comment by ain-soph** [comment]
跟模型没关系，应该是前端的文本转音素没做好

**Comment by even1207** [comment]
> 跟模型没关系，应该是前端的文本转音素没做好

请问怎么文本转音素呀
