### ISSUE TITLE
如何将运行的wav保存下来呢？

### ISSUE THREAD

**Issue by Haroldhy** [2noise/ChatTTS#95]
import ChatTTS
from IPython.display import Audio

chat = ChatTTS.Chat()
chat.load_models()

texts = ["<PUT YOUR TEXT HERE>",]

wavs = chat.infer(texts, use_decoder=True)
Audio(wavs[0], rate=24_000, autoplay=True)
请问这段代码生成的wav要如何正确保存到本地呢？

我也遇到了和https://github.com/2noise/ChatTTS/issues/92一样的问题，而且语音也没有自动播放。
我认为就是生成的音频有问题，因为同一段话我的进度条都不一样

**Comment by pjq** [comment]
https://github.com/2noise/ChatTTS/pull/21
