### ISSUE TITLE
使用mps版本内存爆掉了，芯片：Apple M2 Pro

### ISSUE THREAD

**Issue by hoooou** [2noise/ChatTTS#96]
降级会cpu版本，可以正常运行

**Comment by lin16303** [comment]
不爆的时候速度如何？以下是4090
  7%|█████▋                                                                           | 27/384 [00:00<00:08, 44.05it/s]
  9%|███████▏                                                                         | 34/384 [00:00<00:09, 35.20it/s]
 11%|█████████                                                                      | 234/2048 [00:05<00:42, 43.04it/s]
 14%|███████████▍                                                                   | 295/2048 [00:06<00:40, 43.71it/s]
  2%|█▋                                                                                | 8/384 [00:00<00:06, 62.58it/s]
  5%|████▎                                                                          | 112/2048 [00:01<00:26, 72.45it/s]

**Comment by hoooou** [comment]
> 不爆的时候速度如何？以下是4090 7%|█████▋ | 27/384 [00:00<00:08, 44.05it/s] 9%|███████▏ | 34/384 [00:00<00:09, 35.20it/s] 11%|█████████ | 234/2048 [00:05<00:42, 43.04it/s] 14%|███████████▍ | 295/2048 [00:06<00:40, 43.71it/s] 2%|█▋ | 8/384 [00:00<00:06, 62.58it/s] 5%|████▎ | 112/2048 [00:01<00:26, 72.45it/s]

不爆的时候，也只有1it/s，比cpu还要慢

**Comment by Richard0403** [comment]
好巧， 我用的Mac pro M2， CPU跑的，性能和4070Ti显卡速度一样

**Comment by passioncsu** [comment]
所以m2 到底能跑起来吗  我是macmini m2

**Comment by gougang** [comment]
![image](https://github.com/user-attachments/assets/ca16c7e4-10a8-41ea-ba86-3387cd48fdae)
